import {
  DepotId,
  YardTruck,
  DepotCapacityState,
  DepotEquipmentState,
  DepotBottleneckDiagnosis,
  DepotForecast,
  DepotKpiSummary,
} from "@/types/flowguard";

export function initAllYardTrucks(): Record<DepotId, YardTruck[]> {
  return {
    nairobi: [
      {
        id: "TRK-NBO-01",
        registration: "KDA 123X",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-NBO-8821",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P02",
        timeInStageMin: 27,
        baselineStageMin: 18,
        dwellDeltaMin: 9,
        predictedGateOut: "11:45 AM",
        riskStatus: "RED",
        riskLabel: "Critical Delay Risk (+9m above SLA)",
        nextAction: "Complete loading & dispatch to weighbridge",
        flowGuardStatus: "AUTO-SEQUENCED",
        depotId: "nairobi",
        expectedArrival: "10:15 AM",
        predictedLoadingStart: "10:35 AM",
        predictedTurnaroundMin: 118,
        baselineTurnaroundMin: 65,
        confidencePct: 92,
        whyAtRisk: {
          cause: "Demand surge + compatible bay offline + 14% flow rate drop",
          factors: [
            "14 collection orders forecast in same 45-min window",
            "Compatible PMS loading position offline for calibration",
            "Loading performance 14% below baseline at secondary gantry",
          ],
        },
        actionDetail: {
          interventionId: "INT-8801",
          proposedAction: "Re-sequence upcoming orders and adjust internal processing priority to auxiliary position.",
          actionStatus: "AUTO-EXECUTED",
          expectedImpactMin: 38,
          approvalState: "AUTO",
        },
        stageTimestamps: {
          gateIn: "10:18 AM",
          validation: "10:32 AM",
          loading: "10:48 AM",
        },
      },
      {
        id: "TRK-NBO-02",
        registration: "KDD 441L",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-NBO-9914",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 40000,
        compartmentsCount: 4,
        currentStage: "Loading",
        assignedPosition: "P06",
        timeInStageMin: 21,
        baselineStageMin: 18,
        dwellDeltaMin: 3,
        predictedGateOut: "12:10 PM",
        riskStatus: "RED",
        riskLabel: "SLA Threshold Imminent Breach in 35m",
        nextAction: "Dual-hose allocation pending supervisor sign-off",
        flowGuardStatus: "APPROVAL PENDING",
        depotId: "nairobi",
        expectedArrival: "10:25 AM",
        predictedLoadingStart: "10:50 AM",
        predictedTurnaroundMin: 105,
        baselineTurnaroundMin: 65,
        confidencePct: 88,
        whyAtRisk: {
          cause: "Multi-compartment AGO order during intake peak + gate verification backlog",
          factors: [
            "Multi-compartment AGO order scheduled during peak intake",
            "Electronic seal integrity verification backlog at gate",
            "Secondary pump loading performance variance",
          ],
        },
        actionDetail: {
          interventionId: "INT-8802",
          proposedAction: "Dual-hose bay allocation and fast-track clearance pass.",
          actionStatus: "APPROVAL REQUIRED",
          expectedImpactMin: 26,
          approvalState: "REQUIRED",
        },
        stageTimestamps: {
          gateIn: "10:26 AM",
          validation: "10:45 AM",
          loading: "11:02 AM",
        },
      },
      {
        id: "TRK-NBO-03",
        registration: "KCA 502Y",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-NBO-7719",
        product: "PMS (Super Unleaded)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 34,
        baselineStageMin: 15,
        dwellDeltaMin: 19,
        predictedGateOut: "12:25 PM",
        riskStatus: "AMBER",
        riskLabel: "Validation Dwell (+19m above normal)",
        nextAction: "Awaiting KRA customs seal clearance",
        flowGuardStatus: "MONITORED",
        depotId: "nairobi",
        expectedArrival: "09:55 AM",
        predictedTurnaroundMin: 85,
        baselineTurnaroundMin: 65,
        confidencePct: 89,
        whyAtRisk: {
          cause: "Electronic customs transit manifest reconciliation delay",
          factors: [
            "KRA electronic cargo tracking system confirmation latency",
            "Inspector multi-tanker batch verification in progress",
          ],
        },
        actionDetail: {
          proposedAction: "Escalate electronic release priority to terminal controller.",
          actionStatus: "MONITORING",
          expectedImpactMin: 15,
          approvalState: "NONE",
        },
        stageTimestamps: {
          gateIn: "10:02 AM",
          validation: "10:14 AM",
        },
      },
      {
        id: "TRK-NBO-04",
        registration: "KDE 910M",
        omc: "Hass Petroleum",
        orderNumber: "LO-NBO-6612",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 22,
        baselineStageMin: 10,
        dwellDeltaMin: 12,
        predictedGateOut: "12:40 PM",
        riskStatus: "AMBER",
        riskLabel: "Gate Queue Congestion (+12m)",
        nextAction: "Proceed to Scale 2 upon signal",
        flowGuardStatus: "OPTIMIZED",
        depotId: "nairobi",
        expectedArrival: "10:30 AM",
        predictedTurnaroundMin: 79,
        baselineTurnaroundMin: 65,
        confidencePct: 84,
        stageTimestamps: {
          gateIn: "10:28 AM",
        },
      },
      {
        id: "TRK-NBO-05",
        registration: "KCB 311V",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-NBO-5503",
        product: "DPK (Dual Purpose Kerosene)",
        quantityLitres: 28000,
        compartmentsCount: 2,
        currentStage: "Validation / Release",
        timeInStageMin: 14,
        baselineStageMin: 15,
        dwellDeltaMin: -1,
        predictedGateOut: "12:15 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Nominal)",
        nextAction: "Assign to Bay P05 upon completion of valve service",
        flowGuardStatus: "OPTIMIZED",
        depotId: "nairobi",
        predictedTurnaroundMin: 62,
        baselineTurnaroundMin: 65,
        confidencePct: 91,
        stageTimestamps: {
          gateIn: "10:22 AM",
          validation: "10:36 AM",
        },
      },
      {
        id: "TRK-NBO-06",
        registration: "KDG 808K",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-NBO-8840",
        product: "PMS (Super Unleaded)",
        quantityLitres: 35000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 8,
        baselineStageMin: 10,
        dwellDeltaMin: -2,
        predictedGateOut: "11:32 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Pre-cleared)",
        nextAction: "Proceed to final egress tare scale",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 58,
        baselineTurnaroundMin: 65,
        confidencePct: 96,
        stageTimestamps: {
          gateIn: "09:40 AM",
          validation: "09:54 AM",
          loading: "10:12 AM",
          readyToExit: "10:48 AM",
        },
      },
      {
        id: "TRK-NBO-07",
        registration: "KCD 645B",
        omc: "Galana Oil Kenya",
        orderNumber: "LO-NBO-9922",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 6,
        baselineStageMin: 10,
        dwellDeltaMin: -4,
        predictedGateOut: "11:28 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Complete final exit ticket printing",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 54,
        baselineTurnaroundMin: 65,
        confidencePct: 95,
        stageTimestamps: {
          gateIn: "09:44 AM",
          validation: "09:58 AM",
          loading: "10:16 AM",
          readyToExit: "10:52 AM",
        },
      },
      {
        id: "TRK-NBO-08",
        registration: "KDH 229R",
        omc: "Petrocity Energy",
        orderNumber: "LO-NBO-4418",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 8,
        baselineStageMin: 10,
        dwellDeltaMin: -2,
        predictedGateOut: "12:35 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Tare weighbridge reading in progress",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 60,
        baselineTurnaroundMin: 65,
        confidencePct: 90,
        stageTimestamps: {
          gateIn: "10:42 AM",
        },
      },
      {
        id: "TRK-NBO-09",
        registration: "KCE 104N",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-NBO-7733",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Validation / Release",
        timeInStageMin: 12,
        baselineStageMin: 15,
        dwellDeltaMin: -3,
        predictedGateOut: "12:20 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Routing to Bay P07 upon release",
        flowGuardStatus: "OPTIMIZED",
        depotId: "nairobi",
        predictedTurnaroundMin: 59,
        baselineTurnaroundMin: 65,
        confidencePct: 92,
        stageTimestamps: {
          gateIn: "10:25 AM",
          validation: "10:38 AM",
        },
      },
      {
        id: "TRK-NBO-10",
        registration: "KDJ 517T",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-NBO-8855",
        product: "JET A-1 (Aviation Turbine)",
        quantityLitres: 42000,
        compartmentsCount: 4,
        currentStage: "Validation / Release",
        timeInStageMin: 16,
        baselineStageMin: 15,
        dwellDeltaMin: 1,
        predictedGateOut: "12:30 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Laboratory flash-point certificate matched",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 64,
        baselineTurnaroundMin: 65,
        confidencePct: 94,
        stageTimestamps: {
          gateIn: "10:20 AM",
          validation: "10:34 AM",
        },
      },
      {
        id: "TRK-NBO-11",
        registration: "KCF 992P",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-NBO-3319",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 6,
        baselineStageMin: 10,
        dwellDeltaMin: -4,
        predictedGateOut: "12:45 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Driver security credentials approved",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 58,
        baselineTurnaroundMin: 65,
        confidencePct: 90,
        stageTimestamps: {
          gateIn: "10:44 AM",
        },
      },
      {
        id: "TRK-NBO-12",
        registration: "KDK 341W",
        omc: "Hass Petroleum",
        orderNumber: "LO-NBO-6644",
        product: "DPK (Dual Purpose Kerosene)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 4,
        baselineStageMin: 10,
        dwellDeltaMin: -6,
        predictedGateOut: "12:50 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Queueing for scale entry",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 56,
        baselineTurnaroundMin: 65,
        confidencePct: 88,
        stageTimestamps: {
          gateIn: "10:46 AM",
        },
      },
      {
        id: "TRK-NBO-13",
        registration: "KCG 881L",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-NBO-9966",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P01",
        timeInStageMin: 12,
        baselineStageMin: 18,
        dwellDeltaMin: -6,
        predictedGateOut: "11:50 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Loading 62%)",
        nextAction: "Continuous flow monitoring",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 55,
        baselineTurnaroundMin: 65,
        confidencePct: 93,
        stageTimestamps: {
          gateIn: "10:05 AM",
          validation: "10:19 AM",
          loading: "10:38 AM",
        },
      },
      {
        id: "TRK-NBO-14",
        registration: "KDL 720S",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-NBO-5521",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P03",
        timeInStageMin: 14,
        baselineStageMin: 18,
        dwellDeltaMin: -4,
        predictedGateOut: "11:55 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Loading 74%)",
        nextAction: "Awaiting top compartment fill",
        flowGuardStatus: "NOMINAL",
        depotId: "nairobi",
        predictedTurnaroundMin: 57,
        baselineTurnaroundMin: 65,
        confidencePct: 91,
        stageTimestamps: {
          gateIn: "10:08 AM",
          validation: "10:22 AM",
          loading: "10:36 AM",
        },
      },
      {
        id: "TRK-NBO-15",
        registration: "KCH 455F",
        omc: "Galana Oil Kenya",
        orderNumber: "LO-NBO-4433",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 40000,
        compartmentsCount: 4,
        currentStage: "Gate-Out",
        timeInStageMin: 2,
        baselineStageMin: 5,
        dwellDeltaMin: -3,
        predictedGateOut: "11:05 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Security barrier open",
        flowGuardStatus: "COMPLETED",
        depotId: "nairobi",
        predictedTurnaroundMin: 52,
        baselineTurnaroundMin: 65,
        confidencePct: 98,
        stageTimestamps: {
          gateIn: "09:30 AM",
          validation: "09:44 AM",
          loading: "10:02 AM",
          readyToExit: "10:38 AM",
          gateOut: "10:50 AM",
        },
      },
      {
        id: "TRK-NBO-16",
        registration: "KDM 612Z",
        omc: "Petrocity Energy",
        orderNumber: "LO-NBO-8877",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:04 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Departing facility",
        flowGuardStatus: "COMPLETED",
        depotId: "nairobi",
        predictedTurnaroundMin: 50,
        baselineTurnaroundMin: 65,
        confidencePct: 99,
        stageTimestamps: {
          gateIn: "09:32 AM",
          validation: "09:46 AM",
          loading: "10:04 AM",
          readyToExit: "10:40 AM",
          gateOut: "10:51 AM",
        },
      },
    ],

    nakuru: [
      {
        id: "TRK-NKR-01",
        registration: "KDB 918Q",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-NKR-4412",
        product: "PMS (Super Unleaded)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P01",
        timeInStageMin: 24,
        baselineStageMin: 16,
        dwellDeltaMin: 8,
        predictedGateOut: "12:12 PM",
        riskStatus: "RED",
        riskLabel: "Critical Equipment Bottleneck (+8m)",
        nextAction: "Autonomous divert to Bay P01 active",
        flowGuardStatus: "AUTO-EXECUTED",
        depotId: "nakuru",
        expectedArrival: "10:40 AM",
        predictedTurnaroundMin: 92,
        baselineTurnaroundMin: 58,
        confidencePct: 91,
        whyAtRisk: {
          cause: "Loading position unavailable — metering performance degraded (-18% flow rate)",
          factors: [
            "Flow meter temperature sensor calibration drift on primary bay",
            "Cargo transit verification document delay",
          ],
        },
        actionDetail: {
          interventionId: "INT-8803",
          proposedAction: "Reroute tanker to auxiliary loading position and dispatch calibration technician.",
          actionStatus: "AUTO-EXECUTED",
          expectedImpactMin: 28,
          approvalState: "AUTO",
        },
        stageTimestamps: {
          gateIn: "10:35 AM",
          validation: "10:50 AM",
          loading: "11:05 AM",
        },
      },
      {
        id: "TRK-NKR-02",
        registration: "KCF 772M",
        omc: "Hass Petroleum",
        orderNumber: "LO-NKR-4419",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P04",
        timeInStageMin: 18,
        baselineStageMin: 16,
        dwellDeltaMin: 2,
        predictedGateOut: "12:18 PM",
        riskStatus: "AMBER",
        riskLabel: "Secondary Meter Thermal Latency",
        nextAction: "Maintain fill velocity via pump boost",
        flowGuardStatus: "OPTIMIZED",
        depotId: "nakuru",
        predictedTurnaroundMin: 72,
        baselineTurnaroundMin: 58,
        confidencePct: 86,
        stageTimestamps: {
          gateIn: "10:40 AM",
          validation: "10:56 AM",
          loading: "11:12 AM",
        },
      },
      {
        id: "TRK-NKR-03",
        registration: "KBY 309C",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-NKR-3310",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 20,
        baselineStageMin: 12,
        dwellDeltaMin: 8,
        predictedGateOut: "12:35 PM",
        riskStatus: "AMBER",
        riskLabel: "Bay P02 Offline Queue Delay",
        nextAction: "Queued for Bay P03 upon availability",
        flowGuardStatus: "OPTIMIZED",
        depotId: "nakuru",
        predictedTurnaroundMin: 76,
        baselineTurnaroundMin: 58,
        confidencePct: 85,
        stageTimestamps: {
          gateIn: "10:48 AM",
          validation: "11:00 AM",
        },
      },
      {
        id: "TRK-NKR-04",
        registration: "KDF 415H",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-NKR-5520",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Gate-In",
        timeInStageMin: 8,
        baselineStageMin: 10,
        dwellDeltaMin: -2,
        predictedGateOut: "12:45 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Tare weighbridge entry",
        flowGuardStatus: "NOMINAL",
        depotId: "nakuru",
        predictedTurnaroundMin: 59,
        baselineTurnaroundMin: 58,
        confidencePct: 90,
        stageTimestamps: {
          gateIn: "11:02 AM",
        },
      },
      {
        id: "TRK-NKR-05",
        registration: "KBZ 881E",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-NKR-2299",
        product: "PMS (Super Unleaded)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 7,
        baselineStageMin: 8,
        dwellDeltaMin: -1,
        predictedGateOut: "11:30 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Final gate pass scan",
        flowGuardStatus: "NOMINAL",
        depotId: "nakuru",
        predictedTurnaroundMin: 54,
        baselineTurnaroundMin: 58,
        confidencePct: 96,
        stageTimestamps: {
          gateIn: "10:15 AM",
          validation: "10:28 AM",
          loading: "10:44 AM",
          readyToExit: "11:15 AM",
        },
      },
      {
        id: "TRK-NKR-06",
        registration: "KDN 234G",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-NKR-7711",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 10,
        baselineStageMin: 12,
        dwellDeltaMin: -2,
        predictedGateOut: "12:40 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Release token issued",
        flowGuardStatus: "NOMINAL",
        depotId: "nakuru",
        predictedTurnaroundMin: 57,
        baselineTurnaroundMin: 58,
        confidencePct: 91,
        stageTimestamps: {
          gateIn: "10:55 AM",
          validation: "11:05 AM",
        },
      },
      {
        id: "TRK-NKR-07",
        registration: "KCA 118R",
        omc: "Galana Oil Kenya",
        orderNumber: "LO-NKR-8814",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 5,
        baselineStageMin: 10,
        dwellDeltaMin: -5,
        predictedGateOut: "12:55 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Tare scale queue",
        flowGuardStatus: "NOMINAL",
        depotId: "nakuru",
        predictedTurnaroundMin: 55,
        baselineTurnaroundMin: 58,
        confidencePct: 88,
        stageTimestamps: {
          gateIn: "11:05 AM",
        },
      },
      {
        id: "TRK-NKR-08",
        registration: "KDP 501J",
        omc: "Petrocity Energy",
        orderNumber: "LO-NKR-9932",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:15 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Exited terminal",
        flowGuardStatus: "COMPLETED",
        depotId: "nakuru",
        predictedTurnaroundMin: 52,
        baselineTurnaroundMin: 58,
        confidencePct: 99,
        stageTimestamps: {
          gateIn: "10:10 AM",
          validation: "10:22 AM",
          loading: "10:38 AM",
          readyToExit: "11:05 AM",
          gateOut: "11:12 AM",
        },
      },
    ],

    eldoret: [
      {
        id: "TRK-ELD-01",
        registration: "KCP 320P",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-ELD-3310",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 23,
        baselineStageMin: 10,
        dwellDeltaMin: 13,
        predictedGateOut: "12:13 PM",
        riskStatus: "AMBER",
        riskLabel: "Gate Tare Scale Congestion (+13m)",
        nextAction: "Secondary scale lane activated",
        flowGuardStatus: "AUTO-SCHEDULED",
        depotId: "eldoret",
        expectedArrival: "10:55 AM",
        predictedTurnaroundMin: 78,
        baselineTurnaroundMin: 55,
        confidencePct: 86,
        whyAtRisk: {
          cause: "Gate ingress verification queue: 5 road tankers arrived simultaneously",
          factors: [
            "Batch arrival cluster at Eldoret main gate tare scale",
            "Driver electronic authorization terminal queue",
          ],
        },
        actionDetail: {
          interventionId: "INT-8804",
          proposedAction: "Activate secondary scale lane for pre-validated electronic manifests.",
          actionStatus: "AUTO-SCHEDULED",
          expectedImpactMin: 18,
          approvalState: "AUTO",
        },
        stageTimestamps: {
          gateIn: "10:45 AM",
        },
      },
      {
        id: "TRK-ELD-02",
        registration: "KCN 112L",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-ELD-4418",
        product: "PMS (Super Unleaded)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 20,
        baselineStageMin: 10,
        dwellDeltaMin: 10,
        predictedGateOut: "12:20 PM",
        riskStatus: "AMBER",
        riskLabel: "Gate Batch Delay",
        nextAction: "Directing to Scale Lane 2",
        flowGuardStatus: "OPTIMIZED",
        depotId: "eldoret",
        predictedTurnaroundMin: 72,
        baselineTurnaroundMin: 55,
        confidencePct: 87,
        stageTimestamps: {
          gateIn: "10:48 AM",
        },
      },
      {
        id: "TRK-ELD-03",
        registration: "KDQ 602A",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-ELD-5529",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 40000,
        compartmentsCount: 4,
        currentStage: "Gate-In",
        timeInStageMin: 18,
        baselineStageMin: 10,
        dwellDeltaMin: 8,
        predictedGateOut: "12:28 PM",
        riskStatus: "AMBER",
        riskLabel: "Ingress Inflow Surge",
        nextAction: "Electronic credential check",
        flowGuardStatus: "OPTIMIZED",
        depotId: "eldoret",
        predictedTurnaroundMin: 69,
        baselineTurnaroundMin: 55,
        confidencePct: 85,
        stageTimestamps: {
          gateIn: "10:50 AM",
        },
      },
      {
        id: "TRK-ELD-04",
        registration: "KCQ 489W",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-ELD-6633",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 11,
        baselineStageMin: 12,
        dwellDeltaMin: -1,
        predictedGateOut: "12:10 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Release token issued",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 54,
        baselineTurnaroundMin: 55,
        confidencePct: 92,
        stageTimestamps: {
          gateIn: "10:35 AM",
          validation: "10:48 AM",
        },
      },
      {
        id: "TRK-ELD-05",
        registration: "KDR 811B",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-ELD-7744",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P02",
        timeInStageMin: 15,
        baselineStageMin: 18,
        dwellDeltaMin: -3,
        predictedGateOut: "11:58 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Loading 70%)",
        nextAction: "Top-off loading",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 53,
        baselineTurnaroundMin: 55,
        confidencePct: 94,
        stageTimestamps: {
          gateIn: "10:20 AM",
          validation: "10:34 AM",
          loading: "10:50 AM",
        },
      },
      {
        id: "TRK-ELD-06",
        registration: "KCR 505S",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-ELD-8855",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Loading",
        assignedPosition: "P03",
        timeInStageMin: 12,
        baselineStageMin: 18,
        dwellDeltaMin: -6,
        predictedGateOut: "12:02 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track (Loading 55%)",
        nextAction: "Dual-arm filling",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 52,
        baselineTurnaroundMin: 55,
        confidencePct: 95,
        stageTimestamps: {
          gateIn: "10:25 AM",
          validation: "10:38 AM",
          loading: "10:54 AM",
        },
      },
      {
        id: "TRK-ELD-07",
        registration: "KDS 920C",
        omc: "Petrocity Energy",
        orderNumber: "LO-ELD-9966",
        product: "DPK (Dual Purpose Kerosene)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P05",
        timeInStageMin: 19,
        baselineStageMin: 18,
        dwellDeltaMin: 1,
        predictedGateOut: "11:55 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Disconnection checklist",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 56,
        baselineTurnaroundMin: 55,
        confidencePct: 91,
        stageTimestamps: {
          gateIn: "10:15 AM",
          validation: "10:29 AM",
          loading: "10:46 AM",
        },
      },
      {
        id: "TRK-ELD-08",
        registration: "KCS 618T",
        omc: "Hass Petroleum",
        orderNumber: "LO-ELD-1122",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 6,
        baselineStageMin: 8,
        dwellDeltaMin: -2,
        predictedGateOut: "11:30 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Final tare weighbridge outbound",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 51,
        baselineTurnaroundMin: 55,
        confidencePct: 97,
        stageTimestamps: {
          gateIn: "10:10 AM",
          validation: "10:24 AM",
          loading: "10:40 AM",
          readyToExit: "11:12 AM",
        },
      },
      {
        id: "TRK-ELD-09",
        registration: "KDT 303D",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-ELD-2233",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 4,
        baselineStageMin: 8,
        dwellDeltaMin: -4,
        predictedGateOut: "11:28 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Egress barrier pass ready",
        flowGuardStatus: "NOMINAL",
        depotId: "eldoret",
        predictedTurnaroundMin: 49,
        baselineTurnaroundMin: 55,
        confidencePct: 98,
        stageTimestamps: {
          gateIn: "10:12 AM",
          validation: "10:26 AM",
          loading: "10:42 AM",
          readyToExit: "11:15 AM",
        },
      },
      {
        id: "TRK-ELD-10",
        registration: "KCT 740V",
        omc: "Galana Oil Kenya",
        orderNumber: "LO-ELD-3344",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:14 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Exited facility",
        flowGuardStatus: "COMPLETED",
        depotId: "eldoret",
        predictedTurnaroundMin: 48,
        baselineTurnaroundMin: 55,
        confidencePct: 99,
        stageTimestamps: {
          gateIn: "10:05 AM",
          validation: "10:18 AM",
          loading: "10:35 AM",
          readyToExit: "11:06 AM",
          gateOut: "11:12 AM",
        },
      },
    ],

    mombasa: [
      {
        id: "TRK-MBS-01",
        registration: "KCA 889J",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-MBS-9001",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 40000,
        compartmentsCount: 4,
        currentStage: "Loading",
        assignedPosition: "P01",
        timeInStageMin: 14,
        baselineStageMin: 18,
        dwellDeltaMin: -4,
        predictedGateOut: "11:40 AM",
        riskStatus: "GREEN",
        riskLabel: "Nominal Velocity",
        nextAction: "Top-off meter verification",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 50,
        baselineTurnaroundMin: 50,
        confidencePct: 96,
        stageTimestamps: {
          gateIn: "10:15 AM",
          validation: "10:28 AM",
          loading: "10:44 AM",
        },
      },
      {
        id: "TRK-MBS-02",
        registration: "KDU 101E",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-MBS-9002",
        product: "PMS (Super Unleaded)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P02",
        timeInStageMin: 12,
        baselineStageMin: 18,
        dwellDeltaMin: -6,
        predictedGateOut: "11:42 AM",
        riskStatus: "GREEN",
        riskLabel: "Nominal Velocity",
        nextAction: "Loading 68% complete",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 49,
        baselineTurnaroundMin: 50,
        confidencePct: 97,
        stageTimestamps: {
          gateIn: "10:18 AM",
          validation: "10:30 AM",
          loading: "10:46 AM",
        },
      },
      {
        id: "TRK-MBS-03",
        registration: "KCV 202M",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-MBS-9003",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Loading",
        assignedPosition: "P03",
        timeInStageMin: 8,
        baselineStageMin: 18,
        dwellDeltaMin: -10,
        predictedGateOut: "11:55 AM",
        riskStatus: "GREEN",
        riskLabel: "Nominal Velocity",
        nextAction: "Loading in progress",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 51,
        baselineTurnaroundMin: 50,
        confidencePct: 95,
        stageTimestamps: {
          gateIn: "10:22 AM",
          validation: "10:35 AM",
          loading: "10:52 AM",
        },
      },
      {
        id: "TRK-MBS-04",
        registration: "KDV 404F",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-MBS-9004",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 8,
        baselineStageMin: 12,
        dwellDeltaMin: -4,
        predictedGateOut: "12:10 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Routing to Bay P04",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 48,
        baselineTurnaroundMin: 50,
        confidencePct: 96,
        stageTimestamps: {
          gateIn: "10:35 AM",
          validation: "10:48 AM",
        },
      },
      {
        id: "TRK-MBS-05",
        registration: "KCW 303N",
        omc: "Hass Petroleum",
        orderNumber: "LO-MBS-9005",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Validation / Release",
        timeInStageMin: 6,
        baselineStageMin: 12,
        dwellDeltaMin: -6,
        predictedGateOut: "12:15 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Electronic release sign-off",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 47,
        baselineTurnaroundMin: 50,
        confidencePct: 98,
        stageTimestamps: {
          gateIn: "10:38 AM",
          validation: "10:50 AM",
        },
      },
      {
        id: "TRK-MBS-06",
        registration: "KDW 505G",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-MBS-9006",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 6,
        baselineStageMin: 10,
        dwellDeltaMin: -4,
        predictedGateOut: "12:30 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Tare weighbridge entry",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 48,
        baselineTurnaroundMin: 50,
        confidencePct: 94,
        stageTimestamps: {
          gateIn: "10:48 AM",
        },
      },
      {
        id: "TRK-MBS-07",
        registration: "KCX 404P",
        omc: "Galana Oil Kenya",
        orderNumber: "LO-MBS-9007",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 40000,
        compartmentsCount: 4,
        currentStage: "Gate-In",
        timeInStageMin: 4,
        baselineStageMin: 10,
        dwellDeltaMin: -6,
        predictedGateOut: "12:35 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Driver credential scan",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 50,
        baselineTurnaroundMin: 50,
        confidencePct: 93,
        stageTimestamps: {
          gateIn: "10:52 AM",
        },
      },
      {
        id: "TRK-MBS-08",
        registration: "KDX 606H",
        omc: "Petrocity Energy",
        orderNumber: "LO-MBS-9008",
        product: "DPK (Dual Purpose Kerosene)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 2,
        baselineStageMin: 10,
        dwellDeltaMin: -8,
        predictedGateOut: "12:40 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Ingress barrier clear",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 49,
        baselineTurnaroundMin: 50,
        confidencePct: 95,
        stageTimestamps: {
          gateIn: "10:55 AM",
        },
      },
      {
        id: "TRK-MBS-09",
        registration: "KCY 505Q",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-MBS-9009",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 5,
        baselineStageMin: 8,
        dwellDeltaMin: -3,
        predictedGateOut: "11:20 AM",
        riskStatus: "GREEN",
        riskLabel: "Ready",
        nextAction: "Gross tare ticket verified",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 48,
        baselineTurnaroundMin: 50,
        confidencePct: 98,
        stageTimestamps: {
          gateIn: "10:05 AM",
          validation: "10:18 AM",
          loading: "10:35 AM",
          readyToExit: "11:08 AM",
        },
      },
      {
        id: "TRK-MBS-10",
        registration: "KDY 707J",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-MBS-9010",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Ready to Exit",
        timeInStageMin: 3,
        baselineStageMin: 8,
        dwellDeltaMin: -5,
        predictedGateOut: "11:18 AM",
        riskStatus: "GREEN",
        riskLabel: "Ready",
        nextAction: "Seal tags affixed",
        flowGuardStatus: "NOMINAL",
        depotId: "mombasa",
        predictedTurnaroundMin: 47,
        baselineTurnaroundMin: 50,
        confidencePct: 99,
        stageTimestamps: {
          gateIn: "10:08 AM",
          validation: "10:20 AM",
          loading: "10:38 AM",
          readyToExit: "11:10 AM",
        },
      },
      {
        id: "TRK-MBS-11",
        registration: "KCZ 606R",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-MBS-9011",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:10 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Gate pass cleared",
        flowGuardStatus: "COMPLETED",
        depotId: "mombasa",
        predictedTurnaroundMin: 46,
        baselineTurnaroundMin: 50,
        confidencePct: 100,
        stageTimestamps: {
          gateIn: "10:00 AM",
          validation: "10:12 AM",
          loading: "10:30 AM",
          readyToExit: "11:02 AM",
          gateOut: "11:09 AM",
        },
      },
      {
        id: "TRK-MBS-12",
        registration: "KDZ 808K",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-MBS-9012",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:08 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Exited to port corridor",
        flowGuardStatus: "COMPLETED",
        depotId: "mombasa",
        predictedTurnaroundMin: 45,
        baselineTurnaroundMin: 50,
        confidencePct: 100,
        stageTimestamps: {
          gateIn: "09:58 AM",
          validation: "10:10 AM",
          loading: "10:28 AM",
          readyToExit: "11:00 AM",
          gateOut: "11:07 AM",
        },
      },
    ],

    kisumu: [
      {
        id: "TRK-KSM-01",
        registration: "KEA 111A",
        omc: "Vivo Energy Kenya",
        orderNumber: "LO-KSM-101",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P01",
        timeInStageMin: 13,
        baselineStageMin: 16,
        dwellDeltaMin: -3,
        predictedGateOut: "11:38 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Top-up check",
        flowGuardStatus: "NOMINAL",
        depotId: "kisumu",
        predictedTurnaroundMin: 46,
        baselineTurnaroundMin: 45,
        confidencePct: 96,
        stageTimestamps: {
          gateIn: "10:20 AM",
          validation: "10:32 AM",
          loading: "10:48 AM",
        },
      },
      {
        id: "TRK-KSM-02",
        registration: "KDA 222B",
        omc: "TotalEnergies Marketing",
        orderNumber: "LO-KSM-102",
        product: "PMS (Super Unleaded)",
        quantityLitres: 34000,
        compartmentsCount: 3,
        currentStage: "Loading",
        assignedPosition: "P02",
        timeInStageMin: 10,
        baselineStageMin: 16,
        dwellDeltaMin: -6,
        predictedGateOut: "11:42 AM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Loading in progress",
        flowGuardStatus: "NOMINAL",
        depotId: "kisumu",
        predictedTurnaroundMin: 47,
        baselineTurnaroundMin: 45,
        confidencePct: 95,
        stageTimestamps: {
          gateIn: "10:25 AM",
          validation: "10:36 AM",
          loading: "10:52 AM",
        },
      },
      {
        id: "TRK-KSM-03",
        registration: "KEB 333C",
        omc: "Rubis Energy Kenya",
        orderNumber: "LO-KSM-103",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 38000,
        compartmentsCount: 4,
        currentStage: "Validation / Release",
        timeInStageMin: 8,
        baselineStageMin: 12,
        dwellDeltaMin: -4,
        predictedGateOut: "12:00 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Clear to Bay P03",
        flowGuardStatus: "NOMINAL",
        depotId: "kisumu",
        predictedTurnaroundMin: 48,
        baselineTurnaroundMin: 45,
        confidencePct: 94,
        stageTimestamps: {
          gateIn: "10:38 AM",
          validation: "10:48 AM",
        },
      },
      {
        id: "TRK-KSM-04",
        registration: "KDB 444D",
        omc: "Ola Energy Kenya",
        orderNumber: "LO-KSM-104",
        product: "PMS (Super Unleaded)",
        quantityLitres: 32000,
        compartmentsCount: 3,
        currentStage: "Gate-In",
        timeInStageMin: 5,
        baselineStageMin: 10,
        dwellDeltaMin: -5,
        predictedGateOut: "12:15 PM",
        riskStatus: "GREEN",
        riskLabel: "On Track",
        nextAction: "Tare scale entry",
        flowGuardStatus: "NOMINAL",
        depotId: "kisumu",
        predictedTurnaroundMin: 49,
        baselineTurnaroundMin: 45,
        confidencePct: 92,
        stageTimestamps: {
          gateIn: "10:50 AM",
        },
      },
      {
        id: "TRK-KSM-05",
        registration: "KEC 555E",
        omc: "Hass Petroleum",
        orderNumber: "LO-KSM-105",
        product: "AGO (Automotive Gas Oil)",
        quantityLitres: 36000,
        compartmentsCount: 3,
        currentStage: "Ready to Exit",
        timeInStageMin: 4,
        baselineStageMin: 8,
        dwellDeltaMin: -4,
        predictedGateOut: "11:22 AM",
        riskStatus: "GREEN",
        riskLabel: "Ready",
        nextAction: "Exit barrier clear",
        flowGuardStatus: "NOMINAL",
        depotId: "kisumu",
        predictedTurnaroundMin: 45,
        baselineTurnaroundMin: 45,
        confidencePct: 98,
        stageTimestamps: {
          gateIn: "10:12 AM",
          validation: "10:24 AM",
          loading: "10:40 AM",
          readyToExit: "11:10 AM",
        },
      },
      {
        id: "TRK-KSM-06",
        registration: "KDC 666F",
        omc: "Lake Oil Kenya",
        orderNumber: "LO-KSM-106",
        product: "PMS (Super Unleaded)",
        quantityLitres: 30000,
        compartmentsCount: 3,
        currentStage: "Gate-Out",
        timeInStageMin: 1,
        baselineStageMin: 5,
        dwellDeltaMin: -4,
        predictedGateOut: "11:12 AM",
        riskStatus: "NEUTRAL",
        riskLabel: "Completed",
        nextAction: "Departed facility",
        flowGuardStatus: "COMPLETED",
        depotId: "kisumu",
        predictedTurnaroundMin: 44,
        baselineTurnaroundMin: 45,
        confidencePct: 100,
        stageTimestamps: {
          gateIn: "10:08 AM",
          validation: "10:20 AM",
          loading: "10:36 AM",
          readyToExit: "11:05 AM",
          gateOut: "11:11 AM",
        },
      },
    ],
  };
}

export function initAllCapacityStates(): Record<DepotId, DepotCapacityState> {
  return {
    nairobi: {
      depotId: "nairobi",
      totalPhysicalPositions: 8,
      usableNow: 5,
      degraded: 1,
      offlineUnavailable: 2,
      reasons: {
        degradedReason: "Bay P04: Coriolis mass flow meter calibration drift -18%",
        unavailableReason: "Bay P05: Emergency valve servicing • Bay P08: Weights & Measures seal inspection",
      },
      effectiveProcessingCapacityLabel: "11 trucks / next 90 min",
      effectiveCapacityExplanation: "5 usable gantries + 86% loading performance rate + 48m average dwell",
      calculationModel: {
        usablePositions: 5,
        timeWindowMin: 90,
        avgLoadingDurationMin: 35,
        performanceRatePct: 86,
        effectiveThroughputTrucks: 11,
        formulaExplanation: "(90m window / 35m avg loading) × 5 usable bays × 86% loading performance = 11 orders",
      },
      positions: [
        {
          id: "NBO-P01",
          code: "P01",
          depotId: "nairobi",
          status: "AVAILABLE",
          productCompatibility: "PMS (Super Unleaded) / Dual-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Nominal calibration",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P02",
          code: "P02",
          depotId: "nairobi",
          status: "LOADING",
          activeTruckReg: "KDA 123X",
          activeOmc: "Rubis Energy Kenya",
          activeOrder: "LO-NBO-8821",
          productCompatibility: "PMS (Super Unleaded) / Dual-Arm",
          currentLoadingDurationMin: 27,
          estimatedFreeInMin: 11,
          telemetryNote: "Flow rate 1,580 L/min • Top compartment active",
          flowRateLpm: 1580,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P03",
          code: "P03",
          depotId: "nairobi",
          status: "AVAILABLE",
          productCompatibility: "AGO (Automotive Gas Oil) / High-Flow",
          telemetryNote: "Flow rate 1,640 L/min • Ready for intake",
          flowRateLpm: 1640,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P04",
          code: "P04",
          depotId: "nairobi",
          status: "DEGRADED",
          productCompatibility: "PMS (Super Unleaded) / Single-Arm",
          telemetryNote: "Flow rate 1,320 L/min (-18% drift) • Technician dispatched",
          flowRateLpm: 1320,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P05",
          code: "P05",
          depotId: "nairobi",
          status: "MAINTENANCE",
          productCompatibility: "DPK (Dual Purpose Kerosene) / Dual-Arm",
          telemetryNote: "Offline: Emergency pneumatic valve pack replacement (until 12:30 PM)",
          baselineFlowRateLpm: 1600,
        },
        {
          id: "NBO-P06",
          code: "P06",
          depotId: "nairobi",
          status: "LOADING",
          activeTruckReg: "KDD 441L",
          activeOmc: "TotalEnergies Marketing",
          activeOrder: "LO-NBO-9914",
          productCompatibility: "AGO (Automotive Gas Oil) / Dual-Arm",
          currentLoadingDurationMin: 21,
          estimatedFreeInMin: 17,
          telemetryNote: "Flow rate 1,600 L/min • High-volume arm active",
          flowRateLpm: 1600,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P07",
          code: "P07",
          depotId: "nairobi",
          status: "AVAILABLE",
          productCompatibility: "AGO (Automotive Gas Oil) / Dual-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Arm standby",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NBO-P08",
          code: "P08",
          depotId: "nairobi",
          status: "UNAVAILABLE",
          productCompatibility: "PMS (Super Unleaded) / Single-Arm",
          telemetryNote: "Offline: Annual Weights & Measures regulatory recalibration hold",
          baselineFlowRateLpm: 1650,
        },
      ],
    },

    nakuru: {
      depotId: "nakuru",
      totalPhysicalPositions: 4,
      usableNow: 3,
      degraded: 1,
      offlineUnavailable: 0,
      reasons: {
        degradedReason: "Bay P02: Flow meter temperature drift (-18% flow rate)",
      },
      effectiveProcessingCapacityLabel: "7 trucks / next 90 min",
      effectiveCapacityExplanation: "3 usable gantries + 82% loading performance rate",
      calculationModel: {
        usablePositions: 3,
        timeWindowMin: 90,
        avgLoadingDurationMin: 32,
        performanceRatePct: 82,
        effectiveThroughputTrucks: 7,
        formulaExplanation: "(90m window / 32m avg loading) × 3 usable bays × 82% loading performance = 7 orders",
      },
      positions: [
        {
          id: "NKR-P01",
          code: "P01",
          depotId: "nakuru",
          status: "LOADING",
          activeTruckReg: "KDB 918Q",
          activeOmc: "Lake Oil Kenya",
          activeOrder: "LO-NKR-4412",
          productCompatibility: "PMS / Dual-Arm",
          currentLoadingDurationMin: 24,
          estimatedFreeInMin: 14,
          telemetryNote: "Rerouted tanker loading nominal (1,590 L/min)",
          flowRateLpm: 1590,
          baselineFlowRateLpm: 1600,
        },
        {
          id: "NKR-P02",
          code: "P02",
          depotId: "nakuru",
          status: "DEGRADED",
          productCompatibility: "PMS / Dual-Arm",
          telemetryNote: "Flow rate 1,210 L/min (-18.2% drift) • Diverting heavy tankers",
          flowRateLpm: 1210,
          baselineFlowRateLpm: 1600,
        },
        {
          id: "NKR-P03",
          code: "P03",
          depotId: "nakuru",
          status: "AVAILABLE",
          productCompatibility: "AGO / High-Flow",
          telemetryNote: "Flow rate 1,650 L/min • Nominal calibration",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "NKR-P04",
          code: "P04",
          depotId: "nakuru",
          status: "LOADING",
          activeTruckReg: "KCF 772M",
          activeOmc: "Hass Petroleum",
          activeOrder: "LO-NKR-4419",
          productCompatibility: "AGO / Dual-Arm",
          currentLoadingDurationMin: 18,
          estimatedFreeInMin: 20,
          telemetryNote: "Flow rate 1,580 L/min • In progress",
          flowRateLpm: 1580,
          baselineFlowRateLpm: 1650,
        },
      ],
    },

    eldoret: {
      depotId: "eldoret",
      totalPhysicalPositions: 6,
      usableNow: 5,
      degraded: 0,
      offlineUnavailable: 1,
      reasons: {
        unavailableReason: "Bay P06: Scale interface cabling maintenance",
      },
      effectiveProcessingCapacityLabel: "11 trucks / next 90 min",
      effectiveCapacityExplanation: "5 usable gantries + 94% loading performance rate",
      calculationModel: {
        usablePositions: 5,
        timeWindowMin: 90,
        avgLoadingDurationMin: 38,
        performanceRatePct: 94,
        effectiveThroughputTrucks: 11,
        formulaExplanation: "(90m window / 38m avg loading) × 5 usable bays × 94% loading performance = 11 orders",
      },
      positions: [
        {
          id: "ELD-P01",
          code: "P01",
          depotId: "eldoret",
          status: "AVAILABLE",
          productCompatibility: "PMS / Dual-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Ready",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "ELD-P02",
          code: "P02",
          depotId: "eldoret",
          status: "LOADING",
          activeTruckReg: "KDR 811B",
          activeOmc: "Ola Energy Kenya",
          activeOrder: "LO-ELD-7744",
          productCompatibility: "PMS / Dual-Arm",
          currentLoadingDurationMin: 15,
          estimatedFreeInMin: 23,
          telemetryNote: "Flow rate 1,620 L/min • Nominal",
          flowRateLpm: 1620,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "ELD-P03",
          code: "P03",
          depotId: "eldoret",
          status: "LOADING",
          activeTruckReg: "KCR 505S",
          activeOmc: "Vivo Energy Kenya",
          activeOrder: "LO-ELD-8855",
          productCompatibility: "AGO / High-Flow",
          currentLoadingDurationMin: 12,
          estimatedFreeInMin: 26,
          telemetryNote: "Flow rate 1,640 L/min • Nominal",
          flowRateLpm: 1640,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "ELD-P04",
          code: "P04",
          depotId: "eldoret",
          status: "AVAILABLE",
          productCompatibility: "AGO / Dual-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Standby",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "ELD-P05",
          code: "P05",
          depotId: "eldoret",
          status: "LOADING",
          activeTruckReg: "KDS 920C",
          activeOmc: "Petrocity Energy",
          activeOrder: "LO-ELD-9966",
          productCompatibility: "DPK / Dual-Arm",
          currentLoadingDurationMin: 19,
          estimatedFreeInMin: 19,
          telemetryNote: "Flow rate 1,590 L/min • Nominal",
          flowRateLpm: 1590,
          baselineFlowRateLpm: 1600,
        },
        {
          id: "ELD-P06",
          code: "P06",
          depotId: "eldoret",
          status: "UNAVAILABLE",
          productCompatibility: "AGO / Dual-Arm",
          telemetryNote: "Offline: Tare scale interface telemetry communication card service",
          baselineFlowRateLpm: 1650,
        },
      ],
    },

    mombasa: {
      depotId: "mombasa",
      totalPhysicalPositions: 6,
      usableNow: 6,
      degraded: 0,
      offlineUnavailable: 0,
      reasons: {},
      effectiveProcessingCapacityLabel: "12 trucks / next 90 min",
      effectiveCapacityExplanation: "6 usable gantries + 99% loading performance rate • Optimal marine line balance",
      calculationModel: {
        usablePositions: 6,
        timeWindowMin: 90,
        avgLoadingDurationMin: 44,
        performanceRatePct: 99,
        effectiveThroughputTrucks: 12,
        formulaExplanation: "(90m window / 44m avg loading) × 6 usable bays × 99% loading performance = 12 orders",
      },
      positions: [
        {
          id: "MBS-P01",
          code: "P01",
          depotId: "mombasa",
          status: "LOADING",
          activeTruckReg: "KCA 889J",
          activeOmc: "Vivo Energy Kenya",
          activeOrder: "LO-MBS-9001",
          productCompatibility: "AGO / High-Flow",
          currentLoadingDurationMin: 14,
          estimatedFreeInMin: 24,
          telemetryNote: "Flow rate 1,650 L/min • Optimal",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "MBS-P02",
          code: "P02",
          depotId: "mombasa",
          status: "LOADING",
          activeTruckReg: "KDU 101E",
          activeOmc: "TotalEnergies Marketing",
          activeOrder: "LO-MBS-9002",
          productCompatibility: "PMS / Dual-Arm",
          currentLoadingDurationMin: 12,
          estimatedFreeInMin: 26,
          telemetryNote: "Flow rate 1,650 L/min • Optimal",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "MBS-P03",
          code: "P03",
          depotId: "mombasa",
          status: "LOADING",
          activeTruckReg: "KCV 202M",
          activeOmc: "Rubis Energy Kenya",
          activeOrder: "LO-MBS-9003",
          productCompatibility: "AGO / Dual-Arm",
          currentLoadingDurationMin: 8,
          estimatedFreeInMin: 30,
          telemetryNote: "Flow rate 1,640 L/min • Optimal",
          flowRateLpm: 1640,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "MBS-P04",
          code: "P04",
          depotId: "mombasa",
          status: "AVAILABLE",
          productCompatibility: "PMS / Dual-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Ready",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "MBS-P05",
          code: "P05",
          depotId: "mombasa",
          status: "AVAILABLE",
          productCompatibility: "AGO / High-Flow",
          telemetryNote: "Flow rate 1,650 L/min • Ready",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "MBS-P06",
          code: "P06",
          depotId: "mombasa",
          status: "AVAILABLE",
          productCompatibility: "DPK / High-Flow",
          telemetryNote: "Flow rate 1,600 L/min • Ready",
          flowRateLpm: 1600,
          baselineFlowRateLpm: 1600,
        },
      ],
    },

    kisumu: {
      depotId: "kisumu",
      totalPhysicalPositions: 4,
      usableNow: 4,
      degraded: 0,
      offlineUnavailable: 0,
      reasons: {},
      effectiveProcessingCapacityLabel: "8 trucks / next 90 min",
      effectiveCapacityExplanation: "4 usable gantries + 100% loading performance rate • Steady regional dispatch",
      calculationModel: {
        usablePositions: 4,
        timeWindowMin: 90,
        avgLoadingDurationMin: 45,
        performanceRatePct: 100,
        effectiveThroughputTrucks: 8,
        formulaExplanation: "(90m window / 45m avg loading) × 4 usable bays × 100% loading performance = 8 orders",
      },
      positions: [
        {
          id: "KSM-P01",
          code: "P01",
          depotId: "kisumu",
          status: "LOADING",
          activeTruckReg: "KEA 111A",
          activeOmc: "Vivo Energy Kenya",
          activeOrder: "LO-KSM-101",
          productCompatibility: "AGO / Dual-Arm",
          currentLoadingDurationMin: 13,
          estimatedFreeInMin: 25,
          telemetryNote: "Flow rate 1,650 L/min • Nominal",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "KSM-P02",
          code: "P02",
          depotId: "kisumu",
          status: "LOADING",
          activeTruckReg: "KDA 222B",
          activeOmc: "TotalEnergies Marketing",
          activeOrder: "LO-KSM-102",
          productCompatibility: "PMS / Dual-Arm",
          currentLoadingDurationMin: 10,
          estimatedFreeInMin: 28,
          telemetryNote: "Flow rate 1,650 L/min • Nominal",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "KSM-P03",
          code: "P03",
          depotId: "kisumu",
          status: "AVAILABLE",
          productCompatibility: "AGO / High-Flow",
          telemetryNote: "Flow rate 1,640 L/min • Standby",
          flowRateLpm: 1640,
          baselineFlowRateLpm: 1650,
        },
        {
          id: "KSM-P04",
          code: "P04",
          depotId: "kisumu",
          status: "AVAILABLE",
          productCompatibility: "PMS / Single-Arm",
          telemetryNote: "Flow rate 1,650 L/min • Standby",
          flowRateLpm: 1650,
          baselineFlowRateLpm: 1650,
        },
      ],
    },
  };
}

export function initAllEquipmentStates(): Record<DepotId, DepotEquipmentState> {
  return {
    nairobi: {
      depotId: "nairobi",
      loadingSystem: {
        name: "Gantry Hydraulic Loading Arms",
        status: "NORMAL",
        detail: "8 loading arm position controllers online. Overfill prevention circuits active.",
        lastChecked: "10:06 AM",
      },
      metering: {
        name: "Coriolis Mass Flow Meters",
        status: "DEGRADED",
        detail: "Bay P04 meter drift (-18% flow rate). Bay P08 pending regulatory inspection.",
        lastChecked: "10:04 AM",
      },
      gateSystem: {
        name: "Smart Gates & Tare Weighbridges",
        status: "NORMAL",
        detail: "Dual tare weighbridges connected to SAP and KRA ECTS.",
        lastChecked: "10:07 AM",
      },
      scada: {
        name: "Central SCADA DCS Gateway",
        status: "HEALTHY",
        detail: "Redundant PLC link latency 12ms.",
        lastChecked: "10:07 AM",
      },
      productReadiness: {
        name: "Tank Farm Product Release",
        status: "READY",
        detail: "Tank T-101 (PMS 4.2M L) & Tank T-104 (AGO 5.8M L) certified for commercial loading.",
        lastChecked: "09:50 AM",
      },
      loadingPerformanceRatePct: 86,
      loadingPerformanceDeltaLabel: "14% slower than expected baseline",
      averageFlowRateLpm: 1420,
      baselineFlowRateLpm: 1650,
    },

    nakuru: {
      depotId: "nakuru",
      loadingSystem: {
        name: "Hydraulic Gantry Manifold",
        status: "NORMAL",
        detail: "4 arm assemblies operating within pressure envelope.",
        lastChecked: "10:05 AM",
      },
      metering: {
        name: "Digital Flow Metering Line",
        status: "DEGRADED",
        detail: "Bay P02 thermal calibration offset detected (-18.2% flow variance).",
        lastChecked: "10:02 AM",
      },
      gateSystem: {
        name: "Ingress Weighbridge & Smart Barrier",
        status: "NORMAL",
        detail: "Smart Gate tare reader nominal.",
        lastChecked: "10:06 AM",
      },
      scada: {
        name: "Schneider RTU Interface",
        status: "HEALTHY",
        detail: "DCS loop heartbeat nominal.",
        lastChecked: "10:06 AM",
      },
      productReadiness: {
        name: "Rift Valley Tank Manifold",
        status: "READY",
        detail: "Product release certificates active for PMS and AGO.",
        lastChecked: "09:40 AM",
      },
      loadingPerformanceRatePct: 82,
      loadingPerformanceDeltaLabel: "18% slower than expected baseline",
      averageFlowRateLpm: 1350,
      baselineFlowRateLpm: 1650,
    },

    eldoret: {
      depotId: "eldoret",
      loadingSystem: {
        name: "North Rift Loading Gantry",
        status: "NORMAL",
        detail: "6 gantry arms ready; 5 active.",
        lastChecked: "10:05 AM",
      },
      metering: {
        name: "Mass Meter Skid",
        status: "NORMAL",
        detail: "Coriolis metering within +/-0.1% accuracy threshold.",
        lastChecked: "10:00 AM",
      },
      gateSystem: {
        name: "Eldoret Highway Gate Tare Scales",
        status: "QUEUED",
        detail: "5 transit road tankers arrived within 10 min window. Secondary scale lane active.",
        lastChecked: "10:07 AM",
      },
      scada: {
        name: "Depot DCS Telemetry",
        status: "HEALTHY",
        detail: "RTU link nominal.",
        lastChecked: "10:06 AM",
      },
      productReadiness: {
        name: "Eldoret Storage Tanks",
        status: "READY",
        detail: "Western corridor export tanks released for loading.",
        lastChecked: "09:45 AM",
      },
      loadingPerformanceRatePct: 94,
      loadingPerformanceDeltaLabel: "6% within nominal envelope",
      averageFlowRateLpm: 1550,
      baselineFlowRateLpm: 1650,
    },

    mombasa: {
      depotId: "mombasa",
      loadingSystem: {
        name: "KOT Terminal Loading Gantries",
        status: "NORMAL",
        detail: "All 6 high-velocity positions nominal.",
        lastChecked: "10:06 AM",
      },
      metering: {
        name: "Marine Terminal Mass Meters",
        status: "NORMAL",
        detail: "Calibrated to international marine standards.",
        lastChecked: "10:05 AM",
      },
      gateSystem: {
        name: "Port Corridor Smart Gates",
        status: "NORMAL",
        detail: "Dual high-speed RFID scale lanes nominal.",
        lastChecked: "10:07 AM",
      },
      scada: {
        name: "Honeywell DCS Supervisory Node",
        status: "HEALTHY",
        detail: "100% telemetry link availability.",
        lastChecked: "10:07 AM",
      },
      productReadiness: {
        name: "Kipevu Oil Terminal Tanks",
        status: "READY",
        detail: "Unconstrained marine offloading supply.",
        lastChecked: "09:30 AM",
      },
      loadingPerformanceRatePct: 99,
      loadingPerformanceDeltaLabel: "1% within optimal baseline",
      averageFlowRateLpm: 1640,
      baselineFlowRateLpm: 1650,
    },

    kisumu: {
      depotId: "kisumu",
      loadingSystem: {
        name: "Lake Basin Dispatch Gantries",
        status: "NORMAL",
        detail: "4 arms nominal.",
        lastChecked: "10:04 AM",
      },
      metering: {
        name: "Terminal Mass Flow Meters",
        status: "NORMAL",
        detail: "Calibrated and certified.",
        lastChecked: "10:03 AM",
      },
      gateSystem: {
        name: "Kisumu Main Terminal Gate",
        status: "NORMAL",
        detail: "Tare weighbridge clear and operating.",
        lastChecked: "10:06 AM",
      },
      scada: {
        name: "Process DCS Gateway",
        status: "HEALTHY",
        detail: "SCADA telemetry synced.",
        lastChecked: "10:06 AM",
      },
      productReadiness: {
        name: "Lake Regional Storage Tanks",
        status: "READY",
        detail: "Ready for regional OMC collection.",
        lastChecked: "09:35 AM",
      },
      loadingPerformanceRatePct: 100,
      loadingPerformanceDeltaLabel: "100% on baseline target",
      averageFlowRateLpm: 1650,
      baselineFlowRateLpm: 1650,
    },
  };
}

export function initAllBottlenecks(): Record<DepotId, DepotBottleneckDiagnosis> {
  return {
    nairobi: {
      depotId: "nairobi",
      currentBottleneck: "Loading capacity",
      headline: "Loading Capacity Deficit — Demand Outstrips Usable Gantries",
      explanation:
        "18 expected collection orders in next 90 min exceed estimated processing capacity (11 orders) across 5 usable bays. Meter calibration drift on secondary line (Bay P04) restricts throughput by an additional 14%.",
      primaryCause: "Expected collection demand rising faster than effective processing capacity.",
      currentImpact: "+18 min predicted turnaround elongation",
      forecastHorizon: "Next 45–60 min arrival clustering window",
      flowGuardResponse: "Action in progress (Dual-arm re-sequencing)",
      contributions: [
        {
          factor: "Demand Surge (+18 orders)",
          impactLevel: "High",
          scorePct: 88,
          statusText: "14 arrivals forecast in same 45m window",
        },
        {
          factor: "Gantry Availability (5/8 usable)",
          impactLevel: "High",
          scorePct: 84,
          statusText: "3 positions unavailable / offline",
        },
        {
          factor: "Loading Performance (86% rate)",
          impactLevel: "Medium",
          scorePct: 62,
          statusText: "14% slower fill velocity on secondary line",
        },
        {
          factor: "Gate Processing Velocity",
          impactLevel: "Low",
          scorePct: 25,
          statusText: "Smart Gates processing at baseline pace",
        },
      ],
    },

    nakuru: {
      depotId: "nakuru",
      currentBottleneck: "Equipment",
      headline: "Loading Equipment Degradation — Secondary Meter Drift",
      explanation:
        "Position P02 Coriolis flow meter experiencing 18% thermal calibration drift. Flow velocity suppressed to 1,210 L/min, producing compounding loading duration delays.",
      primaryCause: "Secondary gantry meter thermal calibration drift suppressing fill rate.",
      currentImpact: "+12 min average loading duration increase",
      forecastHorizon: "Next 60 min pending recalibration",
      flowGuardResponse: "Approval required for high-flow manifold re-routing",
      contributions: [
        {
          factor: "Equipment Telemetry Drift",
          impactLevel: "High",
          scorePct: 89,
          statusText: "Bay P02 thermal drift -18.2% flow rate",
        },
        {
          factor: "Loading Performance (82% rate)",
          impactLevel: "High",
          scorePct: 82,
          statusText: "Compounding fill time across PMS orders",
        },
        {
          factor: "Gantry Availability (3/4 usable)",
          impactLevel: "Medium",
          scorePct: 55,
          statusText: "Single bay divert required",
        },
        {
          factor: "Demand Inflow",
          impactLevel: "Low",
          scorePct: 30,
          statusText: "Demand volume (9 orders) within seasonal norm",
        },
      ],
    },

    eldoret: {
      depotId: "eldoret",
      currentBottleneck: "Gate processing",
      headline: "Gate Ingress Inflow Batch Surge — 5 Inbound Transit Tankers",
      explanation:
        "Cluster arrival of 5 long-haul road tankers within 10 min window created tare scale weighbridge congestion. Loading bays remain 83% usable with nominal flow performance.",
      primaryCause: "Batch arrivals of transit tankers creating tare scale congestion.",
      currentImpact: "+15 min gate-in dwell delay",
      forecastHorizon: "Next 30–45 min queue peak",
      flowGuardResponse: "Automated pre-clearance gate dispatch active",
      contributions: [
        {
          factor: "Tare Weighbridge Queue",
          impactLevel: "High",
          scorePct: 92,
          statusText: "5 road tankers arrived simultaneously",
        },
        {
          factor: "Transit Verification Latency",
          impactLevel: "Medium",
          scorePct: 68,
          statusText: "Driver document verification queue",
        },
        {
          factor: "Demand Volume (+14 orders)",
          impactLevel: "Medium",
          scorePct: 48,
          statusText: "Peak corridor transit window",
        },
        {
          factor: "Gantry Loading Capacity",
          impactLevel: "Low",
          scorePct: 15,
          statusText: "5/6 positions open with nominal flow",
        },
      ],
    },

    mombasa: {
      depotId: "mombasa",
      currentBottleneck: "Product/loading readiness",
      headline: "Terminal Operations Fully Nominal — Unconstrained Marine & Gantry Velocity",
      explanation:
        "All 6 loading positions fully operational with 99% loading performance rate. Marine pipeline intake and depot dispatch operating in perfect equilibrium.",
      primaryCause: "Nominal operational flow across coastal gantries.",
      currentImpact: "0 min SLA breach (All orders on target)",
      forecastHorizon: "Next 90 min stable",
      flowGuardResponse: "Continuous autonomous monitoring active",
      contributions: [
        {
          factor: "Gantry Capacity (6/6 usable)",
          impactLevel: "Nominal",
          scorePct: 5,
          statusText: "100% bay availability",
        },
        {
          factor: "Loading Performance (99% rate)",
          impactLevel: "Nominal",
          scorePct: 8,
          statusText: "Optimal flow velocity across all arms",
        },
        {
          factor: "Gate Processing Velocity",
          impactLevel: "Nominal",
          scorePct: 10,
          statusText: "Smart Gates operating below capacity",
        },
        {
          factor: "Demand Pressure",
          impactLevel: "Nominal",
          scorePct: 12,
          statusText: "8 orders forecast over next 90 min",
        },
      ],
    },

    kisumu: {
      depotId: "kisumu",
      currentBottleneck: "Validation/release",
      headline: "Lake Victoria Regional Dispatch Operating Within Standard Parameters",
      explanation:
        "Turnaround averaging 48 min against 45 min baseline. All 4 gantry positions operating at 100% performance without backlog.",
      primaryCause: "Nominal lake basin distribution operations.",
      currentImpact: "0 min SLA breach (Nominal turnaround)",
      forecastHorizon: "Next 90 min stable",
      flowGuardResponse: "Continuous autonomous monitoring active",
      contributions: [
        {
          factor: "Validation Velocity",
          impactLevel: "Nominal",
          scorePct: 10,
          statusText: "SLA compliance 98.4%",
        },
        {
          factor: "Gantry Capacity (4/4 usable)",
          impactLevel: "Nominal",
          scorePct: 5,
          statusText: "All bays nominal",
        },
        {
          factor: "Loading Performance",
          impactLevel: "Nominal",
          scorePct: 6,
          statusText: "100% baseline flow rate",
        },
        {
          factor: "Demand Pressure",
          impactLevel: "Nominal",
          scorePct: 11,
          statusText: "6 orders forecast over next 90 min",
        },
      ],
    },
  };
}

export function initAllDepotForecasts(): Record<DepotId, DepotForecast> {
  return {
    nairobi: {
      depotId: "nairobi",
      stabilizationNote:
        "FlowGuard re-sequenced 6 upcoming orders & adjusted internal processing priority to auxiliary position. Peak queue trajectory suppressed from 114 min to 55 min (-34m verified recovery).",
      points: [
        {
          offsetLabel: "NOW",
          expectedDemand: 7,
          effectiveCapacity: 6,
          projectedBacklog: 1,
          expectedWaitMin: 45,
          operationalState: "NORMAL",
          unmitigatedBacklog: 1,
          unmitigatedWaitMin: 45,
        },
        {
          offsetLabel: "+30m",
          expectedDemand: 14,
          effectiveCapacity: 8,
          projectedBacklog: 6,
          expectedWaitMin: 68,
          operationalState: "DEMAND SURGE",
          unmitigatedBacklog: 8,
          unmitigatedWaitMin: 78,
        },
        {
          offsetLabel: "+60m",
          expectedDemand: 18,
          effectiveCapacity: 8,
          projectedBacklog: 10,
          expectedWaitMin: 98,
          operationalState: "CAPACITY SHORTFALL",
          unmitigatedBacklog: 14,
          unmitigatedWaitMin: 114,
        },
        {
          offsetLabel: "+90m",
          expectedDemand: 10,
          effectiveCapacity: 12,
          projectedBacklog: 3,
          expectedWaitMin: 55,
          operationalState: "STABILIZING",
          unmitigatedBacklog: 16,
          unmitigatedWaitMin: 125,
        },
      ],
    },

    nakuru: {
      depotId: "nakuru",
      stabilizationNote:
        "FlowGuard autonomous bay divert rerouted KDB 918Q to auxiliary position and triggered technician ticket. Turnaround suppressed from 92m to 52m.",
      points: [
        {
          offsetLabel: "NOW",
          expectedDemand: 3,
          effectiveCapacity: 3,
          projectedBacklog: 0,
          expectedWaitMin: 40,
          operationalState: "NORMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 40,
        },
        {
          offsetLabel: "+30m",
          expectedDemand: 7,
          effectiveCapacity: 5,
          projectedBacklog: 2,
          expectedWaitMin: 56,
          operationalState: "DEMAND SURGE",
          unmitigatedBacklog: 3,
          unmitigatedWaitMin: 64,
        },
        {
          offsetLabel: "+60m",
          expectedDemand: 9,
          effectiveCapacity: 5,
          projectedBacklog: 4,
          expectedWaitMin: 88,
          operationalState: "CAPACITY SHORTFALL",
          unmitigatedBacklog: 6,
          unmitigatedWaitMin: 92,
        },
        {
          offsetLabel: "+90m",
          expectedDemand: 6,
          effectiveCapacity: 7,
          projectedBacklog: 1,
          expectedWaitMin: 52,
          operationalState: "STABILIZING",
          unmitigatedBacklog: 7,
          unmitigatedWaitMin: 98,
        },
      ],
    },

    eldoret: {
      depotId: "eldoret",
      stabilizationNote:
        "Automated gate load-balancer opened secondary scale lane for pre-validated electronic manifests. Gate dwell suppressed by 19 minutes.",
      points: [
        {
          offsetLabel: "NOW",
          expectedDemand: 4,
          effectiveCapacity: 4,
          projectedBacklog: 0,
          expectedWaitMin: 38,
          operationalState: "NORMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 38,
        },
        {
          offsetLabel: "+30m",
          expectedDemand: 11,
          effectiveCapacity: 7,
          projectedBacklog: 4,
          expectedWaitMin: 62,
          operationalState: "DEMAND SURGE",
          unmitigatedBacklog: 5,
          unmitigatedWaitMin: 70,
        },
        {
          offsetLabel: "+60m",
          expectedDemand: 14,
          effectiveCapacity: 8,
          projectedBacklog: 6,
          expectedWaitMin: 74,
          operationalState: "CAPACITY SHORTFALL",
          unmitigatedBacklog: 8,
          unmitigatedWaitMin: 86,
        },
        {
          offsetLabel: "+90m",
          expectedDemand: 7,
          effectiveCapacity: 10,
          projectedBacklog: 0,
          expectedWaitMin: 46,
          operationalState: "STABILIZING",
          unmitigatedBacklog: 9,
          unmitigatedWaitMin: 92,
        },
      ],
    },

    mombasa: {
      depotId: "mombasa",
      stabilizationNote: "Operations fully stabilized within optimal parameters. No intervention required.",
      points: [
        {
          offsetLabel: "NOW",
          expectedDemand: 2,
          effectiveCapacity: 4,
          projectedBacklog: 0,
          expectedWaitMin: 32,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 32,
        },
        {
          offsetLabel: "+30m",
          expectedDemand: 5,
          effectiveCapacity: 6,
          projectedBacklog: 0,
          expectedWaitMin: 35,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 35,
        },
        {
          offsetLabel: "+60m",
          expectedDemand: 8,
          effectiveCapacity: 8,
          projectedBacklog: 0,
          expectedWaitMin: 48,
          operationalState: "NORMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 48,
        },
        {
          offsetLabel: "+90m",
          expectedDemand: 4,
          effectiveCapacity: 6,
          projectedBacklog: 0,
          expectedWaitMin: 36,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 36,
        },
      ],
    },

    kisumu: {
      depotId: "kisumu",
      stabilizationNote: "Regional dispatch velocity steady. No intervention required.",
      points: [
        {
          offsetLabel: "NOW",
          expectedDemand: 1,
          effectiveCapacity: 3,
          projectedBacklog: 0,
          expectedWaitMin: 30,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 30,
        },
        {
          offsetLabel: "+30m",
          expectedDemand: 4,
          effectiveCapacity: 4,
          projectedBacklog: 0,
          expectedWaitMin: 36,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 36,
        },
        {
          offsetLabel: "+60m",
          expectedDemand: 6,
          effectiveCapacity: 5,
          projectedBacklog: 1,
          expectedWaitMin: 48,
          operationalState: "NORMAL",
          unmitigatedBacklog: 1,
          unmitigatedWaitMin: 48,
        },
        {
          offsetLabel: "+90m",
          expectedDemand: 3,
          effectiveCapacity: 4,
          projectedBacklog: 0,
          expectedWaitMin: 35,
          operationalState: "OPTIMAL",
          unmitigatedBacklog: 0,
          unmitigatedWaitMin: 35,
        },
      ],
    },
  };
}
