/**
 * KPC FlowGuard — Synthetic Autonomy Control Data (Refined Credibility Pass)
 * 
 * Conforms strictly to FLOWGUARD_PROJECT_CONTEXT.md:
 * - Evidence-grounded operational integration categories (ERP, Gate, Mass-Flow, SCADA, Tank Gauging)
 * - Generic integration terminology (Operational Actuation Interface, Field telemetry payload, Operational event payload)
 * - Prototype Policy Framework (L1 — ADVISORY, L2 — AUTO-EXECUTABLE, L3 — HUMAN APPROVAL)
 * - Cryptographically integrity-checked audit records (tamper-evident SHA-256 digests)
 * - Recovery Attainment metric (89.5%) rather than generic "accuracy"
 * - Scenario 5 updated to "NO SAFE AUTONOMOUS INTERVENTION" (Bounded Autonomy / Escalation)
 */

import {
  AutonomyIncident,
  AutonomyPolicyRule,
  TelemetryDataSource,
  AutonomyAggregateMetrics,
  AutonomySubsystemHealth,
} from "@/types/flowguard";

export function initAllAutonomyIncidents(): AutonomyIncident[] {
  return [
    {
      id: "INT-8801",
      timestamp: "10:02:47",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      headline: "Dual-Arm Fast-Track & Re-sequencing for Peak Demand Relief",
      status: "VERIFIED",
      autonomyLevel: "L2",
      predictedProblem: "Turnaround predicted to cross 114m (+49m above baseline), creating 7-tanker gantry queue and KES 1.85M demurrage exposure",
      telemetryTrigger: "Expected Demand surge (18 orders next 90 min) vs 11 estimated processing capacity across 5 usable bays + gantry metering drag (86% speed)",
      causalFactors: [
        { factor: "Usable loading positions deficit (5/8 operational)", impactScore: 42, category: "capacity" },
        { factor: "Concentrated arrival cluster in 10:00–11:00 window (18 orders)", impactScore: 38, category: "demand" },
        { factor: "Gantry flow rate drag (1,420 L/min vs 1,650 L/min baseline)", impactScore: 20, category: "equipment" },
      ],
      selectedCandidateId: "OPT-03",
      appliedPolicy: {
        id: "POL-042",
        code: "POL-042",
        name: "High-Demand Dual-Arm Fast-Track Authorization",
        category: "Capacity",
        autonomyLevel: "L2 — AUTO-EXECUTABLE",
        condition: "Predicted queue dwell delta > 25m AND compatible multi-compartment road tanker AND zero hazardous cargo conflict",
        actionAuthorized: "Autonomous gantry arm dual-coupling and internal yard re-sequencing without supervisor pre-approval",
        safetyInvariant: "Configured safety boundary: Dual-coupling permitted only for compatible PMS/AGO compartments with certified vapor recovery lines",
        status: "ACTIVE",
        lastEvaluated: "10:02:44",
        evaluationPass: true,
      },
      candidates: [
        {
          id: "OPT-01",
          rank: 4,
          name: "Do Nothing / Maintain FIFO Queue",
          actionType: "Baseline Inaction",
          predictedTurnaroundMin: 114,
          exposureKes: 1850000,
          disruptionScore: "None",
          feasibility: "Rejected",
          objectiveScore: 22,
          selectionRationale: "Improvement insufficient: leaves unmitigated +49m queue blowout and KES 1.85M demurrage exposure",
          queueReductionExpectedMin: 0,
          ordersAffected: 0,
        },
        {
          id: "OPT-02",
          rank: 2,
          name: "Arrival Staggering & Gate Holding Only",
          actionType: "External Throttling",
          predictedTurnaroundMin: 76,
          exposureKes: 820000,
          disruptionScore: "Low",
          feasibility: "Feasible",
          objectiveScore: 68,
          selectionRationale: "Excessive operational disruption: reduces internal queue but transfers dwell to roadside staging area",
          queueReductionExpectedMin: 22,
          ordersAffected: 4,
        },
        {
          id: "OPT-03",
          rank: 1,
          name: "Re-sequence + Dual-Arm Fast-Track (Bays P01 & P03)",
          actionType: "Autonomous Control Actuation",
          predictedTurnaroundMin: 65,
          exposureKes: 410000,
          disruptionScore: "Moderate",
          feasibility: "Selected",
          objectiveScore: 94,
          selectionRationale: "Best projected turnaround improvement (-38m expected) while remaining within configured autonomy policy",
          queueReductionExpectedMin: 38,
          ordersAffected: 6,
        },
        {
          id: "OPT-04",
          rank: 3,
          name: "Cross-Depot Divert to Nakuru Terminal",
          actionType: "Inter-Terminal Reroute",
          predictedTurnaroundMin: 95,
          exposureKes: 2100000,
          disruptionScore: "Severe",
          feasibility: "Blocked by Policy",
          objectiveScore: 35,
          selectionRationale: "Exceeds autonomy policy threshold: inter-terminal transit haul costs (KES 2.1M) exceed demurrage risk ceiling",
          queueReductionExpectedMin: 18,
          ordersAffected: 8,
        },
      ],
      actuationDetails: {
        dispatchTarget: "Operational Actuation Interface (Terminal Control & Dispatch)",
        commandType: "GANTRY_SEQUENCE_UPDATE & DUAL_ARM_ENABLE",
        affectedOrders: ["LO-NBO-8821", "LO-NBO-8822", "LO-NBO-8824", "LO-NBO-8825", "LO-NBO-8829", "LO-NBO-8831"],
        dispatchedAt: "10:02:47.318",
        ackLatencyMs: 142,
        actuationStatus: "CONFIRMED",
        targetDevice: "Gantry Loading Control Gateway (Bays P01 & P03)",
      },
      verification: {
        targetReductionMin: 38,
        verifiedReductionMin: 34,
        varianceMin: 4,
        exposureProtectedKes: 1420000,
        realizedSavingsKes: 1210000,
        recoveryAttainmentPct: 89.5,
        accuracyPct: 89.5,
        status: "VERIFIED",
        measuredAt: "10:48:15",
        verificationMethod: "Gross departure weighbridge timestamps vs unmitigated baseline forecast trajectory",
      },
      auditHash: "sha256:7f49c0d381eb94532b2f6acae7e18933b8a1c93de46e9104fa28db7615024b81",
      operatorNotes: "Auto-executed within configured safety boundaries. Terminal shift supervisor acknowledged notification at 10:04:12.",
      timelineSteps: [
        {
          stage: "SIGNAL",
          label: "Telemetry Ingestion",
          subLabel: "Multi-Source Sensor Ingestion",
          status: "COMPLETED",
          timestamp: "10:02:30",
          summary: "Identified simultaneous arrival surge and gantry loading capacity deficit",
          metrics: [
            { label: "Expected Demand", value: "18 orders / 90m", isHighlight: true },
            { label: "Usable Bays", value: "5 of 8 operational" },
            { label: "Flow Velocity", value: "86% of baseline" },
          ],
          payloadEntries: [
            { key: "ERP Orders Ingested", value: "18 road tankers scheduled between 10:00 and 11:30", type: "text" },
            { key: "Gantry Position Status", value: "Bays P01-P05 Active; P06 Valve Servicing; P07 Recalibration; P08 Offline", type: "text" },
            { key: "Mass-Flow Velocity Reading", value: "1,420 L/min (Baseline rate: 1,650 L/min)", type: "code" },
          ],
          technicalDetail: "Prototype integration modeled on KPC operational control and dispatch systems. Field telemetry sampled at 250ms interval.",
        },
        {
          stage: "PREDICT",
          label: "Predictive Modeling",
          subLabel: "Model: FG-TURNAROUND-SYNTH-v1.4",
          status: "COMPLETED",
          timestamp: "10:02:36",
          summary: "Forecasted severe queue blowout (+49m above baseline SLA) with 88% probability",
          metrics: [
            { label: "Predicted Turnaround", value: "114 min (+49m)", isHighlight: true },
            { label: "Peak Gantry Queue", value: "13 tankers" },
            { label: "Model Confidence", value: "92.4%" },
          ],
          payloadEntries: [
            { key: "Unmitigated Gate-Out", value: "11:48 AM (SLA breach predicted for 6 orders)", type: "badge" },
            { key: "Demurrage Exposure", value: "KES 1,850,000 calculated across 6 OMC collection orders", type: "text" },
            { key: "Feature Importance Weights", value: "Usable Capacity: 0.42 | Arrival Density: 0.38 | Gantry Velocity: 0.20", type: "code" },
          ],
          technicalDetail: "Discrete-event simulation conditioned on historical Friday morning turnaround distributions and physical bay availability.",
        },
        {
          stage: "DIAGNOSE",
          label: "Causal Attribution",
          subLabel: "Root Cause Decomposition",
          status: "COMPLETED",
          timestamp: "10:02:40",
          summary: "Pinpointed structural bottleneck: Demand exceeds effective processing capacity by 7 tankers in the active window",
          metrics: [
            { label: "Capacity Deficit", value: "-7 tankers / 90m", isHighlight: true },
            { label: "Primary Cause", value: "Loading Capacity Deficit" },
            { label: "Secondary Cause", value: "Metering Velocity Drag" },
          ],
          payloadEntries: [
            { key: "Effective Capacity", value: "11 tankers / 90m (Formula: 5 bays × 2.6 fills/hr × 0.86 eff)", type: "code" },
            { key: "Demand Vector", value: "18 tankers registered (164% of depot processing capacity)", type: "text" },
          ],
          technicalDetail: "Causal attribution verified bottleneck origin at gantry loading positions P01–P05 rather than ingress gates.",
        },
        {
          stage: "OPTIMIZE",
          label: "Combinatorial Optimization",
          subLabel: "Candidate Action Ranking",
          status: "COMPLETED",
          timestamp: "10:02:43",
          summary: "Evaluated 4 candidate interventions; selected Option 3 for optimal turnaround recovery within policy boundaries",
          metrics: [
            { label: "Candidates Evaluated", value: "4 actions" },
            { label: "Optimal Option", value: "OPT-03 (Score 94/100)", isHighlight: true },
            { label: "Projected Recovery", value: "-38 min turnaround" },
          ],
          payloadEntries: [
            { key: "Prototype Objective Weighting", value: "min(Delay × 0.6 + Demurrage Cost × 0.3 + Yard Disruption × 0.1)", type: "code" },
            { key: "Selected Package", value: "Re-sequence 6 orders + Enable Dual-Arm Loading on Bays P01 & P03", type: "text" },
          ],
          technicalDetail: "Multi-objective combinatorial solver evaluated candidate options against operational disruption and dwell constraints in 84ms.",
        },
        {
          stage: "DECIDE",
          label: "Policy Governance Gate",
          subLabel: "FlowGuard Autonomy Rule Check",
          status: "COMPLETED",
          timestamp: "10:02:45",
          summary: "Passed FlowGuard rule POL-042 (L2 Auto-Executable); safety boundaries fully satisfied",
          metrics: [
            { label: "FlowGuard Rule", value: "POL-042 (Active)", isHighlight: true },
            { label: "Autonomy Level", value: "L2 — AUTO-EXECUTABLE" },
            { label: "Safety Status", value: "PASSED (Zero Conflict)" },
          ],
          payloadEntries: [
            { key: "Prototype Policy Check", value: "Dwell increase (+49m) > 25m threshold -> PASSED", type: "badge" },
            { key: "Hazardous Cargo Guard", value: "No Jet-A1 or LPG orders in candidate re-sequence batch -> PASSED", type: "badge" },
            { key: "Approval Requirement", value: "L2 Bounded Autonomous Execution authorized; notification dispatched", type: "text" },
          ],
          technicalDetail: "Evaluated against FlowGuard prototype policy rules and terminal safety envelopes.",
        },
        {
          stage: "EXECUTE",
          label: "Operational Actuation",
          subLabel: "Control Interface Dispatch",
          status: "COMPLETED",
          timestamp: "10:02:47",
          summary: "Dispatched operational actuation payload to terminal control interface and electronic yard board",
          metrics: [
            { label: "Dispatched At", value: "10:02:47.318", isHighlight: true },
            { label: "Ack Latency", value: "142 ms" },
            { label: "Orders Affected", value: "6 loading orders" },
          ],
          payloadEntries: [
            { key: "Target Interface", value: "Operational Actuation Interface (Terminal Control Gateway)", type: "code" },
            { key: "Field Telemetry Payload", value: "SET_BAY_DUAL_MODE(P01, TRUE); SET_BAY_DUAL_MODE(P03, TRUE);", type: "code" },
            { key: "Orders Re-sequenced", value: "LO-NBO-8821, LO-NBO-8822, LO-NBO-8824, LO-NBO-8825, LO-NBO-8829, LO-NBO-8831", type: "text" },
          ],
          technicalDetail: "Operational event payload delivered via transactional message queue with sub-second acknowledgement.",
        },
        {
          stage: "VERIFY",
          label: "Closed-Loop Verification",
          subLabel: "Field Telemetry Audit",
          status: "COMPLETED",
          timestamp: "10:48:15",
          summary: "Verified 34 min turnaround reduction across affected orders; KES 1.42M exposure protected",
          metrics: [
            { label: "Expected Recovery", value: "-38 min" },
            { label: "Verified Recovery", value: "-34 min", isHighlight: true },
            { label: "Recovery Attainment", value: "89.5% (Variance: 4m)" },
          ],
          payloadEntries: [
            { key: "Pre-Intervention Dwell", value: "114 min predicted (11:48 AM gate-out)", type: "text" },
            { key: "Post-Intervention Dwell", value: "68 min measured (11:02 AM gate-out)", type: "badge" },
            { key: "Exposure Protected", value: "KES 1,420,000 demurrage claims averted", type: "text" },
          ],
          technicalDetail: "Telemetry validation based on gross weighbridge departure timestamps vs simulated counterfactual baseline.",
        },
        {
          stage: "LOG",
          label: "Forensic Audit Record",
          subLabel: "Tamper-Evident Integrity Check",
          status: "COMPLETED",
          timestamp: "10:48:20",
          summary: "Recorded complete decision state and verification readings into cryptographically integrity-checked audit log",
          metrics: [
            { label: "Audit Hash", value: "sha256:7f49c0d...", isHighlight: true },
            { label: "Log Storage", value: "Append-Only Audit Store" },
            { label: "Sign-Off", value: "Engine v1.4 Validated" },
          ],
          payloadEntries: [
            { key: "Block Digest (SHA-256)", value: "7f49c0d381eb94532b2f6acae7e18933b8a1c93de46e9104fa28db7615024b81", type: "code" },
            { key: "Audit Policy", value: "Cryptographically integrity-checked append-only event log", type: "text" },
          ],
          technicalDetail: "Deterministic SHA-256 digest computed over sensory snapshot, prediction tensor, candidate rankings, policy evaluation, and verification measurements.",
        },
      ],
    },
    {
      id: "INT-8802",
      timestamp: "10:05:12",
      depotId: "nakuru",
      depotName: "Nakuru Terminal (PS25)",
      headline: "Bay P02 Meter Drift Divert & Heavy Tanker Re-Allocation",
      status: "APPROVAL REQUIRED",
      autonomyLevel: "L3",
      predictedProblem: "Bay P02 queue building up; predicted 82 min dwell for heavy 40,000L AGO road tankers, triggering demurrage activation at 10:50 AM",
      telemetryTrigger: "Gantry mass-flow meter on Bay P02 exhibiting continuous sensor drift (-18.2% flow rate, 1,320 L/min vs 1,650 L/min baseline)",
      causalFactors: [
        { factor: "Mass-flow metering calibration drift (-18.2%)", impactScore: 64, category: "equipment" },
        { factor: "Queue imbalance: 4 heavy 40,000L AGO tankers waiting for Bay P02", impactScore: 26, category: "capacity" },
        { factor: "Product viscosity temperature variance (+2.1°C)", impactScore: 10, category: "equipment" },
      ],
      selectedCandidateId: "OPT-22",
      appliedPolicy: {
        id: "POL-012",
        code: "POL-012",
        name: "Flow Meter Drift Divert & Shift Controller Sign-Off",
        category: "Equipment",
        autonomyLevel: "L3 — HUMAN APPROVAL",
        condition: "Loading position flow variance exceeds 15% AND heavy road tankers (>35,000L) queued",
        actionAuthorized: "Bay divert to auxiliary gantry position P03 and automated service work order dispatch",
        safetyInvariant: "Configured safety boundary: Physical bay re-allocation of queued petroleum vehicles requires designated shift supervisor electronic authorization",
        status: "EVALUATING",
        lastEvaluated: "10:05:10",
        evaluationPass: true,
      },
      candidates: [
        {
          id: "OPT-21",
          rank: 3,
          name: "Maintain Loading at Bay P02 at Degraded Speed",
          actionType: "Degraded Inaction",
          predictedTurnaroundMin: 82,
          exposureKes: 620000,
          disruptionScore: "None",
          feasibility: "Rejected",
          objectiveScore: 31,
          selectionRationale: "Improvement insufficient: severe dwell blowout (+34m) and risk of billing discrepancy with OMC",
          queueReductionExpectedMin: 0,
          ordersAffected: 0,
        },
        {
          id: "OPT-22",
          rank: 1,
          name: "Divert Heavy Tankers to Bay P03 & Trigger Recalibration Work Order",
          actionType: "Supervised Autonomous Divert",
          predictedTurnaroundMin: 46,
          exposureKes: 850000,
          disruptionScore: "Moderate",
          feasibility: "Selected",
          objectiveScore: 91,
          selectionRationale: "Best projected turnaround improvement (-26m dwell); requires human authorization under POL-012",
          queueReductionExpectedMin: 26,
          ordersAffected: 3,
        },
        {
          id: "OPT-23",
          rank: 2,
          name: "Emergency Complete Gantry Bay P02 Shutdown",
          actionType: "Uncontrolled Bay Lockout",
          predictedTurnaroundMin: 94,
          exposureKes: 1120000,
          disruptionScore: "High",
          feasibility: "Rejected",
          objectiveScore: 18,
          selectionRationale: "Excessive operational disruption: premature shutdown creates external queue spillover into depot access road",
          queueReductionExpectedMin: -12,
          ordersAffected: 5,
        },
      ],
      actuationDetails: {
        dispatchTarget: "Operational Actuation Interface (Nakuru Shift Controller Terminal)",
        commandType: "BAY_DIVERT_PROPOSAL_AWAITING_SUPERVISOR_SIG",
        affectedOrders: ["LO-NAK-9914", "LO-NAK-9917", "LO-NAK-9918"],
        dispatchedAt: "10:05:12.890",
        ackLatencyMs: 95,
        actuationStatus: "SUPERVISOR_PENDING",
        targetDevice: "Gantry Terminal Controller (Bays P02/P03)",
      },
      verification: {
        targetReductionMin: 26,
        exposureProtectedKes: 520000,
        realizedSavingsKes: 0,
        recoveryAttainmentPct: 0,
        status: "PENDING_VERIFICATION",
        verificationMethod: "Awaiting supervisor authorization signature to initiate actuation",
      },
      auditHash: "sha256:3e19a4b829cc01449daef152033bc67912803b901f4c6e9a039884dc401a8819",
      operatorNotes: "Supervisor authorization required per FlowGuard rule POL-012. Click 'AUTHORIZE ACTION' to execute bay divert.",
      timelineSteps: [
        {
          stage: "SIGNAL",
          label: "Telemetry Ingestion",
          subLabel: "Sensor Flow Rate Analysis",
          status: "COMPLETED",
          timestamp: "10:04:50",
          summary: "Detected 18.2% flow rate degradation on Nakuru Bay P02 mass-flow meter",
          metrics: [
            { label: "Flow Velocity", value: "1,320 L/min (-18.2%)", isHighlight: true },
            { label: "Sensor ID", value: "FT-NAK-202 (Mass-Flow)" },
            { label: "Affected Tankers", value: "3 heavy tankers" },
          ],
          payloadEntries: [
            { key: "Prototype Telemetry Payload", value: "FT-NAK-202 measured 1,320 L/min (Baseline: 1,650 L/min)", type: "code" },
            { key: "Thermal Drift Delta", value: "+2.1°C temperature compensation variance detected", type: "text" },
          ],
          technicalDetail: "Field telemetry signal indicating flow velocity reduction below baseline operating parameters.",
        },
        {
          stage: "PREDICT",
          label: "Predictive Modeling",
          subLabel: "Queue Projection Engine",
          status: "COMPLETED",
          timestamp: "10:04:58",
          summary: "Forecasted Bay P02 dwell blowout to 82 min (+34m above SLA threshold)",
          metrics: [
            { label: "Predicted Dwell", value: "82 min (+34m)", isHighlight: true },
            { label: "Demurrage Risk", value: "KES 520,000" },
            { label: "Confidence", value: "95.1%" },
          ],
          payloadEntries: [
            { key: "Order LO-NAK-9914", value: "TotalEnergies 40,000L AGO - Predicted SLA breach in 35m", type: "badge" },
            { key: "Queue Spillover", value: "Bay P02 backlog will block inner circulation lane by 10:45 AM", type: "text" },
          ],
          technicalDetail: "Bay-level discrete event simulation running with real-time viscosity and meter degradation curves.",
        },
        {
          stage: "DIAGNOSE",
          label: "Causal Attribution",
          subLabel: "Sensor Anomaly Verification",
          status: "COMPLETED",
          timestamp: "10:05:02",
          summary: "Hardware sensor calibration drift verified; mechanical pump output nominal",
          metrics: [
            { label: "Root Cause", value: "Meter Calibration Drift (64%)", isHighlight: true },
            { label: "Pump Head Pressure", value: "4.8 bar (Normal)" },
          ],
          payloadEntries: [
            { key: "Pump Telemetry", value: "Variable Speed Drive P-202 drawing normal current (38A)", type: "text" },
            { key: "Diagnosis Verdict", value: "Mass-flow sensor zero-drift; not a physical pipeline restriction", type: "badge" },
          ],
          technicalDetail: "Cross-correlated with manifold discharge pressure transducer PT-202.",
        },
        {
          stage: "OPTIMIZE",
          label: "Combinatorial Optimization",
          subLabel: "Bay Re-allocation Solver",
          status: "COMPLETED",
          timestamp: "10:05:06",
          summary: "Recommended diverting heavy tankers to Bay P03 and generating maintenance ticket",
          metrics: [
            { label: "Recommended Option", value: "OPT-22 (Score 91/100)", isHighlight: true },
            { label: "Predicted Recovery", value: "-26 min dwell" },
          ],
          payloadEntries: [
            { key: "Re-allocation Plan", value: "Route LO-NAK-9914 & LO-NAK-9917 to Bay P03; schedule P02 recalibration", type: "text" },
          ],
          technicalDetail: "Solver determined Bay P03 has compatible manifold arms and sufficient idle window between 10:15 and 11:30.",
        },
        {
          stage: "DECIDE",
          label: "Policy Governance Gate",
          subLabel: "L3 Approval Gate Enforced",
          status: "BLOCKED",
          timestamp: "10:05:10",
          summary: "FlowGuard rule POL-012 triggered: Bay re-allocation requires shift controller authorization",
          metrics: [
            { label: "FlowGuard Rule", value: "POL-012 (Enforced)", isHighlight: true },
            { label: "Autonomy Level", value: "L3 — HUMAN APPROVAL" },
            { label: "Gate State", value: "AWAITING SUPERVISOR TOKEN" },
          ],
          payloadEntries: [
            { key: "Configured Safety Boundary", value: "Loading bay diversions involving active road tankers require human supervisor sign-off", type: "badge" },
            { key: "Pending Token", value: "Awaiting electronic signature from Nakuru Shift Controller", type: "code" },
          ],
          technicalDetail: "Autonomous engine paused actuation pipeline and issued high-priority authorization request to dashboard.",
        },
        {
          stage: "EXECUTE",
          label: "Operational Actuation",
          subLabel: "Pending Authorization",
          status: "PENDING",
          timestamp: "10:05:12",
          summary: "Actuation payload staged. Ready for immediate dispatch upon supervisor approval",
          metrics: [
            { label: "Status", value: "STAGED / WAITING", isHighlight: true },
            { label: "Affected Orders", value: "3 tankers" },
          ],
          payloadEntries: [
            { key: "Prototype Actuation Payload", value: "DIVERT_BAY_ASSIGNMENT(LO-NAK-9914, P03); DISPATCH_MAINTENANCE_TICKET(P02);", type: "code" },
          ],
          technicalDetail: "Actuation payload pre-validated and held in transactional staging queue.",
        },
        {
          stage: "VERIFY",
          label: "Closed-Loop Verification",
          subLabel: "Verification Staged",
          status: "PENDING",
          timestamp: "10:05:12",
          summary: "Verification probes armed; telemetry baseline established awaiting actuation",
          metrics: [
            { label: "Target Recovery", value: "-26 min" },
            { label: "Verification State", value: "ARMED" },
          ],
          payloadEntries: [
            { key: "Expected Savings", value: "KES 520,000 demurrage exposure protected", type: "text" },
          ],
          technicalDetail: "Event listener registered for Bay P03 mass-flow start trigger.",
        },
        {
          stage: "LOG",
          label: "Forensic Audit Record",
          subLabel: "Authorization Request Logged",
          status: "IN_PROGRESS",
          timestamp: "10:05:12",
          summary: "Authorization request logged to tamper-evident audit trail",
          metrics: [
            { label: "Audit Hash", value: "sha256:3e19a4b...", isHighlight: true },
            { label: "Chain Status", value: "PENDING_BLOCK_SIG" },
          ],
          payloadEntries: [
            { key: "Event", value: "SUPERVISOR_APPROVAL_REQUEST_ISSUED", type: "badge" },
          ],
          technicalDetail: "Cryptographically integrity-checked audit record timestamped with microsecond precision.",
        },
      ],
    },
    {
      id: "INT-8804",
      timestamp: "09:42:18",
      depotId: "kisumu",
      depotName: "Kisumu Oil Jetty & Terminal (PS28)",
      headline: "Automated Manifold Product Flush Blocked by Safety Policy",
      status: "BLOCKED BY POLICY",
      autonomyLevel: "L3",
      predictedProblem: "Jet-A1 road tanker loading queue delayed by 45 min due to shared manifold line holding residual AGO product",
      telemetryTrigger: "Autonomous optimization engine proposed automatic line purge and manifold sequence changeover",
      causalFactors: [
        { factor: "Product transition constraint: Shared gantry manifold header", impactScore: 70, category: "equipment" },
        { factor: "High-priority Jet-A1 export order waiting at Tare Scale", impactScore: 30, category: "demand" },
      ],
      selectedCandidateId: "OPT-41",
      appliedPolicy: {
        id: "POL-088",
        code: "POL-088",
        name: "Aviation Fuel Cross-Contamination Safety Interlock",
        category: "Safety",
        autonomyLevel: "L3 — HUMAN APPROVAL",
        condition: "Manifold line transition involving Aviation Turbine Fuel (Jet-A1) or DPK",
        actionAuthorized: "STRICTLY PROHIBITED FROM AUTONOMOUS OVERRIDE. Requires physical certified quality lab chemist sign-off.",
        safetyInvariant: "Configured safety boundary: Zero tolerance for aviation fuel contamination. Quality sign-off cannot be automated under any operational circumstance.",
        status: "ACTIVE",
        lastEvaluated: "09:42:15",
        evaluationPass: false,
      },
      candidates: [
        {
          id: "OPT-41",
          rank: 1,
          name: "Autonomous Manifold High-Pressure Flush Sequence",
          actionType: "Automated Line Flush",
          predictedTurnaroundMin: 32,
          exposureKes: 220000,
          disruptionScore: "Moderate",
          feasibility: "Blocked by Policy",
          objectiveScore: 12,
          selectionRationale: "Blocked: violates safety policy POL-088; Jet-A1 line purge requires physical lab chemist certified sampling",
          queueReductionExpectedMin: 24,
          ordersAffected: 2,
        },
        {
          id: "OPT-42",
          rank: 2,
          name: "Hold Jet-A1 Tanker at Staging & Alert Quality Control Chemist",
          actionType: "Safe Policy Compliance Fallback",
          predictedTurnaroundMin: 55,
          exposureKes: 480000,
          disruptionScore: "Low",
          feasibility: "Selected",
          objectiveScore: 88,
          selectionRationale: "Best projected turnaround improvement while remaining within configured autonomy policy and safety boundaries",
          queueReductionExpectedMin: 0,
          ordersAffected: 1,
        },
      ],
      actuationDetails: {
        dispatchTarget: "Operational Actuation Interface (Kisumu Quality Lab & Safety Interlock)",
        commandType: "SAFETY_INTERLOCK_ENGAGED & CHEMIST_SAMPLE_DISPATCH",
        affectedOrders: ["LO-KIS-7712"],
        dispatchedAt: "09:42:18.102",
        ackLatencyMs: 65,
        actuationStatus: "BLOCKED",
        targetDevice: "Manifold Safety Interlock Valve XV-2801",
      },
      verification: {
        targetReductionMin: 0,
        exposureProtectedKes: 0,
        realizedSavingsKes: 0,
        recoveryAttainmentPct: 100,
        status: "VERIFIED",
        measuredAt: "09:42:20",
        verificationMethod: "Safety interlock confirmed engaged. Manifold valve XV-2801 physically locked in closed safe position.",
      },
      auditHash: "sha256:91c0e4450a8b910245df891cde4019a33827104ea019485bce904b7716301fa9",
      operatorNotes: "Autonomous engine correctly prevented unsafe actuation. Terminal Chief Chemist arrived at gantry at 09:48.",
      timelineSteps: [
        {
          stage: "SIGNAL",
          label: "Telemetry Ingestion",
          subLabel: "Product Transition Trigger",
          status: "COMPLETED",
          timestamp: "09:42:02",
          summary: "Identified Jet-A1 loading request on shared AGO manifold line",
          metrics: [
            { label: "Product Requested", value: "Jet-A1 (Aviation)", isHighlight: true },
            { label: "Current Line Fill", value: "AGO (Automotive Gasoil)" },
          ],
          payloadEntries: [
            { key: "Incoming Order", value: "LO-KIS-7712 (TotalEnergies / Kisumu Airport Supply)", type: "text" },
          ],
          technicalDetail: "Manifold line fill status verified against terminal product allocation database.",
        },
        {
          stage: "PREDICT",
          label: "Predictive Modeling",
          subLabel: "Delay Forecast",
          status: "COMPLETED",
          timestamp: "09:42:08",
          summary: "Forecasted 45 min delay if standard laboratory sampling procedure followed",
          metrics: [
            { label: "Predicted Delay", value: "+45 min", isHighlight: true },
            { label: "Demurrage Risk", value: "KES 480,000" },
          ],
          payloadEntries: [
            { key: "Predicted Turnaround", value: "78 min without line acceleration", type: "text" },
          ],
          technicalDetail: "Turnaround model projected tanker turnaround under manual chemist sampling cycle.",
        },
        {
          stage: "DIAGNOSE",
          label: "Causal Attribution",
          subLabel: "Line Clearance Bottleneck",
          status: "COMPLETED",
          timestamp: "09:42:11",
          summary: "Product line clearance required to prevent aviation fuel flashpoint contamination",
          metrics: [
            { label: "Bottleneck", value: "Manifold Product Clearance", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Contamination Hazard", value: "AGO residue > 5ppm lowers Jet-A1 flashpoint below safety spec", type: "badge" },
          ],
          technicalDetail: "Chemical compatibility matrix flagged critical safety violation.",
        },
        {
          stage: "OPTIMIZE",
          label: "Combinatorial Optimization",
          subLabel: "Candidate Evaluation",
          status: "COMPLETED",
          timestamp: "09:42:13",
          summary: "Autonomous purge candidate evaluated and passed to policy governance gate",
          metrics: [
            { label: "Candidate", value: "Automated Line Purge Sequence" },
          ],
          payloadEntries: [
            { key: "Prototype Optimization Evaluation", value: "PUMP_PURGE_SEQUENCE(MANIFOLD_M04, DRAIN_SLOP)", type: "code" },
          ],
          technicalDetail: "Optimizer attempted to minimize dwell time by proposing automatic line flushing.",
        },
        {
          stage: "DECIDE",
          label: "Policy Governance Gate",
          subLabel: "Safety Interlock Veto",
          status: "BLOCKED",
          timestamp: "09:42:15",
          summary: "POL-088 VETO ACTIVATED: Autonomous override strictly prohibited for aviation fuel transitions",
          metrics: [
            { label: "FlowGuard Rule", value: "POL-088 (Safety Invariant)", isHighlight: true },
            { label: "Gate Decision", value: "BLOCKED BY POLICY" },
            { label: "Override Status", value: "FORBIDDEN" },
          ],
          payloadEntries: [
            { key: "Configured Safety Boundary", value: "POL-088 requires certified laboratory chemist physical sign-off", type: "badge" },
            { key: "Engine Action", value: "Vetoed automated actuation; engaged physical gantry interlock XV-2801", type: "badge" },
          ],
          technicalDetail: "Deterministic safety invariant in FlowGuard Policy Engine. Zero autonomous bypass allowed.",
        },
        {
          stage: "EXECUTE",
          label: "Operational Actuation",
          subLabel: "Safe State Hold",
          status: "COMPLETED",
          timestamp: "09:42:18",
          summary: "Engaged safety interlock; dispatched urgent notification to Kisumu QA Laboratory",
          metrics: [
            { label: "Interlock State", value: "LOCKED (CLOSED)", isHighlight: true },
            { label: "Notification", value: "Dispatched to Chief Chemist" },
          ],
          payloadEntries: [
            { key: "Prototype Actuation Payload", value: "LOCK_VALVE(XV-2801, CLOSED); ALERT_QA_LAB(STATION_28);", type: "code" },
          ],
          technicalDetail: "Interlock confirmed by field telemetry within 65ms.",
        },
        {
          stage: "VERIFY",
          label: "Closed-Loop Verification",
          subLabel: "Safety Confirmation",
          status: "COMPLETED",
          timestamp: "09:42:20",
          summary: "Verified physical valve closed; contamination hazard fully prevented",
          metrics: [
            { label: "Safety Status", value: "CONFIRMED SAFE", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Field Verification", value: "Valve limit switch ZSO-2801 confirmed closed", type: "text" },
          ],
          technicalDetail: "Zero fuel flow registered on mass-flow sensor FM-2801.",
        },
        {
          stage: "LOG",
          label: "Forensic Audit Record",
          subLabel: "Safety Veto Audit Log",
          status: "COMPLETED",
          timestamp: "09:42:22",
          summary: "Recorded safety veto and lab dispatch event into tamper-evident audit ledger",
          metrics: [
            { label: "Audit Hash", value: "sha256:91c0e44...", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Event", value: "AUTONOMOUS_ACTUATION_BLOCKED_BY_SAFETY_INVARIANT", type: "badge" },
          ],
          technicalDetail: "Cryptographically integrity-checked audit record stamped with SHA-256 digest.",
        },
      ],
    },
    {
      id: "INT-8805",
      timestamp: "09:18:44",
      depotId: "eldoret",
      depotName: "Eldoret Terminal (PS27)",
      headline: "Smart Gate Automated Barrier Divert Failed — Safely Handed Over to Gate Marshal",
      status: "FAILED",
      autonomyLevel: "L2",
      predictedProblem: "Entrance gate queue buildup of 5 tankers causing 28 min tare weighbridge delay",
      telemetryTrigger: "Smart Gate 1 queue reached 5 tankers; FlowGuard triggered automated routing to auxiliary Scale 2",
      causalFactors: [
        { factor: "Gate 1 ingress batch surge (5 tankers in 8 min)", impactScore: 68, category: "gate" },
        { factor: "Optical RFID transponder read failure on vehicle KDD 884M", impactScore: 32, category: "equipment" },
      ],
      selectedCandidateId: "OPT-51",
      appliedPolicy: {
        id: "POL-005",
        code: "POL-005",
        name: "Automated Gate Lane Balancing & Exception Handover",
        category: "Gate",
        autonomyLevel: "L2 — AUTO-EXECUTABLE",
        condition: "Ingress gate queue > 4 tankers AND auxiliary scale available",
        actionAuthorized: "Autonomous Variable Message Sign (VMS) lane diversion instruction and automated barrier actuation",
        safetyInvariant: "Configured safety boundary: If RFID handshake or vehicle compliance check fails, automated barrier must remain closed and escalate to manual Gate Marshal within 15 seconds",
        status: "ACTIVE",
        lastEvaluated: "09:18:40",
        evaluationPass: true,
      },
      candidates: [
        {
          id: "OPT-51",
          rank: 1,
          name: "Autonomous Gate Lane Switching & VMS Display",
          actionType: "Automated Ingress Routing",
          predictedTurnaroundMin: 42,
          exposureKes: 110000,
          disruptionScore: "Low",
          feasibility: "Selected",
          objectiveScore: 92,
          selectionRationale: "Best projected turnaround improvement while remaining within configured autonomy policy; reduces weighbridge wait from 28m to 8m",
          queueReductionExpectedMin: 20,
          ordersAffected: 3,
        },
      ],
      actuationDetails: {
        dispatchTarget: "Operational Actuation Interface (Eldoret Gate Automation & Scale Controller)",
        commandType: "LANE_DIVERSION_VMS_UPDATE & BARRIER_ARM",
        affectedOrders: ["LO-ELD-6604"],
        dispatchedAt: "09:18:44.110",
        ackLatencyMs: 180,
        actuationStatus: "FAILED",
        targetDevice: "Automated Tare Scale 2 Barrier Controller",
      },
      verification: {
        targetReductionMin: 20,
        verifiedReductionMin: 0,
        varianceMin: 20,
        exposureProtectedKes: 0,
        realizedSavingsKes: 0,
        recoveryAttainmentPct: 0,
        status: "FAILED",
        measuredAt: "09:19:02",
        verificationMethod: "Vehicle transponder handshake timed out after 3 retries (14.2 seconds). Anomaly safely escalated to Gate Marshal.",
      },
      auditHash: "sha256:4a08bc7811de9920147cb2019941a8770132b847190014a029db881729013ac1",
      operatorNotes: "Action failed safely (Failure ≠ Collapse). Gate barrier held closed; Gate Marshal processed paper manifest manually in 2.5 minutes.",
      timelineSteps: [
        {
          stage: "SIGNAL",
          label: "Telemetry Ingestion",
          subLabel: "Tare Scale Queue Detection",
          status: "COMPLETED",
          timestamp: "09:18:25",
          summary: "Detected 5 road tankers queued at Eldoret Gate 1",
          metrics: [
            { label: "Gate Queue", value: "5 tankers", isHighlight: true },
            { label: "Tare Scale 2", value: "Available (Idle)" },
          ],
          payloadEntries: [
            { key: "Queue Sensor", value: "Loop detector LD-ELD-01 triggered continuous presence", type: "text" },
          ],
          technicalDetail: "Inductive ground loop sensor telemetry sampled at 1Hz.",
        },
        {
          stage: "PREDICT",
          label: "Predictive Modeling",
          subLabel: "Ingress Dwell Forecast",
          status: "COMPLETED",
          timestamp: "09:18:32",
          summary: "Forecasted 28 min wait before weighbridge entry",
          metrics: [
            { label: "Predicted Tare Wait", value: "28 min", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Bottleneck Horizon", value: "Expected +14m delay cascading into gantry loading bay entry", type: "text" },
          ],
          technicalDetail: "Queue arrival Markov chain projected queue clearance time.",
        },
        {
          stage: "DIAGNOSE",
          label: "Causal Attribution",
          subLabel: "Ingress Lane Imbalance",
          status: "COMPLETED",
          timestamp: "09:18:36",
          summary: "Single-lane gate constraint while secondary weighbridge was vacant",
          metrics: [
            { label: "Diagnosis", value: "Gate Lane Imbalance", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Scale 1 Utilization", value: "100% (Congested)", type: "text" },
            { key: "Scale 2 Utilization", value: "0% (Ready for Tare)", type: "badge" },
          ],
          technicalDetail: "Automated gate load-balancer identified unutilized physical capacity.",
        },
        {
          stage: "OPTIMIZE",
          label: "Combinatorial Optimization",
          subLabel: "Lane Divert Selection",
          status: "COMPLETED",
          timestamp: "09:18:38",
          summary: "Selected autonomous diversion of upcoming tanker KDD 884M to Scale 2",
          metrics: [
            { label: "Selected Action", value: "Divert KDD 884M to Scale 2" },
          ],
          payloadEntries: [
            { key: "Prototype Optimization Evaluation", value: "UPDATE_VMS(GATE_2, 'TRUCK KDD 884M ENTER SCALE 2')", type: "code" },
          ],
          technicalDetail: "Optimal route assignment calculated to eliminate queue delta.",
        },
        {
          stage: "DECIDE",
          label: "Policy Governance Gate",
          subLabel: "POL-005 Compliance Check",
          status: "COMPLETED",
          timestamp: "09:18:40",
          summary: "Passed POL-005: Automated lane diversion authorized under fail-safe interlock",
          metrics: [
            { label: "FlowGuard Rule", value: "POL-005 (Active)" },
            { label: "Fail-Safe Rule", value: "15s Escalation Enforced", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Configured Safety Boundary", value: "Barrier stays closed if RFID tag unverified within 15 seconds", type: "badge" },
          ],
          technicalDetail: "Policy rules checked via automated rule validator.",
        },
        {
          stage: "EXECUTE",
          label: "Operational Actuation",
          subLabel: "Actuation Failure Detected",
          status: "FAILED",
          timestamp: "09:18:44",
          summary: "Actuation failed: Transponder read timeout; barrier safely held closed to prevent unauthorized entry",
          metrics: [
            { label: "Actuation", value: "FAILED (TIMEOUT)", isHighlight: true },
            { label: "Barrier Status", value: "HELD CLOSED (SAFE)" },
          ],
          payloadEntries: [
            { key: "Prototype Actuation Payload", value: "RFID reader reported ERR_NO_TAG_DETECTED (3 retries timed out)", type: "code" },
            { key: "Safety Response", value: "Automated barrier refused lift command; triggered operator buzzer", type: "badge" },
          ],
          technicalDetail: "Transponder protocol returned timeout error code. Fail-safe watchdog engaged.",
        },
        {
          stage: "VERIFY",
          label: "Closed-Loop Verification",
          subLabel: "Escalation Confirmation",
          status: "FAILED",
          timestamp: "09:19:02",
          summary: "Safe failover verified: Escalated to on-duty Gate Marshal within 14.2 seconds",
          metrics: [
            { label: "Escalation Latency", value: "14.2s (< 15s limit)", isHighlight: true },
            { label: "Handover Status", value: "MANUAL MARSHAL ACTIVE" },
          ],
          payloadEntries: [
            { key: "Marshal Action", value: "Gate Marshal verified vehicle paper manifest manually", type: "text" },
          ],
          technicalDetail: "Failover watchdog confirmed automated control release to manual terminal panel.",
        },
        {
          stage: "LOG",
          label: "Forensic Audit Record",
          subLabel: "Hardware Failure Incident Log",
          status: "COMPLETED",
          timestamp: "09:19:05",
          summary: "Failure telemetry and operator handover recorded in tamper-evident audit log",
          metrics: [
            { label: "Audit Hash", value: "sha256:4a08bc7...", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Fault Code", value: "RFID_READ_TIMEOUT_AUTO_FAILOVER_TO_OPERATOR", type: "code" },
          ],
          technicalDetail: "Cryptographically integrity-checked audit record logged to centralized operations database.",
        },
      ],
    },
    {
      id: "INT-8803",
      timestamp: "08:48:30",
      depotId: "mombasa",
      depotName: "Mombasa Terminal (PS01)",
      headline: "High Collection Demand With No Compliant Autonomous Action — Escalated to Controller",
      status: "BLOCKED / ESCALATED",
      autonomyLevel: "L3",
      predictedProblem: "Heavy regional AGO collection surge (22 road tankers in 90 min) while 2 of 6 gantry loading bays undergoing scheduled flow meter verification, predicting 95 min turnaround (+35m above SLA) and KES 1.15M demurrage exposure",
      telemetryTrigger: "Expected demand (22 orders) severely exceeds effective processing capacity (12 orders) with remaining bays at maximum thermal capacity",
      causalFactors: [
        { factor: "Gantry loading capacity constrained (2 of 6 bays offline for calibration)", impactScore: 52, category: "capacity" },
        { factor: "Regional transit order arrival surge (22 tankers in 90 min window)", impactScore: 36, category: "demand" },
        { factor: "Ambient temperature thermal flow reduction on active meters", impactScore: 12, category: "equipment" },
      ],
      selectedCandidateId: "OPT-34",
      appliedPolicy: {
        id: "POL-050",
        code: "POL-050",
        name: "Mandatory Human Escalation When Feasible Autonomous Action Space is Empty",
        category: "Safety",
        autonomyLevel: "L3 — HUMAN APPROVAL",
        condition: "Predicted dwell blowout > 30m AND all candidate autonomous actions violate safety or policy boundaries",
        actionAuthorized: "STRICTLY PROHIBITED FROM AUTONOMOUS OVERRIDE. Mandates immediate operational escalation to Terminal Superintendent with candidate trade-off dossier.",
        safetyInvariant: "Configured safety boundary: Bounded Autonomy Guardrail — When no safe autonomous action exists, the engine must safely halt and hand over to human command.",
        status: "ACTIVE",
        lastEvaluated: "08:48:26",
        evaluationPass: false,
      },
      candidates: [
        {
          id: "OPT-31",
          rank: 1,
          name: "Bypass Meter Thermal Limiter to Force 2,000 L/min Flow Rate",
          actionType: "Equipment Overdrive",
          predictedTurnaroundMin: 52,
          exposureKes: 180000,
          disruptionScore: "High",
          feasibility: "Blocked by Policy",
          objectiveScore: 15,
          selectionRationale: "Blocked: critical safety violation — exceeds maximum gantry pump pressure ceiling (8.5 bar) and meter calibration envelope",
          queueReductionExpectedMin: 32,
          ordersAffected: 6,
        },
        {
          id: "OPT-32",
          rank: 2,
          name: "Reroute Tankers to External Unlicensed Third-Party Loading Rack",
          actionType: "External Reroute",
          predictedTurnaroundMin: 68,
          exposureKes: 420000,
          disruptionScore: "Severe",
          feasibility: "Blocked by Policy",
          objectiveScore: 10,
          selectionRationale: "Blocked: commercial policy violation — off-spec custody transfer prohibited without executive director approval",
          queueReductionExpectedMin: 18,
          ordersAffected: 8,
        },
        {
          id: "OPT-33",
          rank: 3,
          name: "Stack >12 Road Tankers Inside Loading Gantry Apron",
          actionType: "Apron Overflow Stacking",
          predictedTurnaroundMin: 84,
          exposureKes: 780000,
          disruptionScore: "High",
          feasibility: "Blocked by Policy",
          objectiveScore: 24,
          selectionRationale: "Blocked: terminal fire safety violation — apron vehicle count strictly capped at 8 road tankers under emergency evacuation code",
          queueReductionExpectedMin: 8,
          ordersAffected: 10,
        },
        {
          id: "OPT-34",
          rank: 4,
          name: "Halt Autonomous Actuation & Escalate to Terminal Superintendent",
          actionType: "Bounded Autonomy Safety Escalation",
          predictedTurnaroundMin: 95,
          exposureKes: 1150000,
          disruptionScore: "None",
          feasibility: "Selected",
          objectiveScore: 85,
          selectionRationale: "No compliant autonomous intervention available under current operating constraints. Human decision required.",
          queueReductionExpectedMin: 0,
          ordersAffected: 0,
        },
      ],
      actuationDetails: {
        dispatchTarget: "Operational Actuation Interface (Mombasa Superintendent Console)",
        commandType: "MANDATORY_HUMAN_DECISION_DOSSIER_DISPATCHED",
        affectedOrders: ["LO-MBA-5510", "LO-MBA-5512", "LO-MBA-5515", "LO-MBA-5519"],
        dispatchedAt: "08:48:30.405",
        ackLatencyMs: 78,
        actuationStatus: "ESCALATED",
        targetDevice: "Terminal Superintendent Operational Console",
      },
      verification: {
        targetReductionMin: 0,
        exposureProtectedKes: 0,
        realizedSavingsKes: 0,
        recoveryAttainmentPct: 100,
        status: "ESCALATED",
        measuredAt: "08:54:10",
        verificationMethod: "Confirmed no unauthorized actuation dispatched. Operational dossier delivered to Mombasa Terminal Superintendent within 78ms.",
      },
      auditHash: "sha256:1b94ea8820c710499aae3811904bcda771038294911aa7841029cba881402319",
      operatorNotes: "Bounded Autonomy demonstration: FlowGuard safely refused to execute non-compliant options and escalated to human controller.",
      timelineSteps: [
        {
          stage: "SIGNAL",
          label: "Telemetry Ingestion",
          subLabel: "Demand & Capacity Telemetry",
          status: "COMPLETED",
          timestamp: "08:48:10",
          summary: "Identified severe collection demand surge (22 tankers) with 2 bays offline for calibration",
          metrics: [
            { label: "Expected Demand", value: "22 tankers / 90m", isHighlight: true },
            { label: "Usable Gantries", value: "4 of 6 operational" },
          ],
          payloadEntries: [
            { key: "Simulated Field Signal", value: "22 export AGO collection orders logged in ERP for Mombasa terminal", type: "text" },
          ],
          technicalDetail: "Sensory ingestion verified bottleneck: demand exceeds processing capacity by 10 tankers.",
        },
        {
          stage: "PREDICT",
          label: "Predictive Modeling",
          subLabel: "Turnaround Blowout Forecast",
          status: "COMPLETED",
          timestamp: "08:48:18",
          summary: "Forecasted 95 min average turnaround (+35m above SLA) and KES 1.15M demurrage exposure",
          metrics: [
            { label: "Predicted Dwell", value: "95 min (+35m)", isHighlight: true },
            { label: "Demurrage Risk", value: "KES 1,150,000" },
          ],
          payloadEntries: [
            { key: "Prototype Model Output", value: "Queue probability 94% across Bays P01–P04", type: "text" },
          ],
          technicalDetail: "Prediction model projected queue formation cascading onto Mombasa depot access road.",
        },
        {
          stage: "DIAGNOSE",
          label: "Causal Attribution",
          subLabel: "Capacity Shortfall Analysis",
          status: "COMPLETED",
          timestamp: "08:48:22",
          summary: "Root cause: Physical capacity shortfall compounded by meter recertification downtime",
          metrics: [
            { label: "Primary Cause", value: "Capacity Shortfall (52%)", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Causal Diagnostic", value: "No idle bays available; active bays operating at thermal ceiling", type: "text" },
          ],
          technicalDetail: "Bottleneck attribution verified no equipment fault on active positions.",
        },
        {
          stage: "OPTIMIZE",
          label: "Combinatorial Optimization",
          subLabel: "Candidate Search Exhausted",
          status: "COMPLETED",
          timestamp: "08:48:24",
          summary: "Evaluated 4 candidate options; all autonomous actuation candidates violate safety boundaries",
          metrics: [
            { label: "Permutations Evaluated", value: "4 candidates" },
            { label: "Compliant Action Found", value: "None (Zero Feasible)", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Prototype Optimization Evaluation", value: "All active candidate options produce safety or fire code violations", type: "badge" },
          ],
          technicalDetail: "Solver confirmed feasible autonomous action space is empty under configured constraints.",
        },
        {
          stage: "DECIDE",
          label: "Policy Governance Gate",
          subLabel: "FlowGuard Rule POL-050 Enforced",
          status: "BLOCKED",
          timestamp: "08:48:26",
          summary: "POL-050 ENFORCED: Safe stop activated — engine refuses to act and triggers human escalation",
          metrics: [
            { label: "FlowGuard Rule", value: "POL-050 (Active)", isHighlight: true },
            { label: "Action Status", value: "BLOCKED / ESCALATED" },
          ],
          payloadEntries: [
            { key: "Configured Safety Boundary", value: "Mandatory human escalation when feasible autonomous action space is empty", type: "badge" },
            { key: "Decision Verdict", value: "No compliant autonomous intervention available. Human decision required.", type: "badge" },
          ],
          technicalDetail: "Engine safely halted autonomous pipeline per configured bounded autonomy guardrail.",
        },
        {
          stage: "EXECUTE",
          label: "Operational Actuation",
          subLabel: "Human Escalation Dispatched",
          status: "COMPLETED",
          timestamp: "08:48:30",
          summary: "Dispatched operational dossier to Terminal Superintendent console; zero field actuation attempted",
          metrics: [
            { label: "Escalated At", value: "08:48:30.405", isHighlight: true },
            { label: "Handover Latency", value: "78 ms" },
          ],
          payloadEntries: [
            { key: "Prototype Actuation Payload", value: "DISPATCH_SUPERINTENDENT_DOSSIER(INCIDENT_INT-8803, OPTIONS_DOSSIER)", type: "code" },
          ],
          technicalDetail: "Handover delivered to human operator with candidate trade-off analysis.",
        },
        {
          stage: "VERIFY",
          label: "Closed-Loop Verification",
          subLabel: "Safe Halt Confirmed",
          status: "COMPLETED",
          timestamp: "08:54:10",
          summary: "Verified no unauthorized field commands dispatched; human superintendent assumed command",
          metrics: [
            { label: "Safety Status", value: "CONFIRMED SAFE", isHighlight: true },
            { label: "Human Handover", value: "ACKNOWLEDGED" },
          ],
          payloadEntries: [
            { key: "Verification Reading", value: "Zero gantry command mutations executed by engine", type: "badge" },
          ],
          technicalDetail: "Field telemetry confirmed all gantries remained strictly under manual/scheduled operation.",
        },
        {
          stage: "LOG",
          label: "Forensic Audit Record",
          subLabel: "Bounded Autonomy Log",
          status: "COMPLETED",
          timestamp: "08:54:15",
          summary: "Recorded empty action space and superintendent escalation in tamper-evident audit ledger",
          metrics: [
            { label: "Audit Hash", value: "sha256:1b94ea8...", isHighlight: true },
          ],
          payloadEntries: [
            { key: "Event", value: "AUTONOMY_SAFE_HALT_AND_HUMAN_ESCALATION", type: "badge" },
          ],
          technicalDetail: "Cryptographically integrity-checked append-only audit record stamped with SHA-256 digest.",
        },
      ],
    },
  ];
}

export function initAllTelemetryDataSources(): TelemetryDataSource[] {
  return [
    {
      id: "SRC-01",
      name: "ERP / Loading Orders",
      systemCategory: "ERP",
      sourceSystem: "Enterprise ERP System (Loading Authorizations)",
      status: "HEALTHY",
      latencyMs: 120,
      lastSync: "2s ago",
      sampleRate: "Polling every 10s",
      healthPct: 100.0,
      fallbackMechanism: "Cached Order Manifest & Local Database Replicas",
      isFallbackActive: false,
      recordRatePerMin: 14,
      protocol: "OData / REST Service",
    },
    {
      id: "SRC-02",
      name: "Gate & Scale Events",
      systemCategory: "GATE",
      sourceSystem: "Automated Gate & Tare Weighbridge System",
      status: "HEALTHY",
      latencyMs: 85,
      lastSync: "1s ago",
      sampleRate: "Event-driven (Sub-second)",
      healthPct: 99.8,
      fallbackMechanism: "Manual Gate Attendant Manifest Log",
      isFallbackActive: false,
      recordRatePerMin: 28,
      protocol: "Industrial Sensor Bus / MQTT",
    },
    {
      id: "SRC-03",
      name: "Loading / Mass-Flow Telemetry",
      systemCategory: "METERING",
      sourceSystem: "Gantry Mass-Flow Metering System",
      status: "HEALTHY",
      latencyMs: 45,
      lastSync: "500ms ago",
      sampleRate: "Continuous (250ms interval)",
      healthPct: 98.4,
      fallbackMechanism: "Secondary Flow Telemetry Backup",
      isFallbackActive: false,
      recordRatePerMin: 240,
      protocol: "Industrial Ethernet / Modbus",
    },
    {
      id: "SRC-04",
      name: "Equipment & Maintenance State",
      systemCategory: "SCADA",
      sourceSystem: "Depot Maintenance & Equipment Monitoring",
      status: "HEALTHY",
      latencyMs: 340,
      lastSync: "15s ago",
      sampleRate: "Polling every 30s",
      healthPct: 100.0,
      fallbackMechanism: "Last Known Bay Hardware State Cache",
      isFallbackActive: false,
      recordRatePerMin: 6,
      protocol: "REST API / Event Stream",
    },
    {
      id: "SRC-05",
      name: "Tank / Product Readiness",
      systemCategory: "TANK_FARM",
      sourceSystem: "Automated Tank Gauging & Inventory System",
      status: "HEALTHY",
      latencyMs: 180,
      lastSync: "4s ago",
      sampleRate: "Polling every 5s",
      healthPct: 100.0,
      fallbackMechanism: "Manual Dip-Tape Level Entry & Lab Release",
      isFallbackActive: false,
      recordRatePerMin: 12,
      protocol: "SCADA Telemetry Bus",
    },
    {
      id: "SRC-06",
      name: "Historical Turnaround Baseline",
      systemCategory: "HISTORICAL",
      sourceSystem: "FlowGuard Analytical Baseline Store (50k Journeys)",
      status: "HEALTHY",
      latencyMs: 12,
      lastSync: "Real-Time",
      sampleRate: "Continuous Reference Model",
      healthPct: 100.0,
      fallbackMechanism: "Static Baseline Velocity Distributions",
      isFallbackActive: false,
      recordRatePerMin: 0,
      protocol: "In-Memory Vector Engine",
    },
    {
      id: "SRC-07",
      name: "External Arrival Signals",
      systemCategory: "TELEMATICS",
      sourceSystem: "Regional Transporter Route Telemetry",
      status: "HEALTHY",
      latencyMs: 820,
      lastSync: "8s ago",
      sampleRate: "Periodic updates (15s)",
      healthPct: 99.2,
      fallbackMechanism: "Historical Turnaround Baseline (Gate Queue Fallback)",
      isFallbackActive: false,
      recordRatePerMin: 18,
      protocol: "HTTPS Webhook / REST",
    },
  ];
}

export function initPolicyRules(): AutonomyPolicyRule[] {
  return [
    {
      id: "POL-042",
      code: "POL-042",
      name: "High-Demand Dual-Arm Fast-Track Authorization",
      category: "Capacity",
      autonomyLevel: "L2 — AUTO-EXECUTABLE",
      condition: "Predicted queue dwell delta > 25m AND compatible multi-compartment road tanker AND zero hazardous cargo conflict",
      actionAuthorized: "Autonomous gantry arm dual-coupling and internal yard re-sequencing without supervisor pre-approval",
      safetyInvariant: "Configured safety boundary: Dual-coupling permitted only for compatible PMS/AGO compartments with certified vapor recovery lines",
      status: "ACTIVE",
      lastEvaluated: "10:02:44",
      evaluationPass: true,
    },
    {
      id: "POL-012",
      code: "POL-012",
      name: "Flow Meter Drift Divert & Shift Controller Sign-Off",
      category: "Equipment",
      autonomyLevel: "L3 — HUMAN APPROVAL",
      condition: "Loading position flow variance exceeds 15% AND heavy road tankers (>35,000L) queued",
      actionAuthorized: "Bay divert to auxiliary gantry position P03 and automated service work order dispatch",
      safetyInvariant: "Configured safety boundary: Physical bay re-allocation of queued petroleum vehicles requires designated shift supervisor electronic authorization",
      status: "ACTIVE",
      lastEvaluated: "10:05:10",
      evaluationPass: true,
    },
    {
      id: "POL-088",
      code: "POL-088",
      name: "Aviation Fuel Cross-Contamination Safety Interlock",
      category: "Safety",
      autonomyLevel: "L3 — HUMAN APPROVAL",
      condition: "Manifold line transition involving Aviation Turbine Fuel (Jet-A1) or DPK",
      actionAuthorized: "STRICTLY PROHIBITED FROM AUTONOMOUS OVERRIDE. Requires physical certified quality lab chemist sign-off.",
      safetyInvariant: "Configured safety boundary: Zero tolerance for aviation fuel contamination. Quality sign-off cannot be automated under any operational circumstance.",
      status: "ACTIVE",
      lastEvaluated: "09:42:15",
      evaluationPass: true,
    },
    {
      id: "POL-005",
      code: "POL-005",
      name: "Automated Gate Lane Balancing & Exception Handover",
      category: "Gate",
      autonomyLevel: "L2 — AUTO-EXECUTABLE",
      condition: "Ingress gate queue > 4 tankers AND auxiliary scale available",
      actionAuthorized: "Autonomous Variable Message Sign (VMS) lane diversion instruction and automated barrier actuation",
      safetyInvariant: "Configured safety boundary: If RFID handshake or vehicle compliance check fails, automated barrier must remain closed and escalate to manual Gate Marshal within 15 seconds",
      status: "ACTIVE",
      lastEvaluated: "09:18:40",
      evaluationPass: true,
    },
    {
      id: "POL-050",
      code: "POL-050",
      name: "Mandatory Human Escalation When Feasible Action Space Empty",
      category: "Safety",
      autonomyLevel: "L3 — HUMAN APPROVAL",
      condition: "Predicted dwell blowout > 30m AND all candidate autonomous actions violate safety or policy boundaries",
      actionAuthorized: "STRICTLY PROHIBITED FROM AUTONOMOUS OVERRIDE. Mandates immediate operational escalation to Terminal Superintendent with candidate trade-off dossier.",
      safetyInvariant: "Configured safety boundary: When no safe autonomous action exists, the engine must safely halt and hand over to human command.",
      status: "ACTIVE",
      lastEvaluated: "08:48:26",
      evaluationPass: true,
    },
    {
      id: "POL-019",
      code: "POL-019",
      name: "Autonomous Gantry Queue Re-sequencing Bound",
      category: "Capacity",
      autonomyLevel: "L2 — AUTO-EXECUTABLE",
      condition: "Total re-sequenced tankers within 1-hour window <= 8 vehicles AND no tanker delayed > 15m beyond appointment",
      actionAuthorized: "Automated re-ordering of gantry loading queue to optimize batch flow rates",
      safetyInvariant: "Configured safety boundary: Fairness bound — No individual collection order may be delayed > 15m to benefit a higher-volume order",
      status: "ACTIVE",
      lastEvaluated: "10:02:45",
      evaluationPass: true,
    },
  ];
}

export function initAutonomyMetrics(): AutonomyAggregateMetrics {
  return {
    modelVersion: "FG-TURNAROUND-SYNTH-v1.4",
    calibrationAccuracyPct: 94.2,
    successRatePct: 92.0,
    interventionsExecutedTotal: 50,
    interventionsVerifiedSuccess: 46,
    meanArrivalErrorMin: 8.4,
    meanTurnaroundErrorMin: 11.2,
    totalExposureProtectedKes: 14820000,
    activeRulesCount: 18,
    unauthorizedInterventionsCount: 0,
    lastDriftCheck: "4 min ago",
  };
}

export function initSubsystemHealth(): AutonomySubsystemHealth {
  return {
    predictionEngine: "OPERATIONAL",
    optimizationEngine: "OPERATIONAL",
    policyGate: "ACTIVE",
    actionExecutor: "ARMED",
    eventStream: "STREAMING",
    auditLogger: "IMMUTABLE_SYNCED",
  };
}
