import {
  OmcId,
  OmcProfile,
  OmcCollectionOrder,
  OmcNotification,
  OmcHourlyOutlook,
  OmcKpiSummary,
} from "@/types/flowguard";

export const initAllOmcProfiles = (): Record<OmcId, OmcProfile> => ({
  vivo: {
    id: "vivo",
    name: "Vivo Energy Kenya Ltd",
    shortName: "Vivo Energy",
    accountCode: "OMC-VIVO-KE-004",
    activeOrdersCount: 8,
    atRiskCount: 3,
    onTrackCount: 5,
    primaryDepot: "nairobi",
    contactEmail: "dispatch.logistics@vivoenergy.com",
    contactPhone: "+254 20 523 0000",
  },
  totalenergies: {
    id: "totalenergies",
    name: "TotalEnergies Marketing Kenya Plc",
    shortName: "TotalEnergies",
    accountCode: "OMC-TOTAL-KE-001",
    activeOrdersCount: 6,
    atRiskCount: 2,
    onTrackCount: 4,
    primaryDepot: "mombasa",
    contactEmail: "supply.chain@totalenergies.ke",
    contactPhone: "+254 20 289 7000",
  },
  rubis: {
    id: "rubis",
    name: "Rubis Energy Kenya Plc",
    shortName: "Rubis Energy",
    accountCode: "OMC-RUBIS-KE-007",
    activeOrdersCount: 5,
    atRiskCount: 2,
    onTrackCount: 3,
    primaryDepot: "nakuru",
    contactEmail: "operations.dispatch@rubiskenya.com",
    contactPhone: "+254 20 275 5000",
  },
  lakeoil: {
    id: "lakeoil",
    name: "Lake Oil Kenya Ltd",
    shortName: "Lake Oil",
    accountCode: "OMC-LAKE-KE-012",
    activeOrdersCount: 4,
    atRiskCount: 1,
    onTrackCount: 3,
    primaryDepot: "eldoret",
    contactEmail: "fleet.logistics@lakeoilgroup.com",
    contactPhone: "+254 70 982 1000",
  },
  ola: {
    id: "ola",
    name: "Ola Energy Kenya Ltd",
    shortName: "Ola Energy",
    accountCode: "OMC-OLA-KE-003",
    activeOrdersCount: 4,
    atRiskCount: 1,
    onTrackCount: 3,
    primaryDepot: "nairobi",
    contactEmail: "supply.dispatch@olaenergy.com",
    contactPhone: "+254 20 695 2000",
  },
  hass: {
    id: "hass",
    name: "Hass Petroleum Kenya Ltd",
    shortName: "Hass Petroleum",
    accountCode: "OMC-HASS-KE-015",
    activeOrdersCount: 3,
    atRiskCount: 1,
    onTrackCount: 2,
    primaryDepot: "kisumu",
    contactEmail: "operations@hasspetroleum.com",
    contactPhone: "+254 20 271 3131",
  },
});

export const initAllOmcOrders = (): Record<OmcId, OmcCollectionOrder[]> => ({
  vivo: [
    {
      id: "LO-NBO-8821",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KDD 412X",
      transporterName: "Trans-Rift Hauliers Ltd",
      driverName: "James Mwangi (ID: 24891002)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P01",
      status: "LOADING",
      orderPlacementTime: "07:15",
      expectedArrival: "08:00",
      gateInTime: "08:08",
      predictedGateOut: "11:02 AM",
      gateOutConfidencePct: 93,
      predictedTurnaroundMin: 64,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 16,
      riskSeverity: "ELEVATED",
      lastUpdate: "Just now",
      assignedBay: "Bay P01 (High-Velocity)",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "07:15",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 8,
          note: "TSA quota verified, Electronic Loading Order approved by KPC commercial desk.",
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "COMPLETED",
          timestamp: "08:08",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 12,
          note: "Driver identity verified, tare scale measured 14.8 tonnes. Smart Gate transponder scanned.",
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "COMPLETED",
          timestamp: "08:24",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 16,
          note: "KRA RECTS transponder authenticated. Customs export pre-clearance active.",
          customsReleaseStatus: "RELEASED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "ACTIVE",
          timestamp: "08:35",
          expectedDurationMin: 35,
          actualOrPredictedDurationMin: 28,
          note: "Active on Bay P01. Dual loading arm engaged. Flow rate 2,240 L/min.",
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "11:02 AM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
          note: "Projected gross weight check, high-security seal verification & manifest printout.",
        },
      ],
      whyAtRisk: {
        headline: "Morning Peak Gantry Demand vs Usable Loading Positions",
        causeSummary: "18 collection orders converging in morning window while 2 gantries undergo meter inspection.",
        causalContributions: [
          { factor: "Depot Demand Pressure", detail: "18 orders scheduled vs 11 effective capacity", impactLevel: "High" },
          { factor: "Usable Gantries", detail: "5 of 8 gantries usable (P06/P08 offline)", impactLevel: "Medium" },
          { factor: "Loading Flow Rate", detail: "86% of calibrated baseline velocity", impactLevel: "Low" },
        ],
      },
      flowGuardAssessment: {
        summary: "This collection was at critical delay risk (+38 min), but FlowGuard autonomous re-sequencing and dual-arm allocation recovered 22 minutes.",
        confidencePct: 93,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      flowGuardAction: {
        actionName: "Dual-Arm Fast Track & Queue Re-sequence (INT-8801)",
        timestamp: "08:30",
        expectedImpactMin: -22,
        status: "EXECUTED",
        beforeGateOut: "11:24 AM",
        afterGateOut: "11:02 AM",
        rationale: "Allocated dual-arm loading on high-capacity Bay P01 to accelerate turnover by 22 minutes.",
      },
      exposure: {
        potentialKes: 480000,
        protectedKes: 350000,
        realizedKes: 320000,
      },
      communicationStatus: {
        notified: true,
        acknowledged: true,
        notifiedAt: "08:31",
        acknowledgedAt: "08:35",
      },
    },
    {
      id: "LO-NKR-4412",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KDB 918Q",
      transporterName: "Rift Valley Petroleum Fleet",
      driverName: "Daniel Kiprop (ID: 21980442)",
      depotId: "nakuru",
      depotName: "Nakuru Depot (PS25)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Hold / Verification",
      status: "AT RISK",
      orderPlacementTime: "08:30",
      expectedArrival: "09:15",
      gateInTime: "09:22",
      predictedGateOut: "12:12 PM",
      gateOutConfidencePct: 88,
      predictedTurnaroundMin: 92,
      baselineTurnaroundMin: 58,
      turnaroundDeltaMin: 34,
      riskSeverity: "CRITICAL",
      lastUpdate: "3 min ago",
      assignedBay: "Bay P02 (Flow Impaired)",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "08:30",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 10,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "COMPLETED",
          timestamp: "09:22",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "ACTIVE",
          timestamp: "09:36",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 28,
          note: "Awaiting final KRA electronic release document reconciliation.",
          customsReleaseStatus: "INSPECTION_HOLD",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "PREDICTED",
          timestamp: "10:45 AM",
          expectedDurationMin: 32,
          actualOrPredictedDurationMin: 44,
          note: "Assigned Bay P02 experiencing thermal drift (-18% flow velocity).",
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "12:12 PM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 15,
        },
      ],
      whyAtRisk: {
        headline: "Loading Performance Below Normal & Documentation Review",
        causeSummary: "Loading performance is below normal at Nakuru gantry, and customs documentation reconciliation is in progress.",
        causalContributions: [
          { factor: "Depot Loading Performance", detail: "Gantry loading velocity running below normal baseline", impactLevel: "High" },
          { factor: "Customs Documentation Review", detail: "Electronic export document verification pending", impactLevel: "Medium" },
          { factor: "Available Gantry Positions", detail: "3 of 4 loading positions currently in active use", impactLevel: "Low" },
        ],
      },
      flowGuardAssessment: {
        summary: "Turnaround projected +34m above SLA due to meter drift on Bay P02. FlowGuard proposed divert to Bay P01 upon bay clearance.",
        confidencePct: 88,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      flowGuardAction: {
        actionName: "Bay Divert from Degraded P02 to P01 (INT-8802)",
        timestamp: "09:45",
        expectedImpactMin: -24,
        status: "SUPERVISOR_AUTHORIZED",
        beforeGateOut: "12:36 PM",
        afterGateOut: "12:12 PM",
        rationale: "Reassigned order to Bay P01 once previous truck departs to bypass degraded Coriolis sensor.",
      },
      exposure: {
        potentialKes: 390000,
        protectedKes: 280000,
      },
      communicationStatus: {
        notified: true,
        acknowledged: false,
        notifiedAt: "09:46",
      },
    },
    {
      id: "LO-ELD-3091",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KDA 552L",
      transporterName: "Eldoret Highway Logistics",
      driverName: "Wilson Cheruiyot (ID: 28091144)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GATE_IN",
      currentStageLabel: "Smart Gate Tare In",
      status: "DEVELOPING RISK",
      orderPlacementTime: "08:15",
      expectedArrival: "09:30",
      gateInTime: "09:48",
      predictedGateOut: "11:45 AM",
      gateOutConfidencePct: 89,
      predictedTurnaroundMin: 76,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: 14,
      riskSeverity: "ELEVATED",
      lastUpdate: "6 min ago",
      assignedBay: "Bay P04",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "08:15",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 10,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "ACTIVE",
          timestamp: "09:48",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 22,
          note: "5 tankers arrived simultaneously at entry tare scale.",
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "PREDICTED",
          timestamp: "10:10 AM",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 16,
          customsReleaseStatus: "PRE_CLEARED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "PREDICTED",
          timestamp: "10:32 AM",
          expectedDurationMin: 38,
          actualOrPredictedDurationMin: 38,
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "11:45 AM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 15,
        },
      ],
      whyAtRisk: {
        headline: "Smart Gate Tare Scale Batch Ingress Clustering",
        causeSummary: "Multiple road tankers arrived in a 10-minute cluster, causing temporary gate queue.",
        causalContributions: [
          { factor: "Batch Arrival Clustering", detail: "5 road tankers arrived within 10 min window", impactLevel: "Medium" },
          { factor: "Tare Scale Queue", detail: "Single tare scale operating at 3.2 min/truck", impactLevel: "Medium" },
        ],
      },
      flowGuardAssessment: {
        summary: "Gate queue expected to clear within 25 minutes. FlowGuard has pre-assigned Bay P04 to avoid gantry dwell.",
        confidencePct: 89,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 220000,
        protectedKes: 160000,
      },
      communicationStatus: {
        notified: true,
        acknowledged: false,
        notifiedAt: "09:50",
      },
    },
    {
      id: "LO-MBA-1140",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KBZ 771K",
      transporterName: "Coast Express Hauliers",
      driverName: "Hassan Ali (ID: 19882310)",
      depotId: "mombasa",
      depotName: "Mombasa Terminal (KOT/PS1)",
      product: "JET A-1 (Aviation Turbine Fuel)",
      quantityLitres: 45000,
      compartmentsCount: 4,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P05",
      status: "LOADING",
      orderPlacementTime: "07:45",
      expectedArrival: "08:30",
      gateInTime: "08:42",
      predictedGateOut: "10:55 AM",
      gateOutConfidencePct: 96,
      predictedTurnaroundMin: 54,
      baselineTurnaroundMin: 55,
      turnaroundDeltaMin: -1,
      riskSeverity: "NOMINAL",
      lastUpdate: "8 min ago",
      assignedBay: "Bay P05",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "07:45",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 8,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "COMPLETED",
          timestamp: "08:42",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 12,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "COMPLETED",
          timestamp: "09:00",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 14,
          customsReleaseStatus: "RELEASED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "ACTIVE",
          timestamp: "09:20",
          expectedDurationMin: 44,
          actualOrPredictedDurationMin: 42,
          note: "All 4 Jet A-1 certified arms pumping at calibrated 2,100 L/min.",
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "10:55 AM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
      ],
      flowGuardAssessment: {
        summary: "Terminal operation is completely nominal. Jet A-1 manifold line pressure optimal.",
        confidencePct: 96,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 0,
        protectedKes: 0,
      },
      communicationStatus: {
        notified: false,
        acknowledged: false,
      },
    },
    {
      id: "LO-NBO-8799",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KCA 331M",
      transporterName: "Nairobi Logistics Services",
      driverName: "Peter Omondi (ID: 26019844)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 28000,
      compartmentsCount: 3,
      currentStage: "GATE_OUT",
      currentStageLabel: "Ready for Exit / Gross Weighing",
      status: "READY FOR EXIT",
      orderPlacementTime: "07:00",
      expectedArrival: "07:45",
      gateInTime: "07:50",
      predictedGateOut: "10:20 AM",
      gateOutConfidencePct: 98,
      predictedTurnaroundMin: 50,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 2,
      riskSeverity: "NOMINAL",
      lastUpdate: "12 min ago",
      assignedBay: "Bay P02",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "07:00",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 10,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "COMPLETED",
          timestamp: "07:50",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "COMPLETED",
          timestamp: "08:10",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 15,
          customsReleaseStatus: "RELEASED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "COMPLETED",
          timestamp: "08:30",
          expectedDurationMin: 35,
          actualOrPredictedDurationMin: 36,
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "ACTIVE",
          timestamp: "09:40",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 12,
          note: "Gross tare confirmed 38.2 tonnes. Security seals attached.",
        },
      ],
      flowGuardAssessment: {
        summary: "Process concluded on schedule. Vehicle moving through exit boom gate.",
        confidencePct: 98,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 0,
        protectedKes: 0,
      },
      communicationStatus: {
        notified: false,
        acknowledged: false,
      },
    },
    {
      id: "LO-KSM-0922",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KCJ 884P",
      transporterName: "Victoria Freight Ltd",
      driverName: "Bernard Otieno (ID: 22108741)",
      depotId: "kisumu",
      depotName: "Kisumu Depot (PS28)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 32000,
      compartmentsCount: 3,
      currentStage: "GATE_OUT",
      currentStageLabel: "Completed & Gated Out",
      status: "COMPLETED",
      orderPlacementTime: "06:30",
      expectedArrival: "07:15",
      gateInTime: "07:22",
      predictedGateOut: "09:40 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 46,
      baselineTurnaroundMin: 50,
      turnaroundDeltaMin: -4,
      riskSeverity: "NOMINAL",
      lastUpdate: "18 min ago",
      assignedBay: "Bay P03",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "06:30",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 8,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "COMPLETED",
          timestamp: "07:22",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 12,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "COMPLETED",
          timestamp: "07:40",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 14,
          customsReleaseStatus: "RELEASED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "COMPLETED",
          timestamp: "08:00",
          expectedDurationMin: 45,
          actualOrPredictedDurationMin: 42,
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "COMPLETED",
          timestamp: "09:40",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 12,
          note: "Gated out successfully. Verified turnaround 46 min.",
        },
      ],
      flowGuardAssessment: {
        summary: "Turnaround completed 4 minutes faster than regional benchmark. Zero delays.",
        confidencePct: 100,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 0,
        protectedKes: 0,
        realizedKes: 80000,
      },
      communicationStatus: {
        notified: true,
        acknowledged: true,
        notifiedAt: "09:42",
        acknowledgedAt: "09:45",
      },
    },
    {
      id: "LO-NBO-8834",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KCT 119B",
      transporterName: "Trans-Rift Hauliers Ltd",
      driverName: "Francis Mutua (ID: 29011822)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "08:45",
      expectedArrival: "10:15",
      predictedGateOut: "12:15 PM",
      gateOutConfidencePct: 91,
      predictedTurnaroundMin: 52,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 4,
      riskSeverity: "NOMINAL",
      lastUpdate: "15 min ago",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "08:45",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 8,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "PREDICTED",
          timestamp: "10:15 AM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "PREDICTED",
          timestamp: "10:35 AM",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 15,
          customsReleaseStatus: "PRE_CLEARED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "PREDICTED",
          timestamp: "10:55 AM",
          expectedDurationMin: 35,
          actualOrPredictedDurationMin: 35,
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "12:15 PM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 15,
        },
      ],
      flowGuardAssessment: {
        summary: "Order confirmed in ERP. Scheduled arrival coincides with normalized gantry window.",
        confidencePct: 91,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 0,
        protectedKes: 0,
      },
      communicationStatus: {
        notified: false,
        acknowledged: false,
      },
    },
    {
      id: "LO-NKR-4429",
      omcId: "vivo",
      omcName: "Vivo Energy Kenya Ltd",
      truckRegistration: "KDH 602R",
      transporterName: "Rift Valley Petroleum Fleet",
      driverName: "Joseph Koech (ID: 25488102)",
      depotId: "nakuru",
      depotName: "Nakuru Depot (PS25)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "09:00",
      expectedArrival: "10:40",
      predictedGateOut: "12:35 PM",
      gateOutConfidencePct: 89,
      predictedTurnaroundMin: 55,
      baselineTurnaroundMin: 58,
      turnaroundDeltaMin: -3,
      riskSeverity: "NOMINAL",
      lastUpdate: "20 min ago",
      journey: [
        {
          stageId: "ORDER_PLACED",
          stageName: "Order Registered",
          status: "COMPLETED",
          timestamp: "09:00",
          expectedDurationMin: 10,
          actualOrPredictedDurationMin: 9,
        },
        {
          stageId: "GATE_IN",
          stageName: "Arrival / Gate-In",
          status: "PREDICTED",
          timestamp: "10:40 AM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
        {
          stageId: "VALIDATION_RELEASE",
          stageName: "Validation / Release",
          status: "PREDICTED",
          timestamp: "11:00 AM",
          expectedDurationMin: 16,
          actualOrPredictedDurationMin: 15,
          customsReleaseStatus: "PRE_CLEARED",
        },
        {
          stageId: "GANTRY_LOADING",
          stageName: "Gantry Loading",
          status: "PREDICTED",
          timestamp: "11:20 AM",
          expectedDurationMin: 32,
          actualOrPredictedDurationMin: 32,
        },
        {
          stageId: "GATE_OUT",
          stageName: "Gate-Out",
          status: "PREDICTED",
          timestamp: "12:35 PM",
          expectedDurationMin: 15,
          actualOrPredictedDurationMin: 14,
        },
      ],
      flowGuardAssessment: {
        summary: "Arrival window targets cleared Bay P01 slot post-meter maintenance.",
        confidencePct: 89,
        modelVersion: "FG-LSTM-v4.2 (Simulated)",
      },
      exposure: {
        potentialKes: 0,
        protectedKes: 0,
      },
      communicationStatus: {
        notified: false,
        acknowledged: false,
      },
    },
  ],

  // TotalEnergies Marketing Kenya
  totalenergies: [
    {
      id: "LO-MBA-5510",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KCE 902Y",
      transporterName: "Mombasa Heavy Logistics",
      driverName: "Abdi Mohammed (ID: 21088499)",
      depotId: "mombasa",
      depotName: "Mombasa Terminal (KOT/PS1)",
      product: "PMS (Super Petrol)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P02",
      status: "LOADING",
      orderPlacementTime: "07:30",
      expectedArrival: "08:15",
      gateInTime: "08:25",
      predictedGateOut: "10:35 AM",
      gateOutConfidencePct: 95,
      predictedTurnaroundMin: 50,
      baselineTurnaroundMin: 55,
      turnaroundDeltaMin: -5,
      riskSeverity: "NOMINAL",
      lastUpdate: "5 min ago",
      assignedBay: "Bay P02",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:30", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:25", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "08:45", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "09:05", expectedDurationMin: 44, actualOrPredictedDurationMin: 40 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "10:35 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Loading progressing ahead of baseline at KOT manifold.", confidencePct: 95, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-5522",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KDG 114F",
      transporterName: "Express Tankers Kenya",
      driverName: "Samuel Kamau (ID: 27104921)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Clearance",
      status: "DEVELOPING RISK",
      orderPlacementTime: "08:00",
      expectedArrival: "09:00",
      gateInTime: "09:12",
      predictedGateOut: "11:55 AM",
      gateOutConfidencePct: 89,
      predictedTurnaroundMin: 72,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 24,
      riskSeverity: "ELEVATED",
      lastUpdate: "8 min ago",
      assignedBay: "Bay P03",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:00", expectedDurationMin: 10, actualOrPredictedDurationMin: 10 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "09:12", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "ACTIVE", timestamp: "09:30", expectedDurationMin: 16, actualOrPredictedDurationMin: 24, customsReleaseStatus: "INSPECTION_HOLD" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "10:15 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 38 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:55 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      whyAtRisk: {
        headline: "Nairobi Morning Gantry Congestion & Customs Queue",
        causeSummary: "Gantry capacity pressure combined with secondary customs seal check.",
        causalContributions: [
          { factor: "Gantry Capacity", detail: "Nairobi terminal capacity ratio 125%", impactLevel: "High" },
          { factor: "Customs Verification", detail: "Electronic transponder check latency", impactLevel: "Medium" },
        ],
      },
      flowGuardAssessment: { summary: "Predicted turnaround +24 min. FlowGuard has scheduled priority slot on Bay P03 at 10:15 AM.", confidencePct: 89, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 310000, protectedKes: 210000 },
      communicationStatus: { notified: true, acknowledged: false, notifiedAt: "09:35" },
    },
    {
      id: "LO-KSM-5531",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KCF 440W",
      transporterName: "Western Hauliers Ltd",
      driverName: "Victor Onyango (ID: 23901147)",
      depotId: "kisumu",
      depotName: "Kisumu Depot (PS28)",
      product: "IK (Illuminating Kerosene)",
      quantityLitres: 28000,
      compartmentsCount: 2,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P01",
      status: "LOADING",
      orderPlacementTime: "07:50",
      expectedArrival: "08:40",
      gateInTime: "08:52",
      predictedGateOut: "10:45 AM",
      gateOutConfidencePct: 94,
      predictedTurnaroundMin: 48,
      baselineTurnaroundMin: 50,
      turnaroundDeltaMin: -2,
      riskSeverity: "NOMINAL",
      lastUpdate: "10 min ago",
      assignedBay: "Bay P01",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:50", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:52", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "09:08", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "09:25", expectedDurationMin: 45, actualOrPredictedDurationMin: 42 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "10:45 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Kisumu terminal turnaround tracking within normal SLA parameters.", confidencePct: 94, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-MBA-5544",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KBX 812T",
      transporterName: "Mombasa Heavy Logistics",
      driverName: "Omar Said (ID: 18990142)",
      depotId: "mombasa",
      depotName: "Mombasa Terminal (KOT/PS1)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GATE_OUT",
      currentStageLabel: "Gated Out Successfully",
      status: "COMPLETED",
      orderPlacementTime: "06:45",
      expectedArrival: "07:30",
      gateInTime: "07:38",
      predictedGateOut: "09:30 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 52,
      baselineTurnaroundMin: 55,
      turnaroundDeltaMin: -3,
      riskSeverity: "NOMINAL",
      lastUpdate: "35 min ago",
      assignedBay: "Bay P03",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "06:45", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "07:38", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "07:55", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "COMPLETED", timestamp: "08:15", expectedDurationMin: 44, actualOrPredictedDurationMin: 42 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "COMPLETED", timestamp: "09:30", expectedDurationMin: 15, actualOrPredictedDurationMin: 13 },
      ],
      flowGuardAssessment: { summary: "Complete. Loading completed with zero queue friction.", confidencePct: 100, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-5556",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KCU 509D",
      transporterName: "Express Tankers Kenya",
      driverName: "Geoffrey Maina (ID: 25901133)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "08:50",
      expectedArrival: "10:30",
      predictedGateOut: "12:20 PM",
      gateOutConfidencePct: 92,
      predictedTurnaroundMin: 50,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 2,
      riskSeverity: "NOMINAL",
      lastUpdate: "14 min ago",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:50", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "PREDICTED", timestamp: "10:30 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "10:50 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "11:10 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:20 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      flowGuardAssessment: { summary: "Scheduled arrival slot confirmed within normal operational bounds.", confidencePct: 92, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-ELD-5568",
      omcId: "totalenergies",
      omcName: "TotalEnergies Marketing Kenya Plc",
      truckRegistration: "KDA 890J",
      transporterName: "Western Hauliers Ltd",
      driverName: "Dennis Tanui (ID: 28990141)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "09:10",
      expectedArrival: "11:00",
      predictedGateOut: "12:55 PM",
      gateOutConfidencePct: 90,
      predictedTurnaroundMin: 58,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: -4,
      riskSeverity: "NOMINAL",
      lastUpdate: "22 min ago",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "09:10", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "PREDICTED", timestamp: "11:00 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "11:20 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "11:40 AM", expectedDurationMin: 38, actualOrPredictedDurationMin: 38 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:55 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Eldoret dispatch window tracking nominally.", confidencePct: 90, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
  ],

  // Rubis Energy Kenya
  rubis: [
    {
      id: "LO-NKR-7711",
      omcId: "rubis",
      omcName: "Rubis Energy Kenya Plc",
      truckRegistration: "KCY 401V",
      transporterName: "Rift Freight Services",
      driverName: "Paul Ndung'u (ID: 24108849)",
      depotId: "nakuru",
      depotName: "Nakuru Depot (PS25)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P01",
      status: "LOADING",
      orderPlacementTime: "07:40",
      expectedArrival: "08:20",
      gateInTime: "08:35",
      predictedGateOut: "11:15 AM",
      gateOutConfidencePct: 90,
      predictedTurnaroundMin: 68,
      baselineTurnaroundMin: 58,
      turnaroundDeltaMin: 10,
      riskSeverity: "ELEVATED",
      lastUpdate: "6 min ago",
      assignedBay: "Bay P01",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:40", expectedDurationMin: 10, actualOrPredictedDurationMin: 10 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:35", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "08:55", expectedDurationMin: 16, actualOrPredictedDurationMin: 16, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "09:15", expectedDurationMin: 32, actualOrPredictedDurationMin: 34 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:15 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      whyAtRisk: {
        headline: "Nakuru Secondary Bay Queue Congestion",
        causeSummary: "Flow slowed due to gantry capacity constraint on adjacent bay.",
        causalContributions: [
          { factor: "Depot Capacity", detail: "3 of 4 gantries usable", impactLevel: "Medium" },
        ],
      },
      flowGuardAssessment: { summary: "Loaded on Bay P01. Projected gate-out 11:15 AM.", confidencePct: 90, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 180000, protectedKes: 120000 },
      communicationStatus: { notified: true, acknowledged: true, notifiedAt: "08:45", acknowledgedAt: "08:50" },
    },
    {
      id: "LO-NBO-7724",
      omcId: "rubis",
      omcName: "Rubis Energy Kenya Plc",
      truckRegistration: "KDE 110L",
      transporterName: "Prime Movers Ltd",
      driverName: "Moses Kilonzo (ID: 26119842)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "GATE_IN",
      currentStageLabel: "Tare Scale Gate-In",
      status: "DEVELOPING RISK",
      orderPlacementTime: "08:15",
      expectedArrival: "09:10",
      gateInTime: "09:30",
      predictedGateOut: "12:05 PM",
      gateOutConfidencePct: 88,
      predictedTurnaroundMin: 70,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 22,
      riskSeverity: "ELEVATED",
      lastUpdate: "4 min ago",
      assignedBay: "Bay P04",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:15", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "ACTIVE", timestamp: "09:30", expectedDurationMin: 15, actualOrPredictedDurationMin: 20 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "09:55 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 16, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "10:20 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:05 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      whyAtRisk: {
        headline: "Nairobi Gantry Demand Surge Queue",
        causeSummary: "Nairobi terminal capacity ratio exceeds 120% in morning window.",
        causalContributions: [{ factor: "Demand Pressure", detail: "High tanker arrival density", impactLevel: "High" }],
      },
      flowGuardAssessment: { summary: "Turnaround delay projected. Priority re-sequencing applied by FlowGuard.", confidencePct: 88, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 260000, protectedKes: 180000 },
      communicationStatus: { notified: true, acknowledged: false, notifiedAt: "09:35" },
    },
    {
      id: "LO-ELD-7733",
      omcId: "rubis",
      omcName: "Rubis Energy Kenya Plc",
      truckRegistration: "KCB 992P",
      transporterName: "Rift Freight Services",
      driverName: "Elijah Korir (ID: 23118940)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Validation",
      status: "ON TRACK",
      orderPlacementTime: "07:55",
      expectedArrival: "08:45",
      gateInTime: "08:58",
      predictedGateOut: "11:20 AM",
      gateOutConfidencePct: 93,
      predictedTurnaroundMin: 58,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: -4,
      riskSeverity: "NOMINAL",
      lastUpdate: "11 min ago",
      assignedBay: "Bay P02",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:55", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:58", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "ACTIVE", timestamp: "09:15", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "09:35 AM", expectedDurationMin: 38, actualOrPredictedDurationMin: 38 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:20 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Validation proceeding normally at Eldoret.", confidencePct: 93, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NKR-7745",
      omcId: "rubis",
      omcName: "Rubis Energy Kenya Plc",
      truckRegistration: "KDA 119M",
      transporterName: "Rift Freight Services",
      driverName: "Harrison Mwangi (ID: 27991024)",
      depotId: "nakuru",
      depotName: "Nakuru Depot (PS25)",
      product: "PMS (Super Petrol)",
      quantityLitres: 28000,
      compartmentsCount: 2,
      currentStage: "GATE_OUT",
      currentStageLabel: "Completed Collection",
      status: "COMPLETED",
      orderPlacementTime: "06:15",
      expectedArrival: "07:00",
      gateInTime: "07:12",
      predictedGateOut: "09:10 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 54,
      baselineTurnaroundMin: 58,
      turnaroundDeltaMin: -4,
      riskSeverity: "NOMINAL",
      lastUpdate: "45 min ago",
      assignedBay: "Bay P01",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "06:15", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "07:12", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "07:30", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "COMPLETED", timestamp: "07:50", expectedDurationMin: 32, actualOrPredictedDurationMin: 30 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "COMPLETED", timestamp: "09:10", expectedDurationMin: 15, actualOrPredictedDurationMin: 13 },
      ],
      flowGuardAssessment: { summary: "Complete. Turnaround 4 min faster than baseline.", confidencePct: 100, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-7758",
      omcId: "rubis",
      omcName: "Rubis Energy Kenya Plc",
      truckRegistration: "KDF 330G",
      transporterName: "Prime Movers Ltd",
      driverName: "Anthony Njoroge (ID: 29810411)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "09:05",
      expectedArrival: "10:45",
      predictedGateOut: "12:40 PM",
      gateOutConfidencePct: 91,
      predictedTurnaroundMin: 51,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 3,
      riskSeverity: "NOMINAL",
      lastUpdate: "18 min ago",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "09:05", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "PREDICTED", timestamp: "10:45 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "11:05 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "11:25 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:40 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      flowGuardAssessment: { summary: "Scheduled arrival slot matches anticipated post-surge turnaround.", confidencePct: 91, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
  ],

  // Lake Oil Kenya
  lakeoil: [
    {
      id: "LO-ELD-8801",
      omcId: "lakeoil",
      omcName: "Lake Oil Kenya Ltd",
      truckRegistration: "KDC 712U",
      transporterName: "Lake Transporters Co",
      driverName: "Abdullahi Juma (ID: 22891044)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P03",
      status: "LOADING",
      orderPlacementTime: "07:50",
      expectedArrival: "08:35",
      gateInTime: "08:48",
      predictedGateOut: "11:05 AM",
      gateOutConfidencePct: 92,
      predictedTurnaroundMin: 60,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: -2,
      riskSeverity: "NOMINAL",
      lastUpdate: "7 min ago",
      assignedBay: "Bay P03",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:50", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:48", expectedDurationMin: 15, actualOrPredictedDurationMin: 13 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "09:05", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "09:25", expectedDurationMin: 38, actualOrPredictedDurationMin: 36 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:05 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Eldoret collection proceeding normally.", confidencePct: 92, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-8815",
      omcId: "lakeoil",
      omcName: "Lake Oil Kenya Ltd",
      truckRegistration: "KDB 449A",
      transporterName: "Lake Transporters Co",
      driverName: "Boniface Mutisya (ID: 25901198)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Clearance",
      status: "DEVELOPING RISK",
      orderPlacementTime: "08:10",
      expectedArrival: "09:05",
      gateInTime: "09:20",
      predictedGateOut: "11:50 AM",
      gateOutConfidencePct: 89,
      predictedTurnaroundMin: 68,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 20,
      riskSeverity: "ELEVATED",
      lastUpdate: "9 min ago",
      assignedBay: "Bay P05",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:10", expectedDurationMin: 10, actualOrPredictedDurationMin: 10 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "09:20", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "ACTIVE", timestamp: "09:40", expectedDurationMin: 16, actualOrPredictedDurationMin: 20, customsReleaseStatus: "INSPECTION_HOLD" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "10:15 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:50 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      whyAtRisk: { headline: "Nairobi Morning Gantry Congestion", causeSummary: "Nairobi peak inflow creating gantry queue.", causalContributions: [{ factor: "Gantry Demand", detail: "Cluster of 6 AGO/PMS tankers", impactLevel: "High" }] },
      flowGuardAssessment: { summary: "FlowGuard adjusted sequence priority to minimize dwell.", confidencePct: 89, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 240000, protectedKes: 170000 },
      communicationStatus: { notified: true, acknowledged: false, notifiedAt: "09:42" },
    },
    {
      id: "LO-KSM-8829",
      omcId: "lakeoil",
      omcName: "Lake Oil Kenya Ltd",
      truckRegistration: "KCA 990H",
      transporterName: "Lake Transporters Co",
      driverName: "Titus Oloo (ID: 21908411)",
      depotId: "kisumu",
      depotName: "Kisumu Depot (PS28)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 32000,
      compartmentsCount: 3,
      currentStage: "GATE_OUT",
      currentStageLabel: "Completed Collection",
      status: "COMPLETED",
      orderPlacementTime: "06:40",
      expectedArrival: "07:25",
      gateInTime: "07:35",
      predictedGateOut: "09:25 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 48,
      baselineTurnaroundMin: 50,
      turnaroundDeltaMin: -2,
      riskSeverity: "NOMINAL",
      lastUpdate: "40 min ago",
      assignedBay: "Bay P02",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "06:40", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "07:35", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "07:50", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "COMPLETED", timestamp: "08:10", expectedDurationMin: 45, actualOrPredictedDurationMin: 42 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "COMPLETED", timestamp: "09:25", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
      ],
      flowGuardAssessment: { summary: "Complete. Turnaround 48m.", confidencePct: 100, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-ELD-8837",
      omcId: "lakeoil",
      omcName: "Lake Oil Kenya Ltd",
      truckRegistration: "KDD 190E",
      transporterName: "Lake Transporters Co",
      driverName: "Simon Kurgat (ID: 28901142)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "09:00",
      expectedArrival: "10:50",
      predictedGateOut: "12:45 PM",
      gateOutConfidencePct: 91,
      predictedTurnaroundMin: 59,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: -3,
      riskSeverity: "NOMINAL",
      lastUpdate: "16 min ago",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "09:00", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "PREDICTED", timestamp: "10:50 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "11:10 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "11:30 AM", expectedDurationMin: 38, actualOrPredictedDurationMin: 38 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:45 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Scheduled slot on track.", confidencePct: 91, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
  ],

  // Ola Energy Kenya
  ola: [
    {
      id: "LO-NBO-3310",
      omcId: "ola",
      omcName: "Ola Energy Kenya Ltd",
      truckRegistration: "KDB 802C",
      transporterName: "Nairobi Fuel Transporters",
      driverName: "Charles Kariuki (ID: 23890111)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P03",
      status: "LOADING",
      orderPlacementTime: "07:35",
      expectedArrival: "08:20",
      gateInTime: "08:32",
      predictedGateOut: "11:10 AM",
      gateOutConfidencePct: 92,
      predictedTurnaroundMin: 65,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 17,
      riskSeverity: "ELEVATED",
      lastUpdate: "5 min ago",
      assignedBay: "Bay P03",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:35", expectedDurationMin: 10, actualOrPredictedDurationMin: 10 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:32", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "08:50", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "09:10", expectedDurationMin: 35, actualOrPredictedDurationMin: 36 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:10 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      whyAtRisk: { headline: "Nairobi Terminal Morning Peak", causeSummary: "High gantry utilization slowing turnover.", causalContributions: [{ factor: "Demand Ratio", detail: "High morning arrival volume", impactLevel: "Medium" }] },
      flowGuardAssessment: { summary: "Predicted turnaround +17 min. Gantry flow actively monitored.", confidencePct: 92, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 210000, protectedKes: 140000 },
      communicationStatus: { notified: true, acknowledged: true, notifiedAt: "08:40", acknowledgedAt: "08:45" },
    },
    {
      id: "LO-MBA-3324",
      omcId: "ola",
      omcName: "Ola Energy Kenya Ltd",
      truckRegistration: "KCE 419P",
      transporterName: "Coast Express Hauliers",
      driverName: "Salim Baraka (ID: 20119842)",
      depotId: "mombasa",
      depotName: "Mombasa Terminal (KOT/PS1)",
      product: "PMS (Super Petrol)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Release Pre-Cleared",
      status: "ON TRACK",
      orderPlacementTime: "08:15",
      expectedArrival: "09:00",
      gateInTime: "09:10",
      predictedGateOut: "11:15 AM",
      gateOutConfidencePct: 95,
      predictedTurnaroundMin: 53,
      baselineTurnaroundMin: 55,
      turnaroundDeltaMin: -2,
      riskSeverity: "NOMINAL",
      lastUpdate: "8 min ago",
      assignedBay: "Bay P04",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:15", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "09:10", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "ACTIVE", timestamp: "09:28", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "09:50 AM", expectedDurationMin: 44, actualOrPredictedDurationMin: 42 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:15 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Mombasa operations completely nominal.", confidencePct: 95, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NKR-3338",
      omcId: "ola",
      omcName: "Ola Energy Kenya Ltd",
      truckRegistration: "KDA 770B",
      transporterName: "Rift Freight Services",
      driverName: "Dominic Ngetich (ID: 26880144)",
      depotId: "nakuru",
      depotName: "Nakuru Depot (PS25)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "GATE_OUT",
      currentStageLabel: "Completed Collection",
      status: "COMPLETED",
      orderPlacementTime: "06:20",
      expectedArrival: "07:05",
      gateInTime: "07:18",
      predictedGateOut: "09:15 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 55,
      baselineTurnaroundMin: 58,
      turnaroundDeltaMin: -3,
      riskSeverity: "NOMINAL",
      lastUpdate: "38 min ago",
      assignedBay: "Bay P03",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "06:20", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "07:18", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "07:35", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "COMPLETED", timestamp: "07:55", expectedDurationMin: 32, actualOrPredictedDurationMin: 31 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "COMPLETED", timestamp: "09:15", expectedDurationMin: 15, actualOrPredictedDurationMin: 13 },
      ],
      flowGuardAssessment: { summary: "Complete. Turnaround 55m.", confidencePct: 100, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-3349",
      omcId: "ola",
      omcName: "Ola Energy Kenya Ltd",
      truckRegistration: "KCF 112S",
      transporterName: "Nairobi Fuel Transporters",
      driverName: "Alex Waweru (ID: 27109844)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 28000,
      compartmentsCount: 2,
      currentStage: "ORDER_PLACED",
      currentStageLabel: "En Route to Gate-In",
      status: "ON TRACK",
      orderPlacementTime: "09:15",
      expectedArrival: "11:00",
      predictedGateOut: "12:50 PM",
      gateOutConfidencePct: 90,
      predictedTurnaroundMin: 49,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 1,
      riskSeverity: "NOMINAL",
      lastUpdate: "20 min ago",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "09:15", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "PREDICTED", timestamp: "11:00 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "PREDICTED", timestamp: "11:20 AM", expectedDurationMin: 16, actualOrPredictedDurationMin: 15, customsReleaseStatus: "PRE_CLEARED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "11:40 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "12:50 PM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Scheduled arrival slot matches anticipated post-surge turnaround.", confidencePct: 90, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
  ],

  // Hass Petroleum
  hass: [
    {
      id: "LO-KSM-9912",
      omcId: "hass",
      omcName: "Hass Petroleum Kenya Ltd",
      truckRegistration: "KCH 551R",
      transporterName: "Hass Regional Logistics",
      driverName: "Erick Ouma (ID: 23091184)",
      depotId: "kisumu",
      depotName: "Kisumu Depot (PS28)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GANTRY_LOADING",
      currentStageLabel: "Loading on Bay P04",
      status: "LOADING",
      orderPlacementTime: "07:20",
      expectedArrival: "08:10",
      gateInTime: "08:22",
      predictedGateOut: "10:30 AM",
      gateOutConfidencePct: 94,
      predictedTurnaroundMin: 52,
      baselineTurnaroundMin: 50,
      turnaroundDeltaMin: 2,
      riskSeverity: "NOMINAL",
      lastUpdate: "6 min ago",
      assignedBay: "Bay P04",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "07:20", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "08:22", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "08:38", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "ACTIVE", timestamp: "08:58", expectedDurationMin: 45, actualOrPredictedDurationMin: 44 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "10:30 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 14 },
      ],
      flowGuardAssessment: { summary: "Steady loading progression at Kisumu PS28.", confidencePct: 94, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
    {
      id: "LO-NBO-9925",
      omcId: "hass",
      omcName: "Hass Petroleum Kenya Ltd",
      truckRegistration: "KDE 819K",
      transporterName: "Hass Regional Logistics",
      driverName: "Titus Macharia (ID: 25901188)",
      depotId: "nairobi",
      depotName: "Nairobi Terminal (PS10)",
      product: "PMS (Super Petrol)",
      quantityLitres: 36000,
      compartmentsCount: 3,
      currentStage: "VALIDATION_RELEASE",
      currentStageLabel: "Customs Hold / Documentation",
      status: "DEVELOPING RISK",
      orderPlacementTime: "08:05",
      expectedArrival: "09:00",
      gateInTime: "09:15",
      predictedGateOut: "11:58 AM",
      gateOutConfidencePct: 88,
      predictedTurnaroundMin: 72,
      baselineTurnaroundMin: 48,
      turnaroundDeltaMin: 24,
      riskSeverity: "ELEVATED",
      lastUpdate: "8 min ago",
      assignedBay: "Bay P02",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "08:05", expectedDurationMin: 10, actualOrPredictedDurationMin: 9 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "09:15", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "ACTIVE", timestamp: "09:35", expectedDurationMin: 16, actualOrPredictedDurationMin: 22, customsReleaseStatus: "INSPECTION_HOLD" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "PREDICTED", timestamp: "10:20 AM", expectedDurationMin: 35, actualOrPredictedDurationMin: 35 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "PREDICTED", timestamp: "11:58 AM", expectedDurationMin: 15, actualOrPredictedDurationMin: 15 },
      ],
      whyAtRisk: { headline: "Nairobi Terminal Congestion Hold", causeSummary: "Queue buildup at Smart Gate tare scale.", causalContributions: [{ factor: "Gate Queue", detail: "Multiple tankers arriving in 09:00 window", impactLevel: "Medium" }] },
      flowGuardAssessment: { summary: "Predicted turnaround +24 min above baseline. FlowGuard sequence slot active.", confidencePct: 88, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 250000, protectedKes: 160000 },
      communicationStatus: { notified: true, acknowledged: false, notifiedAt: "09:40" },
    },
    {
      id: "LO-ELD-9939",
      omcId: "hass",
      omcName: "Hass Petroleum Kenya Ltd",
      truckRegistration: "KDA 220X",
      transporterName: "Hass Regional Logistics",
      driverName: "Silas Rotich (ID: 27891044)",
      depotId: "eldoret",
      depotName: "Eldoret Depot (PS27)",
      product: "AGO (Automotive Gasoil)",
      quantityLitres: 40000,
      compartmentsCount: 4,
      currentStage: "GATE_OUT",
      currentStageLabel: "Completed Collection",
      status: "COMPLETED",
      orderPlacementTime: "06:30",
      expectedArrival: "07:15",
      gateInTime: "07:28",
      predictedGateOut: "09:20 AM (Confirmed)",
      gateOutConfidencePct: 100,
      predictedTurnaroundMin: 56,
      baselineTurnaroundMin: 62,
      turnaroundDeltaMin: -6,
      riskSeverity: "NOMINAL",
      lastUpdate: "48 min ago",
      assignedBay: "Bay P01",
      journey: [
        { stageId: "ORDER_PLACED", stageName: "Order Registered", status: "COMPLETED", timestamp: "06:30", expectedDurationMin: 10, actualOrPredictedDurationMin: 8 },
        { stageId: "GATE_IN", stageName: "Gate-In", status: "COMPLETED", timestamp: "07:28", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
        { stageId: "VALIDATION_RELEASE", stageName: "Validation", status: "COMPLETED", timestamp: "07:45", expectedDurationMin: 16, actualOrPredictedDurationMin: 14, customsReleaseStatus: "RELEASED" },
        { stageId: "GANTRY_LOADING", stageName: "Loading", status: "COMPLETED", timestamp: "08:05", expectedDurationMin: 38, actualOrPredictedDurationMin: 36 },
        { stageId: "GATE_OUT", stageName: "Gate-Out", status: "COMPLETED", timestamp: "09:20", expectedDurationMin: 15, actualOrPredictedDurationMin: 12 },
      ],
      flowGuardAssessment: { summary: "Complete. 6 min ahead of SLA.", confidencePct: 100, modelVersion: "FG-LSTM-v4.2" },
      exposure: { potentialKes: 0, protectedKes: 0 },
      communicationStatus: { notified: false, acknowledged: false },
    },
  ],
});

export const initAllOmcNotifications = (): Record<OmcId, OmcNotification[]> => ({
  vivo: [
    {
      id: "NOTIF-VIV-001",
      omcId: "vivo",
      orderId: "LO-NBO-8821",
      truckRegistration: "KDD 412X",
      depotName: "Nairobi Terminal (PS10)",
      type: "PREDICTION_UPDATE",
      title: "Predicted Gate-Out Improved (-22 min)",
      message: "Your estimated gate-out has moved from 11:24 AM to 11:02 AM following FlowGuard autonomous dual-arm allocation on Bay P01.",
      timestamp: "08:31 AM",
      severity: "success",
      requiresAcknowledgement: true,
      isAcknowledged: true,
      acknowledgedAt: "08:35 AM",
    },
    {
      id: "NOTIF-VIV-002",
      omcId: "vivo",
      orderId: "LO-NKR-4412",
      truckRegistration: "KDB 918Q",
      depotName: "Nakuru Depot (PS25)",
      type: "DELAY_WARNING",
      title: "Collection Processing Update",
      message: "Your Nakuru collection is experiencing increased processing time as loading performance at the depot is below normal. Current predicted gate-out: 12:12 PM. FlowGuard has scheduled a bay re-assignment to mitigate further delay.",
      timestamp: "09:46 AM",
      severity: "warning",
      requiresAcknowledgement: true,
      isAcknowledged: false,
    },
    {
      id: "NOTIF-VIV-003",
      omcId: "vivo",
      orderId: "LO-KSM-0922",
      truckRegistration: "KCJ 884P",
      depotName: "Kisumu Depot (PS28)",
      type: "COLLECTION_COMPLETED",
      title: "Collection Completed: KCJ 884P Gated Out",
      message: "Road tanker KCJ 884P successfully gated out of Kisumu at 09:40 AM. Total turnaround duration: 46 min (4 min ahead of baseline target).",
      timestamp: "09:42 AM",
      severity: "info",
      requiresAcknowledgement: false,
      isAcknowledged: true,
    },
    {
      id: "NOTIF-VIV-004",
      omcId: "vivo",
      orderId: "LO-ELD-3091",
      truckRegistration: "KDA 552L",
      depotName: "Eldoret Depot (PS27)",
      type: "CAPACITY_ADVISORY",
      title: "Eldoret Tare Scale Inflow Advisory",
      message: "Cluster arrival of 5 road tankers at Eldoret Smart Gate. Queue delay estimated at 14 min. Pre-assigned Bay P04 to avoid subsequent gantry delay.",
      timestamp: "09:50 AM",
      severity: "warning",
      requiresAcknowledgement: false,
      isAcknowledged: false,
    },
  ],
  totalenergies: [
    {
      id: "NOTIF-TOT-001",
      omcId: "totalenergies",
      orderId: "LO-NBO-5522",
      truckRegistration: "KDG 114F",
      depotName: "Nairobi Terminal (PS10)",
      type: "DELAY_WARNING",
      title: "Nairobi Gantry Capacity Advisory",
      message: "Nairobi terminal currently operating at 125% capacity ratio. Order LO-NBO-5522 turnaround projected at 72 min (+24 min above baseline).",
      timestamp: "09:35 AM",
      severity: "warning",
      requiresAcknowledgement: true,
      isAcknowledged: false,
    },
    {
      id: "NOTIF-TOT-002",
      omcId: "totalenergies",
      orderId: "LO-MBA-5544",
      truckRegistration: "KBX 812T",
      depotName: "Mombasa Terminal (KOT/PS1)",
      type: "COLLECTION_COMPLETED",
      title: "Collection Completed: KBX 812T Gated Out",
      message: "Tanker KBX 812T gated out at 09:30 AM with verified 52 min turnaround.",
      timestamp: "09:32 AM",
      severity: "info",
      requiresAcknowledgement: false,
      isAcknowledged: true,
    },
  ],
  rubis: [
    {
      id: "NOTIF-RUB-001",
      omcId: "rubis",
      orderId: "LO-NKR-7711",
      truckRegistration: "KCY 401V",
      depotName: "Nakuru Depot (PS25)",
      type: "PREDICTION_UPDATE",
      title: "Loading Progress Notice",
      message: "Tanker KCY 401V active on Bay P01. Projected gate-out 11:15 AM.",
      timestamp: "08:45 AM",
      severity: "info",
      requiresAcknowledgement: true,
      isAcknowledged: true,
      acknowledgedAt: "08:50 AM",
    },
    {
      id: "NOTIF-RUB-002",
      omcId: "rubis",
      orderId: "LO-NBO-7724",
      truckRegistration: "KDE 110L",
      depotName: "Nairobi Terminal (PS10)",
      type: "CAPACITY_ADVISORY",
      title: "Nairobi Morning Demand Surge",
      message: "High arrival density at Nairobi Smart Gate. FlowGuard has adjusted priority to protect against demurrage.",
      timestamp: "09:35 AM",
      severity: "warning",
      requiresAcknowledgement: false,
      isAcknowledged: false,
    },
  ],
  lakeoil: [
    {
      id: "NOTIF-LAK-001",
      omcId: "lakeoil",
      orderId: "LO-NBO-8815",
      truckRegistration: "KDB 449A",
      depotName: "Nairobi Terminal (PS10)",
      type: "DELAY_WARNING",
      title: "Nairobi Dispatch Notice",
      message: "Order LO-NBO-8815 undergoing KRA document reconciliation. Estimated gate-out 11:50 AM.",
      timestamp: "09:42 AM",
      severity: "warning",
      requiresAcknowledgement: false,
      isAcknowledged: false,
    },
  ],
  ola: [
    {
      id: "NOTIF-OLA-001",
      omcId: "ola",
      orderId: "LO-NBO-3310",
      truckRegistration: "KDB 802C",
      depotName: "Nairobi Terminal (PS10)",
      type: "CAPACITY_ADVISORY",
      title: "Nairobi Morning Peak Dispatch",
      message: "Order LO-NBO-3310 active on Bay P03. Predicted gate-out 11:10 AM.",
      timestamp: "08:40 AM",
      severity: "info",
      requiresAcknowledgement: true,
      isAcknowledged: true,
      acknowledgedAt: "08:45 AM",
    },
  ],
  hass: [
    {
      id: "NOTIF-HAS-001",
      omcId: "hass",
      orderId: "LO-NBO-9925",
      truckRegistration: "KDE 819K",
      depotName: "Nairobi Terminal (PS10)",
      type: "DELAY_WARNING",
      title: "Nairobi Gate Queue Hold",
      message: "Tare scale queue buildup at Nairobi. FlowGuard sequence slot active.",
      timestamp: "09:40 AM",
      severity: "warning",
      requiresAcknowledgement: false,
      isAcknowledged: false,
    },
  ],
});

export const initAllOmcOutlooks = (): Record<OmcId, OmcHourlyOutlook[]> => ({
  vivo: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 4,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Normal turnaround ~48m",
      note: "Eldoret & Kisumu terminals operating with optimal throughput.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 7,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Capacity pressure ~76m (+18m)",
      note: "Nairobi & Nakuru experiencing morning dispatch pressure. Interventions active.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 5,
      congestionLevel: "STABILIZING",
      turnaroundCondition: "Stabilizing flow ~54m",
      note: "Queue clearing across gantries post-FlowGuard dual-arm allocations.",
    },
    {
      timeWindow: "12:00–13:00",
      expectedOrdersCount: 3,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Nominal SLA ~46m",
      note: "Midday dispatch return to baseline SLA turnaround times.",
    },
  ],
  totalenergies: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 3,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Normal turnaround ~50m",
      note: "Mombasa KOT loading nominal; all jet fuel arms operating at full rate.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 5,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Elevated dwell ~72m (+14m)",
      note: "Nairobi central terminal queue elevated.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 4,
      congestionLevel: "STABILIZING",
      turnaroundCondition: "Stabilizing ~52m",
      note: "Kisumu and Mombasa dispatches tracking ahead of SLA.",
    },
  ],
  rubis: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 2,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Capacity constrained ~78m",
      note: "Nakuru loading performance below normal impacting PMS orders.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 4,
      congestionLevel: "STABILIZING",
      turnaroundCondition: "Stabilizing flow ~60m",
      note: "Bay divert interventions active; turnaround recovery in progress.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 3,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Baseline SLA ~58m",
      note: "Expected return to standard 58-minute turnaround.",
    },
  ],
  lakeoil: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 2,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Normal turnaround ~45m",
      note: "Eldoret dispatch gate operating normally.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 3,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Peak dwell ~68m (+12m)",
      note: "Nairobi orders facing morning peak dwell.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 2,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Nominal flow ~47m",
      note: "Normalized regional collections.",
    },
  ],
  ola: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 2,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Normal turnaround ~48m",
      note: "Mombasa terminal nominal.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 3,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Queue pressure ~70m",
      note: "Nairobi morning gantry queue.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 2,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Nominal turnaround ~50m",
      note: "Stabilized flow across terminals.",
    },
  ],
  hass: [
    {
      timeWindow: "09:00–10:00",
      expectedOrdersCount: 1,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Normal turnaround ~44m",
      note: "Kisumu terminal nominal.",
    },
    {
      timeWindow: "10:00–11:00",
      expectedOrdersCount: 2,
      congestionLevel: "CAPACITY_PRESSURE",
      turnaroundCondition: "Scale queue ~65m",
      note: "Nairobi tare scale clustering.",
    },
    {
      timeWindow: "11:00–12:00",
      expectedOrdersCount: 1,
      congestionLevel: "NORMAL",
      turnaroundCondition: "Nominal turnaround ~45m",
      note: "Normal afternoon collection.",
    },
  ],
});

export const calculateOmcKpiSummary = (
  omcId: OmcId,
  orders: OmcCollectionOrder[]
): OmcKpiSummary => {
  const activeOrders = orders.filter((o) => o.status !== "COMPLETED");
  const inProcess = orders.filter(
    (o) =>
      o.currentStage === "GATE_IN" ||
      o.currentStage === "VALIDATION_RELEASE" ||
      o.currentStage === "GANTRY_LOADING"
  );
  const atRisk = orders.filter(
    (o) => o.status === "AT RISK" || o.status === "DEVELOPING RISK" || o.status === "DELAYED"
  );

  const totalPredictedTurnaround = orders.reduce((acc, o) => acc + o.predictedTurnaroundMin, 0);
  const totalBaselineTurnaround = orders.reduce((acc, o) => acc + o.baselineTurnaroundMin, 0);
  const avgPredicted = orders.length > 0 ? Math.round(totalPredictedTurnaround / orders.length) : 55;
  const avgBaseline = orders.length > 0 ? Math.round(totalBaselineTurnaround / orders.length) : 52;

  const exposureAtRisk = orders.reduce((acc, o) => acc + (o.exposure?.potentialKes || 0), 0);
  const exposureProtected = orders.reduce((acc, o) => acc + (o.exposure?.protectedKes || 0), 0);
  const realizedSavings = orders.reduce((acc, o) => acc + (o.exposure?.realizedKes || 0), 0);

  const confirmedCompleted = orders.filter((o) => o.status === "COMPLETED").length;
  // Confirmed actual gate-outs completed today vs predicted remaining collections
  const completedCount = confirmedCompleted > 0 ? confirmedCompleted : 6;
  const remainingCount = Math.max(activeOrders.length, 3);

  return {
    activeOrdersCount: orders.length,
    trucksInKpcProcess: inProcess.length,
    atRiskCount: atRisk.length,
    predictedAvgTurnaroundMin: avgPredicted,
    baselineAvgTurnaroundMin: avgBaseline,
    turnaroundDeltaMin: avgPredicted - avgBaseline,
    gateOutsCompletedToday: completedCount,
    expectedGateOutsRemaining: remainingCount,
    expectedGateOutsToday: completedCount + remainingCount,
    exposureAtRiskKes: exposureAtRisk,
    exposureProtectedKes: exposureProtected,
    realizedSavingsKes: realizedSavings,
  };
};
