"""initial_canonical_schema

Revision ID: 144f9fbd2d79
Revises: 
Create Date: 2026-09-15 16:51:20.660290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144f9fbd2d79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('baseline_turnaround_min', sa.Integer(), nullable=False),
    sa.Column('operating_hours_open', sa.String(length=16), nullable=False),
    sa.Column('operating_hours_close', sa.String(length=16), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('depot_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_depots_etl_run_id'), 'depots', ['etl_run_id'], unique=False)
    op.create_table('etl_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('rows_quarantined', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('density_kg_per_l', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('standard_flow_rate_lpm', sa.Integer(), nullable=False),
    sa.Column('is_hazardous_priority', sa.Boolean(), nullable=False),
    sa.Column('compatible_bays_desc', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_products_etl_run_id'), 'products', ['etl_run_id'], unique=False)
    op.create_table('trucks',
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('registration', sa.String(length=32), nullable=False),
    sa.Column('trailer_registration', sa.String(length=32), nullable=False),
    sa.Column('transporter_name', sa.String(length=128), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('driver_national_id', sa.String(length=32), nullable=False),
    sa.Column('capacity_litres', sa.Integer(), nullable=False),
    sa.Column('compartments_count', sa.Integer(), nullable=False),
    sa.Column('tare_weight_kg', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('active_status', sa.String(length=32), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('truck_id')
    )
    op.create_index('ix_trucks_active_status', 'trucks', ['active_status'], unique=False)
    op.create_index(op.f('ix_trucks_etl_run_id'), 'trucks', ['etl_run_id'], unique=False)
    op.create_index(op.f('ix_trucks_registration'), 'trucks', ['registration'], unique=True)
    op.create_index('ix_trucks_transporter', 'trucks', ['transporter_name'], unique=False)
    op.create_table('loading_positions',
    sa.Column('loading_position_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('bay_number', sa.Integer(), nullable=False),
    sa.Column('product_compatibility', sa.String(length=128), nullable=False),
    sa.Column('has_dual_arm', sa.Boolean(), nullable=False),
    sa.Column('standard_flow_rate_lpm', sa.Integer(), nullable=False),
    sa.Column('is_high_velocity', sa.Boolean(), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.PrimaryKeyConstraint('loading_position_id')
    )
    op.create_index('ix_loading_positions_bay_number', 'loading_positions', ['depot_id', 'bay_number'], unique=False)
    op.create_index('ix_loading_positions_depot_id', 'loading_positions', ['depot_id'], unique=False)
    op.create_index(op.f('ix_loading_positions_etl_run_id'), 'loading_positions', ['etl_run_id'], unique=False)
    op.create_table('omcs',
    sa.Column('omc_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('primary_depot_id', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=128), nullable=False),
    sa.Column('volume_tier', sa.String(length=32), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_depot_id'], ['depots.depot_id'], ),
    sa.PrimaryKeyConstraint('omc_id'),
    sa.UniqueConstraint('account_code')
    )
    op.create_index(op.f('ix_omcs_etl_run_id'), 'omcs', ['etl_run_id'], unique=False)
    op.create_index('ix_omcs_primary_depot_id', 'omcs', ['primary_depot_id'], unique=False)
    op.create_index('ix_omcs_volume_tier', 'omcs', ['volume_tier'], unique=False)
    op.create_table('product_readiness_events',
    sa.Column('readiness_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=16), nullable=False),
    sa.Column('tank_id', sa.String(length=32), nullable=False),
    sa.Column('readiness_status', sa.String(length=32), nullable=False),
    sa.Column('certified_volume_litres', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('constraint_reason', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('readiness_id')
    )
    op.create_index(op.f('ix_product_readiness_events_etl_run_id'), 'product_readiness_events', ['etl_run_id'], unique=False)
    op.create_index('ix_readiness_depot_product', 'product_readiness_events', ['depot_id', 'product_id'], unique=False)
    op.create_index('ix_readiness_status', 'product_readiness_events', ['readiness_status'], unique=False)
    op.create_index('ix_readiness_timestamp', 'product_readiness_events', ['depot_id', 'event_timestamp'], unique=False)
    op.create_table('quarantine_records',
    sa.Column('quarantine_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('source_row_id', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('validation_rule', sa.String(length=128), nullable=False),
    sa.Column('raw_record', sa.Text(), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['etl_runs.run_id'], ),
    sa.PrimaryKeyConstraint('quarantine_id')
    )
    op.create_index('ix_quarantine_rule', 'quarantine_records', ['validation_rule'], unique=False)
    op.create_index('ix_quarantine_run_table', 'quarantine_records', ['run_id', 'source_table'], unique=False)
    op.create_table('risk_events',
    sa.Column('risk_event_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('predicted_turnaround_min', sa.Integer(), nullable=False),
    sa.Column('baseline_turnaround_min', sa.Integer(), nullable=False),
    sa.Column('dwell_delta_min', sa.Integer(), nullable=False),
    sa.Column('exposure_at_risk_kes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('primary_root_cause', sa.String(length=255), nullable=False),
    sa.Column('affected_orders_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.PrimaryKeyConstraint('risk_event_id')
    )
    op.create_index('ix_active_risks_partial', 'risk_events', ['depot_id', 'detected_at'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_risk_events_depot_status_time', 'risk_events', ['depot_id', 'status', 'detected_at'], unique=False)
    op.create_index(op.f('ix_risk_events_etl_run_id'), 'risk_events', ['etl_run_id'], unique=False)
    op.create_index('ix_risk_events_severity', 'risk_events', ['severity'], unique=False)
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('risk_event_id', sa.String(length=32), nullable=True),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('autonomy_level', sa.String(length=32), nullable=False),
    sa.Column('decision_status', sa.String(length=32), nullable=False),
    sa.Column('selected_candidate_id', sa.String(length=32), nullable=True),
    sa.Column('policy_rule_id', sa.String(length=32), nullable=True),
    sa.Column('target_orders_count', sa.Integer(), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.risk_event_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('ix_decisions_autonomy_level', 'decisions', ['autonomy_level'], unique=False)
    op.create_index('ix_decisions_depot_status_time', 'decisions', ['depot_id', 'decision_status', 'decision_timestamp'], unique=False)
    op.create_index(op.f('ix_decisions_etl_run_id'), 'decisions', ['etl_run_id'], unique=False)
    op.create_index('ix_decisions_risk_id', 'decisions', ['risk_event_id'], unique=False)
    op.create_table('equipment_events',
    sa.Column('equipment_event_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('loading_position_id', sa.String(length=32), nullable=True),
    sa.Column('equipment_category', sa.String(length=64), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flow_impact_pct', sa.Integer(), nullable=False),
    sa.Column('operational_notes', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['loading_position_id'], ['loading_positions.loading_position_id'], ),
    sa.PrimaryKeyConstraint('equipment_event_id')
    )
    op.create_index('ix_equipment_depot_status', 'equipment_events', ['depot_id', 'status'], unique=False)
    op.create_index(op.f('ix_equipment_events_etl_run_id'), 'equipment_events', ['etl_run_id'], unique=False)
    op.create_index('ix_equipment_position', 'equipment_events', ['loading_position_id'], unique=False)
    op.create_index('ix_equipment_timestamp', 'equipment_events', ['depot_id', 'event_timestamp'], unique=False)
    op.create_table('loading_orders',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('omc_id', sa.String(length=64), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=16), nullable=False),
    sa.Column('ordered_quantity_litres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_registered_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['omc_id'], ['omcs.omc_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.truck_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_loading_orders_etl_run_id'), 'loading_orders', ['etl_run_id'], unique=False)
    op.create_index('ix_orders_active_depot', 'loading_orders', ['depot_id', 'order_registered_time'], unique=False, postgresql_where=sa.text("order_status IN ('REGISTERED', 'APPROACHING', 'AT_GATE', 'VALIDATED', 'STAGING', 'LOADING')"))
    op.create_index('ix_orders_depot_registered', 'loading_orders', ['depot_id', 'order_registered_time'], unique=False)
    op.create_index('ix_orders_depot_status', 'loading_orders', ['depot_id', 'order_status'], unique=False)
    op.create_index('ix_orders_expected_arrival', 'loading_orders', ['depot_id', 'expected_arrival_time'], unique=False)
    op.create_index('ix_orders_omc_status', 'loading_orders', ['omc_id', 'order_status'], unique=False)
    op.create_index('ix_orders_truck_registered', 'loading_orders', ['truck_id', 'order_registered_time'], unique=False)
    op.create_table('arrival_signals',
    sa.Column('signal_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('signal_source', sa.String(length=64), nullable=False),
    sa.Column('signal_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_quality', sa.String(length=32), nullable=False),
    sa.Column('estimated_distance_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('predicted_arrival_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_arrival_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_arrival_signals_etl_run_id'), 'arrival_signals', ['etl_run_id'], unique=False)
    op.create_index('ix_arrival_signals_order_time', 'arrival_signals', ['order_id', 'signal_timestamp'], unique=False)
    op.create_index('ix_arrival_signals_timestamp', 'arrival_signals', ['signal_timestamp'], unique=False)
    op.create_table('autonomous_actions',
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('control_state', sa.String(length=32), nullable=False),
    sa.Column('target_device_interface', sa.String(length=128), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ack_latency_ms', sa.Integer(), nullable=False),
    sa.Column('execution_result', sa.String(length=64), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('ix_autonomous_actions_decision_id', 'autonomous_actions', ['decision_id'], unique=False)
    op.create_index('ix_autonomous_actions_depot_state', 'autonomous_actions', ['depot_id', 'control_state'], unique=False)
    op.create_index(op.f('ix_autonomous_actions_etl_run_id'), 'autonomous_actions', ['etl_run_id'], unique=False)
    op.create_table('decision_stages',
    sa.Column('stage_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('stage_sequence', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=32), nullable=False),
    sa.Column('stage_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage_status', sa.String(length=32), nullable=False),
    sa.Column('metric_label', sa.String(length=128), nullable=True),
    sa.Column('metric_value', sa.String(length=255), nullable=True),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_index('ix_decision_stages_decision_seq', 'decision_stages', ['decision_id', 'stage_sequence'], unique=False)
    op.create_index(op.f('ix_decision_stages_etl_run_id'), 'decision_stages', ['etl_run_id'], unique=False)
    op.create_index('ix_decision_stages_name', 'decision_stages', ['stage_name'], unique=False)
    op.create_table('gate_events',
    sa.Column('gate_event_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tare_weight_kg', sa.Integer(), nullable=False),
    sa.Column('gross_weight_kg', sa.Integer(), nullable=False),
    sa.Column('rfid_transponder_id', sa.String(length=64), nullable=False),
    sa.Column('gate_lane', sa.String(length=32), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.truck_id'], ),
    sa.PrimaryKeyConstraint('gate_event_id')
    )
    op.create_index('ix_gate_events_depot_time', 'gate_events', ['depot_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_gate_events_etl_run_id'), 'gate_events', ['etl_run_id'], unique=False)
    op.create_index('ix_gate_events_order_time', 'gate_events', ['order_id', 'event_timestamp'], unique=False)
    op.create_index('ix_gate_events_truck_time', 'gate_events', ['truck_id', 'event_timestamp'], unique=False)
    op.create_index('ix_gate_events_type_time', 'gate_events', ['depot_id', 'event_type', 'event_timestamp'], unique=False)
    op.create_table('loading_events',
    sa.Column('loading_event_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('loading_position_id', sa.String(length=32), nullable=False),
    sa.Column('loading_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loading_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_quantity_litres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_quantity_litres', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('loading_duration_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_flow_rate_lpm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dual_arm_used', sa.Boolean(), nullable=False),
    sa.Column('loading_status', sa.String(length=32), nullable=False),
    sa.Column('exception_reason', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['loading_position_id'], ['loading_positions.loading_position_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.PrimaryKeyConstraint('loading_event_id')
    )
    op.create_index('ix_loading_events_depot_start', 'loading_events', ['depot_id', 'loading_start'], unique=False)
    op.create_index(op.f('ix_loading_events_etl_run_id'), 'loading_events', ['etl_run_id'], unique=False)
    op.create_index('ix_loading_events_order_id', 'loading_events', ['order_id'], unique=False)
    op.create_index('ix_loading_events_position_start', 'loading_events', ['loading_position_id', 'loading_start'], unique=False)
    op.create_index('ix_loading_events_status', 'loading_events', ['loading_status'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('omc_id', sa.String(length=64), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_role', sa.String(length=32), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('previous_timing', sa.String(length=128), nullable=True),
    sa.Column('new_timing', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requires_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['omc_id'], ['omcs.omc_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_depot_time', 'notifications', ['depot_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_etl_run_id'), 'notifications', ['etl_run_id'], unique=False)
    op.create_index('ix_notifications_omc_time', 'notifications', ['omc_id', 'timestamp'], unique=False)
    op.create_index('ix_notifications_order_id', 'notifications', ['order_id'], unique=False)
    op.create_index('ix_notifications_priority', 'notifications', ['priority'], unique=False)
    op.create_table('staging_events',
    sa.Column('staging_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('staging_area_id', sa.String(length=64), nullable=False),
    sa.Column('queue_entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queue_exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_duration_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('queue_reason', sa.String(length=128), nullable=False),
    sa.Column('initial_predicted_wait_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_staging_area_depot', 'staging_events', ['depot_id', 'staging_area_id'], unique=False)
    op.create_index('ix_staging_depot_entry', 'staging_events', ['depot_id', 'queue_entry_time'], unique=False)
    op.create_index(op.f('ix_staging_events_etl_run_id'), 'staging_events', ['etl_run_id'], unique=False)
    op.create_index('ix_staging_order_id', 'staging_events', ['order_id'], unique=False)
    op.create_table('validation_events',
    sa.Column('validation_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('validation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('validation_outcome', sa.String(length=32), nullable=False),
    sa.Column('customs_status', sa.String(length=64), nullable=False),
    sa.Column('electronic_manifest_matched', sa.Boolean(), nullable=False),
    sa.Column('exception_reason', sa.String(length=255), nullable=True),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.depot_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['loading_orders.order_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_index('ix_validation_depot_outcome', 'validation_events', ['depot_id', 'validation_outcome'], unique=False)
    op.create_index(op.f('ix_validation_events_etl_run_id'), 'validation_events', ['etl_run_id'], unique=False)
    op.create_index('ix_validation_order_id', 'validation_events', ['order_id'], unique=False)
    op.create_index('ix_validation_start_time', 'validation_events', ['depot_id', 'validation_start'], unique=False)
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('control_state', sa.String(length=32), nullable=False),
    sa.Column('audit_reference_sha256', sa.String(length=64), nullable=False),
    sa.Column('verification_digest', sa.Text(), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['autonomous_actions.action_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index('ix_audit_events_decision_time', 'audit_events', ['decision_id', 'audit_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_etl_run_id'), 'audit_events', ['etl_run_id'], unique=False)
    op.create_index('ix_audit_events_sha256', 'audit_events', ['audit_reference_sha256'], unique=False)
    op.create_table('verification_events',
    sa.Column('verification_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pre_intervention_turnaround_min', sa.Integer(), nullable=False),
    sa.Column('post_intervention_turnaround_min', sa.Integer(), nullable=False),
    sa.Column('expected_reduction_min', sa.Integer(), nullable=False),
    sa.Column('observed_reduction_min', sa.Integer(), nullable=False),
    sa.Column('recovery_attainment_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('exposure_protected_kes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('realized_savings_kes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('etl_run_id', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['autonomous_actions.action_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index('ix_verification_action_id', 'verification_events', ['action_id'], unique=False)
    op.create_index('ix_verification_decision_id', 'verification_events', ['decision_id'], unique=False)
    op.create_index(op.f('ix_verification_events_etl_run_id'), 'verification_events', ['etl_run_id'], unique=False)
    op.create_index('ix_verification_status', 'verification_events', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_status', table_name='verification_events')
    op.drop_index(op.f('ix_verification_events_etl_run_id'), table_name='verification_events')
    op.drop_index('ix_verification_decision_id', table_name='verification_events')
    op.drop_index('ix_verification_action_id', table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index('ix_audit_events_sha256', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_etl_run_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_decision_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_validation_start_time', table_name='validation_events')
    op.drop_index('ix_validation_order_id', table_name='validation_events')
    op.drop_index(op.f('ix_validation_events_etl_run_id'), table_name='validation_events')
    op.drop_index('ix_validation_depot_outcome', table_name='validation_events')
    op.drop_table('validation_events')
    op.drop_index('ix_staging_order_id', table_name='staging_events')
    op.drop_index(op.f('ix_staging_events_etl_run_id'), table_name='staging_events')
    op.drop_index('ix_staging_depot_entry', table_name='staging_events')
    op.drop_index('ix_staging_area_depot', table_name='staging_events')
    op.drop_table('staging_events')
    op.drop_index('ix_notifications_priority', table_name='notifications')
    op.drop_index('ix_notifications_order_id', table_name='notifications')
    op.drop_index('ix_notifications_omc_time', table_name='notifications')
    op.drop_index(op.f('ix_notifications_etl_run_id'), table_name='notifications')
    op.drop_index('ix_notifications_depot_time', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_loading_events_status', table_name='loading_events')
    op.drop_index('ix_loading_events_position_start', table_name='loading_events')
    op.drop_index('ix_loading_events_order_id', table_name='loading_events')
    op.drop_index(op.f('ix_loading_events_etl_run_id'), table_name='loading_events')
    op.drop_index('ix_loading_events_depot_start', table_name='loading_events')
    op.drop_table('loading_events')
    op.drop_index('ix_gate_events_type_time', table_name='gate_events')
    op.drop_index('ix_gate_events_truck_time', table_name='gate_events')
    op.drop_index('ix_gate_events_order_time', table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_etl_run_id'), table_name='gate_events')
    op.drop_index('ix_gate_events_depot_time', table_name='gate_events')
    op.drop_table('gate_events')
    op.drop_index('ix_decision_stages_name', table_name='decision_stages')
    op.drop_index(op.f('ix_decision_stages_etl_run_id'), table_name='decision_stages')
    op.drop_index('ix_decision_stages_decision_seq', table_name='decision_stages')
    op.drop_table('decision_stages')
    op.drop_index(op.f('ix_autonomous_actions_etl_run_id'), table_name='autonomous_actions')
    op.drop_index('ix_autonomous_actions_depot_state', table_name='autonomous_actions')
    op.drop_index('ix_autonomous_actions_decision_id', table_name='autonomous_actions')
    op.drop_table('autonomous_actions')
    op.drop_index('ix_arrival_signals_timestamp', table_name='arrival_signals')
    op.drop_index('ix_arrival_signals_order_time', table_name='arrival_signals')
    op.drop_index(op.f('ix_arrival_signals_etl_run_id'), table_name='arrival_signals')
    op.drop_table('arrival_signals')
    op.drop_index('ix_orders_truck_registered', table_name='loading_orders')
    op.drop_index('ix_orders_omc_status', table_name='loading_orders')
    op.drop_index('ix_orders_expected_arrival', table_name='loading_orders')
    op.drop_index('ix_orders_depot_status', table_name='loading_orders')
    op.drop_index('ix_orders_depot_registered', table_name='loading_orders')
    op.drop_index('ix_orders_active_depot', table_name='loading_orders', postgresql_where=sa.text("order_status IN ('REGISTERED', 'APPROACHING', 'AT_GATE', 'VALIDATED', 'STAGING', 'LOADING')"))
    op.drop_index(op.f('ix_loading_orders_etl_run_id'), table_name='loading_orders')
    op.drop_table('loading_orders')
    op.drop_index('ix_equipment_timestamp', table_name='equipment_events')
    op.drop_index('ix_equipment_position', table_name='equipment_events')
    op.drop_index(op.f('ix_equipment_events_etl_run_id'), table_name='equipment_events')
    op.drop_index('ix_equipment_depot_status', table_name='equipment_events')
    op.drop_table('equipment_events')
    op.drop_index('ix_decisions_risk_id', table_name='decisions')
    op.drop_index(op.f('ix_decisions_etl_run_id'), table_name='decisions')
    op.drop_index('ix_decisions_depot_status_time', table_name='decisions')
    op.drop_index('ix_decisions_autonomy_level', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_risk_events_severity', table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_etl_run_id'), table_name='risk_events')
    op.drop_index('ix_risk_events_depot_status_time', table_name='risk_events')
    op.drop_index('ix_active_risks_partial', table_name='risk_events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('risk_events')
    op.drop_index('ix_quarantine_run_table', table_name='quarantine_records')
    op.drop_index('ix_quarantine_rule', table_name='quarantine_records')
    op.drop_table('quarantine_records')
    op.drop_index('ix_readiness_timestamp', table_name='product_readiness_events')
    op.drop_index('ix_readiness_status', table_name='product_readiness_events')
    op.drop_index('ix_readiness_depot_product', table_name='product_readiness_events')
    op.drop_index(op.f('ix_product_readiness_events_etl_run_id'), table_name='product_readiness_events')
    op.drop_table('product_readiness_events')
    op.drop_index('ix_omcs_volume_tier', table_name='omcs')
    op.drop_index('ix_omcs_primary_depot_id', table_name='omcs')
    op.drop_index(op.f('ix_omcs_etl_run_id'), table_name='omcs')
    op.drop_table('omcs')
    op.drop_index(op.f('ix_loading_positions_etl_run_id'), table_name='loading_positions')
    op.drop_index('ix_loading_positions_depot_id', table_name='loading_positions')
    op.drop_index('ix_loading_positions_bay_number', table_name='loading_positions')
    op.drop_table('loading_positions')
    op.drop_index('ix_trucks_transporter', table_name='trucks')
    op.drop_index(op.f('ix_trucks_registration'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_etl_run_id'), table_name='trucks')
    op.drop_index('ix_trucks_active_status', table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_products_etl_run_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('etl_runs')
    op.drop_index(op.f('ix_depots_etl_run_id'), table_name='depots')
    op.drop_table('depots')
    # ### end Alembic commands ###
