"""Data models for FlowGuard constrained optimization engine."""

from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class OrderOptimizationItem:
    """Operational order details ingested by the optimization solver."""
    order_id: str
    omc_id: str
    product_id: str
    ordered_quantity_litres: float
    arrival_minute: int  # minutes from optimization reference zero
    predicted_turnaround_min: float
    predicted_gate_out_minute: int
    risk_score: float
    sla_window_end_minute: int
    is_active_inside: bool = False
    current_bay_id: Optional[str] = None


@dataclass
class LoadingPositionItem:
    """Loading position/bay details and constraints."""
    loading_position_id: str
    code: str
    bay_number: int
    product_compatibility: str
    has_dual_arm: bool
    standard_flow_rate_lpm: int
    is_high_velocity: bool
    is_available: bool = True
    operational_degradation_pct: float = 0.0


@dataclass
class OptimizationInput:
    """Bounded problem inputs for depot optimization."""
    depot_id: str
    reference_timestamp: datetime
    orders: List[OrderOptimizationItem]
    positions: List[LoadingPositionItem]
    planning_horizon_minutes: int = 240
    solver_timeout_seconds: float = 5.0
    input_diagnostics: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CandidateAction:
    """Candidate operational intervention generated by the optimizer."""
    candidate_id: str
    action_type: str  # RESEQUENCE_QUEUE, ASSIGN_COMPATIBLE_POSITION, PRIORITIZE_HIGH_RISK_ORDER, BALANCE_LOADING_POSITIONS, DEFER_LOW_RISK_ORDER
    target_orders: List[str]
    target_positions: List[str]
    score: float  # 0 to 100
    expected_turnaround_change_min: float  # negative indicates savings
    expected_queue_change_min: float
    expected_risk_change_pts: float
    constraint_status: str  # FEASIBLE_VERIFIED, INFEASIBLE
    explanation: str
    schedule: Dict[str, Dict[str, Any]] = field(default_factory=dict)


@dataclass
class OptimizationResult:
    """Complete output of the constrained optimization solver."""
    depot_id: str
    status: str  # OPTIMAL, FEASIBLE, INFEASIBLE, TIME_LIMIT, NO_FEASIBLE_PLAN
    solve_time_ms: float
    candidates: List[CandidateAction]
    selected_candidate: Optional[CandidateAction]
    baseline_metrics: Dict[str, Any]
    counterfactual_metrics: Dict[str, Any]
    solver_diagnostics: Dict[str, Any]
